project:
  type: website
  output-dir: "docs"
website:
  title: "Shuhan (Alice) Ai"
  navbar:
    background: "#2774AE"
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Presentation"
        file: presentation.qmd
      - text: "Blog Posts"
        file: blog_posts.qmd
      - text: "Teaching"
        file: teaching.qmd
      - text: "CV"
        file: CV.qmd
        
    right:
      - icon: github
        href: https://github.com/AliceAii
      - icon: google
        href: https://scholar.google.com/citations?user=jUyocCQAAAAJ&hl=en&oi=ao
      - icon: linkedin
        href: https://www.linkedin.com/in/shuhan-alice-ai-90146720b/
format:
  html:
    theme:
      light: [cosmo, brand]
      dark: [cyborg, brand]
    css: styles.css
editor: visual