---
title: "Publications"
format: 
  html:
    css: styles.css
---

<style>
.hanging {
  text-indent: -2em;   /* moves first line left */
  margin-left: 2em;    /* indents rest of paragraph */
}
</style>

**Published:**

<div class="hanging">

**Ai, S.** & Eagan, K., (2026). From Club to College: The Impact of Science Clubs/Groups on High School Students’ STEM Major Choice. *Research in Higher Education*, 67, 32. [[Paper]](https://doi.org/10.1007/s11162-026-09892-8)

**Ai, S.**, Eagan, K., Wu, J. (in press). Fueling Ambition: Graduate Degree Aspirations Among Women of Color in STEM. *CBE – Life Science Education.*

**Ai, S.** (2024). Empowering Online Teaching: A System Review of Online Instructors’ Professional Development in Higher Education. *InterActions: UCLA Journal of Education and Information Studies, 19*(1). 
[[Paper]](https://doi.org/10.5070/D41.6661)

-----

**Preprint:**

**Ai, S.** (2026). Causal Fairness Analysis of ADHD Status and High School STEM Outcomes. *arXiv preprint*. [[Paper]](https://arxiv.org/abs/2604.10824) [[Code]](https://github.com/AliceAii/ADHD_STEM-Outcomes_Causal-Fairness-Analysis)


**Ai, S.** (2026). Discussion Network Formation and Evolution in an Online Professional Development Class: Evidence from a MOOC for K-12 Educators. *arXiv preprint*.
[[Paper]](https://arxiv.org/abs/2601.01117)

**Ai, S.**, Kevin, E., Olivares, J., & Jiang, T. (2024). Can Community Cultural Wealth Maintain STEM Career Aspirations of Undergraduate Women of Color? Examining HERI Data. *In annual meeting of the Association for the Study of Higher Education (ASHE), Minneapolis, MN.* 
[[Paper]](https://escholarship.org/uc/item/86c6r5m2)

------

**Technical Reports:**

Omery, F., Montes-Diaz, I., **Ai, S.** (2023). City Fiscal Conditions. *National League of Cities.* 
[[Report]](https://www.nlc.org/resource/city-fiscal-conditions-2023/)

Omeyr, F. & **Ai, S.** (2023). State of the Cities. *National League of Cities.*  [[Report]](https://www.nlc.org/resource/state-of-the-cities-2023/)

---------

**Under Peer review:**

**Ai, S.** (under review). Engaging Future Scientists: The Effect of Science Museum Visits on High School Students’ Science Identity Development. *International Journal of STEM Education.*

**Ai, S.** (under review). Building Professional Ties Online: How Discussion Networks Form and Evolve in a MOOC for K-12 Educators. *Social Networks.*

Wu, J., Li, L., & **Ai, S.** (under review). Finding the Way In: Longitudinal Predictors of Female STEM Joiner Pathways. *AERA Open.* 

Eagan, M. K., Ramos, H., **Ai, S.**, Romero, A. L., & Cobian, K. (under review). BUILDing science identity: Exploring the efficacy and moderation effects of a nationally funded intervention. *Educational Evaluation and Policy Analysis.*

Jiang, T., **Ai, S.**, Jiao, C., Li, K. (R&R). Revealing Hidden Contributions on Research Data: The Potential of Data Paper. *Scientometrics.*


</div>
