{
  "hash": "2709164dc5f7e703dc39f3b4d0418872",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"A Practical Machine Learning Guide in R\"\nauthor: Shuhan (Alice) Ai\ndate: \"2025-11-16\"\ncategories: [R, ML]\ntoc: true\ntoc-depth: 3\ntoc-title: \"Contents\"\ncode-fold: show\ncode-tools: true\nself-contained: true\nimage: \"p1.png\"\n---\n\nMachine learning (ML) has become an increasingly valuable tool in educational research, offering powerful methods to predict student outcomes and identify key factors influencing academic and career trajectories. This tutorial demonstrates how to apply multiple ML algorithms to predict STEM students' science career aspirations using real survey data.\n\n![](p1.png)\n\n**What makes ML-worthy?**\n\nNot every prediction problem needs machine learning. This one does because:\n\n1. **Non-linear relationships**: Science identity + research experience might interact synergistically\n2. **Multiple pathways**: Different combinations can lead to the same outcome\n3. **Hidden patterns**: Humans might miss subtle combinations that algorithms detect\n4. **High dimensionality**: 18+ predictors with complex interactions\n\nBy the end of this tutorial, you'll understand:\n\n- When to use ML (and when traditional methods suffice)\n- How 5 core algorithms work and when to use each\n- How to set up proper cross-validation\n- How to evaluate and compare model performance\n- How to interpret variable importance\n- Common pitfalls and how to avoid them\n\n## 1. When Should You Use Machine Learning?\n\n### 1.1 Use ML When...\n\n#### 1.1.1 The relationship is complex and non-linear\n\nExample from our data:\n\n```\nSimple relationship: \"High science identity → Science career\"\nReality: \n- Identity > 60 AND Research > 6 months → 85% pursue careers\n- Identity < 40 BUT Strong mentorship → Still 60% pursue careers\n- Identity moderate BUT Values scientific contribution → 70% pursue careers\n```\n\nMultiple interacting factors create patterns too complex for simple IF-THEN rules.\n\n#### 1.1.2 Traditional methods show poor fit\n\nIf you run simple regression and get:\n\n- R² < 0.20 (explains less than 20% of variance)\n- Many non-significant predictors\n- Clear patterns in residuals\n\nNow try ML. Non-parametric methods might capture what regression misses.\n\n#### 1.1.3 You have sufficient data\n\n**Rules of thumb:**\n\n- **Minimum**: 10-20 observations per predictor\n- **Comfortable**: 50+ observations per predictor  \n- **Ideal**: 100+ observations per predictor\n\n```\n**Why size matters:**\nSmall data (n=200): ML overfits → Poor generalization\nMedium data (n=500-1000): ML works with careful validation\nLarge data (n=5000+): ML often outperforms simpler methods\n```\n\n#### 1.1.4 Prediction is more important than explanation\n\nTwo different goals:\n\n| Goal | Best Approach | Example Question |\n|------|---------------|------------------|\n| **Prediction** | ML (Random Forest, XGBoost) | \"Which 100 students should we invite to research symposium?\" |\n| **Explanation** | Traditional Regression | \"Does science identity associate with career interest, controlling for GPA?\" |\n| **Both** | Use BOTH | \"Predict with random forest, understand with Logistic Regression\" |\n\nYou're willing to trade interpretability for accuracy\n\n```\nFollowing order from low Accuracy to high accuracy, \nfrom high interpretability to low interpretability\n\nLogistic Regression ← Decision Tree ← Random Forest ← XGBoost\n(β coefficients)      (IF-THEN rules)  (\"black box\")   (\"black box\")\n```\n\n### 1.2 Don't Use ML When...\n\n#### 1.2.1 Your dataset is tiny (n < 200)\n\nWith small data, ML models: overfit training data, perform poorly on new data, show high variance across runs\n\n**Solution**: Use logistic regression with careful variable selection.\n\n#### 1.2.2 You need causal inference\n\nML finds associations, NOT causes.\n\n**Example mistake:**\n\n- ML finds: \"Students who socialize less pursue science careers\"\n- Wrong conclusion: \"Reduce socializing to increase science interest\"\n\n#### 1.2.3 Simple methods already work well\n\nIf logistic regression achieves:\n\n- AUC > 0.85 (excellent discrimination)\n- Clear, significant predictors\n- Good calibration\n\n**Occam's Razor**: Simpler models are better when performance is comparable.\n\n#### 1.2.4 Complete transparency is required\n\nIn high-stakes decisions (loan approval, medical diagnosis, college admissions), stakeholders may demand:\n\n- \"Why was this person rejected?\"\n- \"Show me exactly how you made this decision\"\n\nRandom Forest answer: \"The algorithm voted based on 500 trees...\"  \nLogistic Regression answer: \"Their science identity score was 2 SDs below average, which decreased odds by 73%...\"\n\n## 2. Required Package and Data Load\n\nWe'll use `caret` as our unified ML framework. Think of `caret` as the \"tidyverse of machine learning\", it provides consistent syntax for 200+ algorithms.\n\n### 2.1 Package Overview\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#core ML framework\nlibrary(caret)        # Classification And REgression Training\nlibrary(pROC)         # ROC curves and AUC\n\n#specific algorithms (caret calls these internally)\nlibrary(rpart)        # Decision trees (CART)\nlibrary(randomForest) # Random Forest\nlibrary(xgboost)      # Gradient Boosting  \nlibrary(glmnet)       # Regularized regression\n\n#data manipulation and visualization\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(patchwork)\nlibrary(lattice)\nlibrary(gridExtra)\n```\n:::\n\n\n::: {.callout-tip}\n| Package | Purpose | When to Use |\n|---------|---------|-------------|\n| **caret** | Unified ML interface | Always - handles training, tuning, evaluation |\n| **pROC** | ROC/AUC analysis | Binary classification performance |\n| **rpart** | Decision trees | Interpretable tree-based models |\n| **randomForest** | Ensemble trees | High accuracy, variable importance |\n| **xgboost** | Gradient boosting | State-of-the-art performance |\n| **glmnet** | Regularized regression | High-dimensional data, feature selection |\n:::\n\n\n### 2.2 Data Preparation\n\nOur survey asked students: \"Will you pursue a science-related research career?\"\n\nResponses (5-point Likert scale): 1. Definitely no 2. Probably no 3. Uncertain 4. Probably yes 5. Definitely yes\n\nWe transform this into binary classification:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list = ls())\ndt <- read.csv(\"dt.csv\")\ndt <- dt %>% mutate(SCICAREER_binary = ifelse(as.numeric(SCICAREER) >= 4, 1, 0))\ndt <- dt %>%\n  mutate(SCICAREER_binary = factor(SCICAREER_binary, levels = c(0, 1), labels = c(\"No\", \"Yes\")))\ntable(dt$SCICAREER_binary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  No  Yes \n1836 1510 \n```\n\n\n:::\n\n```{.r .cell-code}\nprop.table(table(dt$SCICAREER_binary))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n       No       Yes \n0.5487149 0.4512851 \n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_vars <- c(\"SCICAREER_binary\",\"SCIENCE_SELF_EFFICACY\", \"SCIENCE_IDENTITY\", \"ACADEMIC_SELFCONCEPT\", \"HABITS_OF_MIND\", \"MAJORGPA\", \"GOAL19\", \"GOAL11\", \"GOAL04\",\"RESEARCH\", \"HPW17\", \"HPW29\", \"HPW28\", \"HPW09\", \"HPW04\", \"HPW24\", \"HPW06\", \"HPW27\", \"HPW02\")\n\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ lubridate 1.9.4     ✔ tibble    3.3.0\n✔ purrr     1.1.0     ✔ tidyr     1.3.1\n✔ readr     2.1.5     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ gridExtra::combine()   masks dplyr::combine(), randomForest::combine()\n✖ tidyr::expand()        masks Matrix::expand()\n✖ dplyr::filter()        masks stats::filter()\n✖ dplyr::lag()           masks stats::lag()\n✖ purrr::lift()          masks caret::lift()\n✖ randomForest::margin() masks ggplot2::margin()\n✖ tidyr::pack()          masks Matrix::pack()\n✖ dplyr::slice()         masks xgboost::slice()\n✖ tidyr::unpack()        masks Matrix::unpack()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\ndt_model <- dt %>% select(all_of(model_vars)) %>% drop_na()  # Listwise deletion (missing rate < 2%)\n\nfor(var in model_vars[-1]) {\n  dt_model[[var]] <- as.numeric(as.character(dt_model[[var]]))\n}\n\ndim(dt_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3346   19\n```\n\n\n:::\n:::\n\nPredictors:\n\n- `SCIENCE_SELF_EFFICACY`\n- `SCIENCE_IDENTITY`\n- `ACADEMIC_SELFCONCEPT`\n- `HABITS_OF_MIND`\n- `MAJORGPA`: Major GPA (1=D to 8=A/A+)\n- `GOAL19`: Making theoretical contribution to science (1-4 scale)\n- `GOAL11`: Helping others in difficulty (1-4 scale)\n- `GOAL04`: Becoming authority in field (1-4 scale)\n- `RESEARCH`: Months working on professor's research (0 to 25+ months)\n- `HPW17`: Hours studying/homework\n- `HPW29`: Hours studying with others\n- `HPW28`: Hours socializing in person\n- `HPW09`: Hours using social media\n- `HPW04`: Hours in student clubs\n- `HPW24`: Hours watching TV/videos\n- `HPW06`: Hours exercising/sports\n- `HPW27`: Hours working on campus\n- `HPW02`: Hours career planning\n\n## 3. Cross-Validation\n\n### 3.1 The Problem: Why We Need Cross-Validation\n\n**Bad approach**:\n```r\n#Train on ALL data\nmodel <- train(outcome ~ ., data = all_data)\n\n#Test on THE SAME data\npredictions <- predict(model, all_data)\naccuracy <- mean(predictions == all_data$outcome)\n#Accuracy = 95%\n```\n\n**The problem:** This is like teaching a student with practice questions, then testing them on **the exact same questions**. Of course they'll do well. But can they handle *new* questions?\n\nThis is called **overfitting**, the model memorized the training data but won't generalize to new students.\n\n### 3.2 The Solution: Cross-Validation\n\n**Cross-validation** tests models on data they haven't seen during training.\n\n**10-Fold Cross-Validation** (our approach):\n\n1. Split data into 10 equal \"folds\" (10% each)\n2. Train on 9 folds, test on 1 fold (repeat 10 times)\n3. Each observation is in the test set exactly once\n4. Average performance across all 10 folds\n\n**Visual representation:**\n\n```\nIteration 1: [Test] [Train] [Train] [Train] [Train] [Train] [Train] [Train] [Train] [Train]\nIteration 2: [Train] [Test] [Train] [Train] [Train] [Train] [Train] [Train] [Train] [Train]\nIteration 3: [Train] [Train] [Test] [Train] [Train] [Train] [Train] [Train] [Train] [Train]\n...\nIteration 10: [Train] [Train] [Train] [Train] [Train] [Train] [Train] [Train] [Train] [Test]\n\nFinal metric = Average(Iteration 1, Iteration 2, ..., Iteration 10)\n```\n\n### 3.3 Setting Up Cross-Validation in caret\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(612)   \n\ntrain_control <- trainControl(\n  method = \"cv\",                    # Cross-validation\n  number = 10,                      # 10 folds\n  savePredictions = \"final\",        # Save predictions for later analysis\n  classProbs = TRUE,                # Calculate P(Yes) and P(No)\n  summaryFunction = twoClassSummary # Compute ROC, Sensitivity, Specificity\n)\n```\n:::\n\n\n::: {.callout-tip}\nWith `twoClassSummary`, caret computes:\n\n1. **ROC** (Receiver Operating Characteristic): Area under ROC curve (0.5 = random, 1.0 = perfect)\n2. **Sens** (Sensitivity): Of students who WILL pursue careers, % we correctly identify  \n3. **Spec** (Specificity): Of students who WON'T pursue careers, % we correctly identify\n:::\n\n## 4. Machine Learning Algorithms\n\nWe'll train 5 algorithms, each with different strengths. \n\n### Algorithm Selection\n\n| Algorithm | Strength | Use Case | Computational Cost |\n|-----------|----------|----------|-------------------|\n| **Logistic Regression** | Interpretability | Understanding effects | Low |\n| **Decision Tree** | Visual explanation | Presenting to stakeholders | Low |\n| **Random Forest** | High accuracy | Best predictions | Medium |\n| **KNN** | Non-parametric flexibility | Unusual patterns | Medium |\n| **XGBoost** | Maximum performance | Competitions, production | Medium-High |\n\n**Our approach:** Train all 5, compare performance, use best for predictions and most interpretable for understanding.\n\n\n### 4.1. Logistic Regression\n\nClassic statistical method - the \"generalized linear regression\" of classification.\n\nLogistic regression models the probability of \"Yes\" using a function:\n\n$$P(\\text{Yes}) = \\frac{1}{1 + e^{-(\\beta_0 + \\beta_1X_1 + \\beta_2X_2 + ... + \\beta_pX_p)}}$$\nWhere:\n\n- $\\beta_0$ = intercept\n- $\\beta_i$ = coefficient for predictor $X_i$\n- Higher $\\beta$ = stronger positive effect\n- Negative $\\beta$ = negative effect\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_logit <- train(SCICAREER_binary ~ ., data = dt_model, method = \"glm\", family = \"binomial\",         \n  trControl = train_control, metric = \"ROC\")\n\nprint(m_logit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeneralized Linear Model \n\n3346 samples\n  18 predictor\n   2 classes: 'No', 'Yes' \n\nNo pre-processing\nResampling: Cross-Validated (10 fold) \nSummary of sample sizes: 3012, 3012, 3011, 3012, 3012, 3011, ... \nResampling results:\n\n  ROC        Sens       Spec     \n  0.8077944  0.7805179  0.6781457\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(m_logit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nNULL\n\nCoefficients:\n                       Estimate Std. Error z value Pr(>|z|)    \n(Intercept)           -5.670138   0.482579 -11.750  < 2e-16 ***\nSCIENCE_SELF_EFFICACY  0.007211   0.005354   1.347  0.17803    \nSCIENCE_IDENTITY       0.102336   0.007290  14.037  < 2e-16 ***\nACADEMIC_SELFCONCEPT  -0.025231   0.005804  -4.347 1.38e-05 ***\nHABITS_OF_MIND         0.001720   0.005770   0.298  0.76565    \nMAJORGPA              -0.057779   0.031257  -1.849  0.06453 .  \nGOAL19                 0.628349   0.052470  11.975  < 2e-16 ***\nGOAL11                -0.269491   0.058384  -4.616 3.92e-06 ***\nGOAL04                -0.026149   0.055420  -0.472  0.63704    \nRESEARCH               0.160162   0.024968   6.415 1.41e-10 ***\nHPW17                  0.075667   0.032725   2.312  0.02077 *  \nHPW29                 -0.034236   0.031198  -1.097  0.27248    \nHPW28                 -0.088388   0.030907  -2.860  0.00424 ** \nHPW09                 -0.039477   0.029997  -1.316  0.18816    \nHPW04                  0.012361   0.027557   0.449  0.65375    \nHPW24                  0.004450   0.030052   0.148  0.88228    \nHPW06                  0.017729   0.026883   0.659  0.50959    \nHPW27                 -0.029158   0.020282  -1.438  0.15054    \nHPW02                  0.015218   0.035392   0.430  0.66720    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 4606.7  on 3345  degrees of freedom\nResidual deviance: 3506.9  on 3327  degrees of freedom\nAIC: 3544.9\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n### 4.2 Decision Tree (CART)\n\n**Think of it as:** A flowchart that asks yes/no questions to make predictions.\n\n**How it works:**\n\nThe algorithm builds a tree by repeatedly finding the best \"split\":\n\n```\n                     [Root: All 3346 students]\n                              |\n          Is SCIENCE_IDENTITY > 55?\n         /                          \\\n      Yes                            No\n       |                              |\n  [2100 students]              [1246 students]\n  70% pursue careers           30% pursue careers\n       |                              |\n  RESEARCH >= 4 months?        GOAL19 >= 3?\n   /           \\                /          \\\n Yes           No             Yes          No\n[1500]        [600]          [400]        [846]\n85%           45%            55%          18%\nPREDICT: Yes  PREDICT: No    PREDICT: Yes PREDICT: No\n```\n\n**Strengths:**\n\n- Highly interpretable: Anyone can follow the logic\n- Handles non-linearity: Captures complex patterns automatically\n- No scaling needed: Works with raw data (unlike KNN)\n- Automatic interaction detection: Finds interactions without manual specification\n- Missing data handling: Can work with missing values\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_tree <- train(SCICAREER_binary ~ ., data = dt_model, method = \"rpart\",\n  trControl = train_control, metric = \"ROC\", tuneLength = 10    )\n\n#visualize the tree\nlibrary(rpart.plot)\nrpart.plot(m_tree$finalModel, type = 4, extra = 2,              \n           fallen.leaves = TRUE, main = \"Decision Tree for Science Career Prediction\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n### 4.3 Random Forest\n\n**Think of it as:** A committee of decision trees voting on predictions.\n\n**How it works:**\n\nRandom Forest creates many trees (default: 500) and averages their predictions:\n\n```\nTree 1: Uses random sample of data + random subset of predictors → Predicts \"Yes\"\nTree 2: Uses different random sample + different predictors → Predicts \"Yes\"  \nTree 3: Uses different random sample + different predictors → Predicts \"No\"\nTree 4: Uses different random sample + different predictors → Predicts \"Yes\"\n...\nTree 500: Uses different random sample + different predictors → Predicts \"Yes\"\n\nFinal prediction: Majority vote = \"Yes\" (350/500 = 70% probability)\n```\n\n**Two sources of randomness:**\n\n1. **Bootstrap samples**: Each tree sees different subset of data (sampling with replacement)\n2. **Random features**: Each split considers only random subset of predictors (typically $\\sqrt{p}$ predictors)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_rf <- train(SCICAREER_binary ~ ., data = dt_model, method = \"rf\",\n  trControl = train_control, metric = \"ROC\", tuneLength = 5,  importance = TRUE)\n\nvarImp(m_rf)\n\nplot(varImp(m_rf), top = 10, main = \"Top 10 Most Important Variables\")\n```\n:::\n\n\n### 4.4 K-Nearest Neighbors (KNN)\n\n**Think of it as:** \"predictions based on similar observations.\n\n**How it works:**\n\nFor a new student:\n\n1. **Find the k most similar students** in training data\n2. **Check their outcomes**: How many pursued science careers?\n3. **Predict based on majority**: If 4 out of 5 neighbors = \"Yes\" → predict 80% probability \"Yes\"\n\n**Similarity metric:**\n\nEuclidean distance in 18-dimensional space:\n\n$$d(i,j) = \\sqrt{\\sum_{p=1}^{18} (x_{ip} - x_{jp})^2}$$\nWhere $x_{ip}$ is value of predictor $p$ for student $i$.\n\n::: {.callout-note}\nFeature scaling required. \n\nWithout scaling:\n```\nSCIENCE_SELF_EFFICACY: range 20-80 (scale of 60)\nMAJORGPA: range 2-4 (scale of 2)\n\nDistance dominated by SCIENCE_SELF_EFFICACY! \nMAJORGPA essentially ignored.\n```\n\nWith scaling (mean = 0, SD = 1):\n```\nBoth variables: range ≈ -3 to +3\nEqual contribution to distance calculation\n```\n::: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_knn <- train(SCICAREER_binary ~ ., data = dt_model, method = \"knn\", trControl = train_control,\n  metric = \"ROC\", preProcess = c(\"center\", \"scale\"),  # Scale features\n  tuneLength = 10)\n```\n:::\n\n\n**Hyperparameter: k (number of neighbors)**\n\n- **Small k** (e.g., k=1): Very sensitive to noise, overfits\n- **Large k** (e.g., k=50): Oversmooths, underfits\n- **Default**: Often $\\sqrt{n}$ (e.g., $\\sqrt{3346} \\approx 58$)\n\n**Visual intuition:**\n\nImagine plotting two variables (Science Identity vs. Research Experience):\n\n::: {.callout-note}\n```\nHigh Research ↑\n             |   Yes  Yes  Yes\n             |      Yes\n             | No      Yes\n             |   No  No\n             |No  No     Yes\nLow Research +----------------→ High Identity\n```\n\nFor a new student at (Identity=60, Research=5):\n\n- k=3: Find 3 closest points → Predict based on their outcomes\n- Nearby points: 2 \"Yes\", 1 \"No\" → Predict \"Yes\" (67% probability)\n::: \n\n### 4.5 XGBoost (Extreme Gradient Boosting)\n\n**Think of it as:** Sequential problem-solving where each step corrects previous mistakes.\n\n**How it works:**\n\nXGBoost builds trees sequentially, each focusing on previous errors:\n\n```\nStep 1: Build Tree 1 → Makes predictions → Calculate errors\n        Predictions: [0.5, 0.6, 0.7, ...]\n        Actual:      [0, 1, 1, ...]\n        Errors:      [+0.5, -0.4, -0.3, ...]\n\nStep 2: Build Tree 2 to predict the ERRORS from Tree 1\n        Focus on observations Tree 1 got wrong\n        \nStep 3: Build Tree 3 to predict remaining errors\n        Continue correcting mistakes\n\n...\n\nStep 100: Final prediction = Tree1 + η×Tree2 + η×Tree3 + ... + η×Tree100\n          Where η (eta) is learning rate (typically 0.1-0.3)\n```\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_xgb <- train(SCICAREER_binary ~ ., data = dt_model, method = \"xgbTree\", trControl = train_control,\n  metric = \"ROC\", tuneLength = 3, verbosity = 0)\n```\n:::\n\n\n### 4.6 Model Training Summary\n\nNow let's train all 5 models and compare them:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#set seed for reproducibility\nset.seed(612)\n\n#setup cross-validation\ntrain_control <- trainControl(\n  method = \"cv\",\n  number = 10,\n  savePredictions = \"final\",\n  classProbs = TRUE,\n  summaryFunction = twoClassSummary\n)\n\nm_logit <- train(SCICAREER_binary ~ ., data = dt_model, method = \"glm\",\n                 family = \"binomial\", trControl = train_control, metric = \"ROC\")\n\nm_tree <- train(SCICAREER_binary ~ ., data = dt_model, method = \"rpart\",\n                trControl = train_control, metric = \"ROC\", tuneLength = 10)\n\nm_rf <- train(SCICAREER_binary ~ ., data = dt_model, method = \"rf\",\n              trControl = train_control, metric = \"ROC\", \n              tuneLength = 5, importance = TRUE)\n\nm_knn <- train(SCICAREER_binary ~ ., data = dt_model, method = \"knn\",\n               trControl = train_control, metric = \"ROC\",\n               preProcess = c(\"center\", \"scale\"), tuneLength = 10)\n\nm_xgb <- train(SCICAREER_binary ~ ., data = dt_model, method = \"xgbTree\",\n               trControl = train_control, metric = \"ROC\",\n               tuneLength = 3, verbosity = 0)\n```\n:::\n\n\n## 5. Model Evaluation & Comparison\n\n### 5.1 Performance Metrics\n\nFor binary classification, we use three key metrics:\n\n#### 5.1.1 ROC AUC (Area Under the Curve)\n\n**What it measures:** Overall discriminatory ability, can the model distinguish \"Yes\" from \"No\"?\n\n**Scale:** 0.5 (random guessing) to 1.0 (perfect classification)\n\n- **0.90-1.00**: Excellent\n- **0.80-0.90**: Good\n- **0.70-0.80**: Fair\n- **0.60-0.70**: Poor\n- **0.50-0.60**: Failure\n\n**Geometric meaning:**\n\nROC curve plots:\n- X-axis: False Positive Rate (1 - Specificity)\n- Y-axis: True Positive Rate (Sensitivity)\n\nAUC = Area under this curve.\n\n**Intuition:** Pick one random \"Yes\" student and one random \"No\" student. AUC = probability the model assigns higher score to the \"Yes\" student.\n\nExample: AUC = 0.81 means model correctly ranks pairs 81% of the time.\n\n#### 5.1.2 Sensitivity (True Positive Rate / Recall)\n\n**What it measures:** Of students who WILL pursue science careers, what % do we correctly identify?\n\n**Formula:** \n$$\\text{Sensitivity} = \\frac{\\text{True Positives}}{\\text{True Positives + False Negatives}}$$\n\n**Example:**\n\n- 100 students actually pursue science careers\n- Model identifies 82 of them\n- Sensitivity = 82/100 = 0.82 (82%)\n- We missed 18 students (false negatives)\n\n#### 5.1.3 Specificity (True Negative Rate)\n\n**What it measures:** Of students who WON'T pursue science careers, what % do we correctly identify?\n\n**Formula:**\n$$\\text{Specificity} = \\frac{\\text{True Negatives}}{\\text{True Negatives + False Positives}}$$\n\n**Example:**\n\n- 100 students don't pursue science careers\n- Model correctly identifies 70 of them\n- Specificity = 70/100 = 0.70 (70%)\n- We misclassified 30 students as \"Yes\" (false positives)\n\n### 5.2 The Sensitivity-Specificity Tradeoff\n\nYou can't maximize both simultaneously.\n\n**High threshold** (predict \"Yes\" only when very confident):\n- ↑ Specificity (few false alarms)\n- ↓ Sensitivity (miss some true positives)\n\n**Low threshold** (predict \"Yes\" liberally):\n- ↑ Sensitivity (catch most true positives)\n- ↓ Specificity (many false alarms)\n\n\n| Threshold | Sensitivity | Specificity | Interpretation |\n|-----------|-------------|-------------|----------------|\n| 0.3 | 0.95 | 0.40 | Catch almost everyone interested, but many false invites |\n| 0.5 | 0.78 | 0.68 | Balanced approach |\n| 0.7 | 0.55 | 0.85 | Conservative - only invite very likely candidates |\n\n### 5.3 Comparing Our Models\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Combine all models\nresults <- resamples(list(\n  Logistic = m_logit,\n  Tree = m_tree,\n  RandomForest = m_rf,\n  KNN = m_knn,\n  XGBoost = m_xgb\n))\n\n# Summary statistics\nsummary(results)\n```\n:::\n\n\n**Example output:**\n\n```\nModels: Logistic, Tree, RandomForest, KNN, XGBoost\nNumber of resamples: 10\n\nROC\n              Min.   1st Qu.  Median   Mean   3rd Qu.  Max.\nLogistic     0.792  0.796    0.805   0.809   0.814   0.847\nTree         0.716  0.745    0.783   0.773   0.792   0.827\nRandomForest 0.771  0.792    0.801   0.804   0.816   0.838\nKNN          0.741  0.763    0.775   0.775   0.791   0.807\nXGBoost      0.786  0.801    0.809   0.810   0.820   0.839\n\nSens\n              Min.   1st Qu.  Median   Mean   3rd Qu.  Max.\nLogistic     0.745  0.769    0.790   0.788   0.807   0.821\nTree         0.668  0.712    0.746   0.740   0.769   0.793\nRandomForest 0.739  0.760    0.777   0.781   0.794   0.836\nKNN          0.761  0.801    0.812   0.812   0.833   0.853\nXGBoost      0.717  0.736    0.779   0.767   0.788   0.810\n\nSpec\n              Min.   1st Qu.  Median   Mean   3rd Qu.  Max.\nLogistic     0.603  0.664    0.682   0.683   0.710   0.748\nTree         0.589  0.649    0.669   0.683   0.720   0.788\nRandomForest 0.589  0.634    0.659   0.666   0.712   0.722\nKNN          0.523  0.578    0.589   0.593   0.609   0.662\nXGBoost      0.603  0.684    0.689   0.697   0.722   0.768\n```\n\n### 5.4 Visualizing Performance\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#create comparison plots\nperf_p1 <- bwplot(results, metric = \"ROC\", main = \"ROC AUC across 10 Folds\")\nperf_p2 <- bwplot(results, metric = \"Sens\", main = \"Sensitivity across 10 Folds\")\nperf_p3 <- bwplot(results, metric = \"Spec\", main = \"Specificity across 10 Folds\")\n\n#combine\nlibrary(gridExtra)\npng(\"model_performance.png\", width = 15, height = 5, units = \"in\", res = 300, bg = \"white\")\ngrid.arrange(perf_p1, perf_p2, perf_p3, ncol = 3)\ndev.off()\n```\n:::\n\n\n## 6. Variable Importance Analysis\n\n### 6.1 How Different Models Measure Importance\n\n| Model | Importance Metric | What It Measures |\n|-------|------------------|------------------|\n| **Logistic** | Absolute coefficient | Direct effect size on log-odds |\n| **Tree** | Split improvement | How much variable improves predictions when used |\n| **Random Forest** | Gini importance | Average impurity reduction across 500 trees |\n| **XGBoost** | Gain | Total improvement in objective function |\n\n**All metrics scaled to 0-100** where 100 = most important variable in that model.\n\n### 6.2 Extracting Importance\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_importance <- function(model, model_name) {\n  tryCatch({\n    imp <- varImp(model, scale = TRUE)\n    data.frame(\n      Variable = rownames(imp$importance),\n      Importance = imp$importance[, 1],\n      Model = model_name\n    )\n  }, error = function(e) NULL)\n}\n\nlogit_imp <- get_importance(m_logit, \"Logistic\")\ntree_imp <- get_importance(m_tree, \"Tree\")\nrf_imp <- get_importance(m_rf, \"RandomForest\")\nxgb_imp <- get_importance(m_xgb, \"XGBoost\")\n\nall_imp <- bind_rows(logit_imp, tree_imp, rf_imp, xgb_imp)\n\ntop10_vars <- all_imp %>%\n  group_by(Variable) %>%\n  summarise(Avg_Importance = mean(Importance, na.rm = TRUE)) %>%\n  arrange(desc(Avg_Importance)) %>%\n  head(10) %>%\n  pull(Variable)\n\nplot_data <- all_imp %>% filter(Variable %in% top10_vars)\n\nggplot(plot_data, \n       aes(x = reorder(Variable, Importance), \n           y = Importance, fill = Model)) +\n  geom_col(position = \"dodge\", alpha = 0.8) +\n  coord_flip() +\n  scale_fill_brewer(palette = \"Set2\") +\n  labs(title = \"Top 10 Predictors Across 4 Models\",\n       x = NULL, y = \"Importance (0-100)\") +\n  theme_minimal() +\n  theme(plot.title = element_text(face = \"bold\", size = 12),\n        legend.position = \"top\")\n```\n:::\n\n\n### 6.3 Interpreting Variable Importance\n\n**Example results:**\n\n| Variable | Average Importance | Interpretation |\n|----------|-------------------|----------------|\n| **SCIENCE_IDENTITY** | 95.2 | Strongest predictor - identifying as a \"science person\" matters most |\n| **GOAL19** (Theoretical contribution) | 78.4 | Valuing scientific contribution is key motivator |\n| **RESEARCH** | 55.1 | Research experience strongly predicts career plans |\n| **SCIENCE_SELF_EFFICACY** | 42.3 | Confidence in scientific ability matters |\n| **ACADEMIC_SELFCONCEPT** | 28.7 | General academic confidence plays a role |\n| **HPW28** (Socializing) | 18.2 | Time socializing has small negative association |\n| **GOAL11** (Helping others) | 15.8 | Competing value - reduces science career interest |\n| **HABITS_OF_MIND** | 12.4 | Scientific thinking dispositions matter less than identity |\n| **HPW17** (Studying) | 10.9 | Study time has small positive effect |\n| **MAJORGPA** | 8.3 | GPA has small prediction importance |\n\nPractical Guidance:\n\n**Identity > Ability**\n\nSCIENCE_IDENTITY (95.2) >> MAJORGPA (8.3)\n\n**Implication**: Students who see themselves as \"science people\" pursue science careers regardless of grades. Focus interventions on building science identity.\n\n**Undergraduate Research Experiences Matter**\n\n**Implication**: Provide undergraduate research opportunities. These experiences shape career decisions more than classroom performance.\n\n## More readings:\n\n- [caret package](http://topepo.github.io/caret/)\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}