{
  "hash": "cf54a64134438e44e3b30154c559c5dc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bayesian Methods Part 4: Regression with rstanarm --- From Logistic to Ordered Models\"\nauthor: Shuhan (Alice) Ai\ndate: \"2026-05-23\"\ncategories: [Bayesian, R]\nformat:\n  html:\n    toc: true\n    toc-title: Contents\n    code-fold: false\n    self-contained: true\nimage: \"cover.png\"\nexecute:\n  warning: false\n  message: false\n---\n\n[Part 1](https://aliceaii.github.io/posts/bayesian1/) through [Part 3](https://aliceaii.github.io/posts/bayesian3/) we worked with one simple model the whole way: the Beta-Binomial. It was a friendly place to start because everything had a clean formula. The posterior was just another Beta distribution, and updating our beliefs came down to adding up counts. That was on purpose. With the math staying out of the way, we could focus on the idea itself: prior \\times likelihood \\rightarrow posterior, and then using that posterior to make predictions and build credible intervals.\n\nBut that clean formula is a special case, and most real models don't get it. As soon as we move to regression --- where the outcome depends on several predictors at once through a nonlinear link --- the neat algebra goes away. Logistic regression has no clean formula for the posterior. So we fall back on the one thing we can always do: instead of solving for the posterior, we draw samples from it.\n\nThat's what this post is about: how to actually run a Bayesian regression when there's no formula to lean on. We'll do it with Markov Chain Monte Carlo (MCMC) through the rstanarm package. It fits the same kinds of regression models we already know (the syntax looks just like glm), but instead of handing back a single best estimate for each coefficient, it gives you a full distribution of plausible values. Along the way, we'll explore four ideas that the simple Beta-Binomial model couldn't show us:\n\n- **Building and comparing models** with weakly informative priors and leave-one-out cross-validation.\n- **Encoding a substantive prior belief** and watching the posterior land between prior and data.\n- **Rescuing a broken likelihood** --- the case where the classical MLE runs off to infinity and a prior quietly saves it.\n- **Going beyond binary outcomes** with probit links and ordered (multinomial) regression.\n\nOur running example is the **American National Election Study (NES)**, a long-running survey of U.S. voters. We'll use a few different election years to predict how people voted and which party they identified with, based on their background and political views.\n\n\n## Setup: The NES Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(foreign)    # read .dta\nlibrary(rstanarm)   # Bayesian GLMs via MCMC (Stan)\nlibrary(bayesplot)\nlibrary(loo)        # leave-one-out cross-validation\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(knitr)\n\noptions(mc.cores = 4)\ntheme_set(bayesplot::theme_default(base_size = 11))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase <- \"https://faculty.stat.ucla.edu/handcock/216/examples/nes/\"\nnes_raw <- read.dta(paste0(base, \"nes5200_processed_voters_realideo.dta\"),\n                    convert.factors = FALSE)\n\n# Drop third-party candidates; recode presvote as 1 = Republican, 0 = Democrat\nNes.red <- nes_raw[nes_raw$presvote < 3, ]\nNes.red$presvote <- ifelse(Nes.red$presvote == 2, 1, 0)\n\ndim(Nes.red)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 41199    62\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(Nes.red$presvote, useNA = \"ifany\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    0     1  <NA> \n 7387  7853 25959 \n```\n\n\n:::\n:::\n\n\nA quick codebook for the variables we'll lean on:\n\n| Variable    | Coding                                                                 |\n|-------------|------------------------------------------------------------------------|\n| `presvote`  | 1 = Republican, 0 = Democrat                                           |\n| `female`    | 1 = female, 0 = male                                                    |\n| `black`     | 1 = Black, 0 = non-Black                                                |\n| `educ3`     | 1 ($\\leq$ 8 grades) ... 7 (advanced degree)                             |\n| `income`    | 1 (lowest quintile) ... 5 (highest quintile)                            |\n| `partyid7`  | 1 (Strong Democrat) ... 7 (Strong Republican)                           |\n| `real_ideo` | 1 (Extremely liberal) ... 7 (Extremely conservative)                    |\n| `ideo_feel` | Liberal--conservative thermometer (0--100)                              |\n| `age`       | Respondent's age in years                                               |\n\n## 1. Meet `rstanarm`\n\n`rstanarm` lets us fit Bayesian versions of familiar regression models with almost the same code we'd use for `glm`. Where we would write `glm(y ~ x, family = binomial)`, we write `stan_glm(y ~ x, family = binomial)` --- same formula, same `family`, same `data`. The difference is: instead of maximizing the likelihood down to a single point estimate, `rstanarm` hands the model to **Stan**, which runs MCMC to draw thousands of samples from the full posterior. Every coefficient comes back as a distribution, not a number plus a standard error.\n\nThe functions we'll lean on:\n\n| Function | What it does |\n|:--|:--|\n| `stan_glm()` | Bayesian GLMs --- logistic and probit regression here |\n| `stan_polr()` | Bayesian ordered logistic regression (Section 6) |\n| `prior_summary()` | reports the priors a model actually used |\n| `posterior_epred()` | posterior draws of the fitted probabilities |\n| `pp_check()` | posterior predictive checks |\n| `loo()`, `loo_compare()` | leave-one-out cross-validation for model comparison |\n\nTwo conventions appear in every fit below: `seed` makes the MCMC reproducible, and `refresh = 0` silences the sampler's progress output. After fitting, `as.matrix(model)` pulls the draws out as a matrix --- one column per parameter, one row per draw --- which is how we compute medians, intervals, and densities by hand throughout.\n\n::: {.callout-note}\n## What \"weakly informative\" actually means\nBy default, `stan_glm` puts an independent Normal prior, centered at 0, on each coefficient --- roughly $\\mathcal{N}(0,\\ 2.5)$ on the log-odds scale once the predictor is rescaled. The point of the scale is to be wide enough to let the data lead, but narrow enough to rule out the absurd.\n\nHere is why $2.5$ counts as \"weak\" rather than \"uninformative.\" On the log-odds scale, a coefficient of $2.5$ already means a one-unit change in the predictor multiplies the odds by $e^{2.5} \\approx 12$. A coefficient of $10$ would mean a multiplier of $e^{10} \\approx 22{,}000$ --- an effect that essentially never shows up in real social data. The $\\mathcal{N}(0, 2.5)$ prior places almost no probability that far out, so it quietly says *\"implausibly huge effects are off the table\"* while staying agnostic about every reasonable value in between.\n\nThat gentle nudge is usually invisible when the data are rich, but it does two useful jobs: it keeps the sampler stable, and (as we'll see in Section 4) it rescues a fit where a perfectly flat prior would let a coefficient run off to infinity. When we genuinely know more (Section 3), we can swap in a tighter, informative prior; `prior_summary()` always reports what a model actually used.\n:::\n\n## 2. Bayesian Logistic Regression: The 1992 Presidential Vote\n\n### 2.1 Why We Can't Just Update Two Numbers Anymore\n\nIn the Beta-Binomial world, a single probability $\\theta$ governed everything, and the prior was conjugate. In a logistic regression, the probability of voting Republican depends on a respondent's age, race, income, ideology, and so on:\n\n$$\\Pr(\\text{vote}_i = 1) = \\text{logit}^{-1}(\\beta_0 + \\beta_1 x_{i1} + \\cdots + \\beta_k x_{ik})$$\n\nThe parameters are now a whole vector $\\boldsymbol\\beta$, and the Bernoulli likelihood combined with any sensible prior on $\\boldsymbol\\beta$ gives a posterior with no closed form. There is no \"add the counts\" shortcut. Instead, MCMC explores the posterior by simulating a Markov chain whose stationary distribution is the posterior, and we summarize the draws. We can use `stan_glm`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnes92 <- Nes.red %>%\n  filter(year == 1992) %>%\n  select(presvote, female, black, age, income, educ3,\n         partyid7, real_ideo, ideo_feel) %>%\n  na.omit()\n\nnrow(nes92)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 921\n```\n\n\n:::\n:::\n\n\n### 2.2 A Classical Baseline\n\nIt helps to anchor on the familiar `glm` first, so we can see what the Bayesian version adds (and, later, where it breaks).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_classical <- glm(presvote ~ age + black + income + real_ideo + income:real_ideo,\n                     family = binomial(link = \"logit\"), data = nes92)\nsummary(fit_classical)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = presvote ~ age + black + income + real_ideo + income:real_ideo, \n    family = binomial(link = \"logit\"), data = nes92)\n\nCoefficients:\n                  Estimate Std. Error z value Pr(>|z|)    \n(Intercept)      -2.134072   1.036506  -2.059  0.03950 *  \nage              -0.006309   0.005045  -1.250  0.21113    \nblack            -3.317605   0.571653  -5.804 6.49e-09 ***\nincome           -0.786441   0.322521  -2.438  0.01475 *  \nreal_ideo         0.411764   0.226655   1.817  0.06926 .  \nincome:real_ideo  0.224855   0.072240   3.113  0.00185 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1261.87  on 920  degrees of freedom\nResidual deviance:  831.43  on 915  degrees of freedom\nAIC: 843.43\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n### 2.3 Three Bayesian Models\n\nWe fit a short sequence of models, from the classical specification to a richer one. The default `rstanarm` priors are weakly informative Normals on the coefficients --- gentle enough to let the data speak, strong enough to keep things stable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 1: the classical specification, refit the Bayesian way\nm1 <- stan_glm(presvote ~ age + black + income + real_ideo + income:real_ideo,\n               family = binomial(link = \"logit\"),\n               data = nes92, seed = 215, refresh = 0)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 2: add party ID, gender, education, and the ideology thermometer\nm2 <- stan_glm(presvote ~ female + black + age + income + educ3 +\n                          real_ideo + partyid7 + ideo_feel,\n               family = binomial(link = \"logit\"),\n               data = nes92, seed = 215, refresh = 0)\nsummary(m2, digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Info:\n function:     stan_glm\n family:       binomial [logit]\n formula:      presvote ~ female + black + age + income + educ3 + real_ideo + \n\t   partyid7 + ideo_feel\n algorithm:    sampling\n sample:       4000 (posterior sample size)\n priors:       see help('prior_summary')\n observations: 921\n predictors:   9\n\nEstimates:\n              mean    sd      10%     50%     90%  \n(Intercept)  -9.121   0.925 -10.344  -9.103  -7.945\nfemale        0.294   0.249  -0.022   0.293   0.617\nblack        -2.309   0.653  -3.161  -2.285  -1.508\nage          -0.002   0.007  -0.012  -0.002   0.007\nincome       -0.162   0.130  -0.328  -0.163   0.002\neduc3         0.013   0.085  -0.095   0.013   0.121\nreal_ideo     0.457   0.124   0.300   0.454   0.619\npartyid7      0.941   0.072   0.851   0.938   1.036\nideo_feel     0.071   0.014   0.054   0.071   0.089\n\nFit Diagnostics:\n           mean   sd    10%   50%   90%\nmean_PPD 0.437  0.012 0.421 0.436 0.453\n\nThe mean_ppd is the sample average posterior predictive distribution of the outcome variable (for details see help('summary.stanreg')).\n\nMCMC diagnostics\n              mcse  Rhat  n_eff\n(Intercept)   0.013 1.000 5340 \nfemale        0.004 1.000 4670 \nblack         0.011 0.999 3685 \nage           0.000 1.000 3898 \nincome        0.002 1.000 4144 \neduc3         0.001 1.001 4007 \nreal_ideo     0.002 1.000 3777 \npartyid7      0.001 0.999 4002 \nideo_feel     0.000 1.000 3875 \nmean_PPD      0.000 1.000 4616 \nlog-posterior 0.049 1.000 2013 \n\nFor each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 3: Model 2 plus an income x ideology interaction\nm3 <- stan_glm(presvote ~ female + black + age + income + educ3 +\n                          real_ideo + partyid7 + ideo_feel + income:real_ideo,\n               family = binomial(link = \"logit\"),\n               data = nes92, seed = 215, refresh = 0)\nsummary(m3, digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Info:\n function:     stan_glm\n family:       binomial [logit]\n formula:      presvote ~ female + black + age + income + educ3 + real_ideo + \n\t   partyid7 + ideo_feel + income:real_ideo\n algorithm:    sampling\n sample:       4000 (posterior sample size)\n priors:       see help('prior_summary')\n observations: 921\n predictors:   10\n\nEstimates:\n                   mean    sd      10%     50%     90%  \n(Intercept)       -9.048   1.583 -11.098  -8.999  -7.087\nfemale             0.291   0.250  -0.032   0.293   0.607\nblack             -2.306   0.655  -3.175  -2.281  -1.482\nage               -0.002   0.007  -0.011  -0.002   0.007\nincome            -0.197   0.415  -0.725  -0.203   0.351\neduc3              0.013   0.083  -0.092   0.014   0.118\nreal_ideo          0.437   0.310   0.042   0.435   0.833\npartyid7           0.938   0.075   0.843   0.936   1.035\nideo_feel          0.072   0.013   0.055   0.072   0.089\nincome:real_ideo   0.008   0.095  -0.116   0.009   0.132\n\nFit Diagnostics:\n           mean   sd    10%   50%   90%\nmean_PPD 0.437  0.012 0.421 0.436 0.453\n\nThe mean_ppd is the sample average posterior predictive distribution of the outcome variable (for details see help('summary.stanreg')).\n\nMCMC diagnostics\n                 mcse  Rhat  n_eff\n(Intercept)      0.031 1.000 2619 \nfemale           0.004 1.001 4219 \nblack            0.010 1.000 4030 \nage              0.000 1.000 4353 \nincome           0.009 1.000 2224 \neduc3            0.001 1.000 4161 \nreal_ideo        0.007 1.001 2240 \npartyid7         0.001 1.000 3466 \nideo_feel        0.000 1.000 5785 \nincome:real_ideo 0.002 1.001 2132 \nmean_PPD         0.000 0.999 4329 \nlog-posterior    0.052 1.001 1746 \n\nFor each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).\n```\n\n\n:::\n:::\n\n\n### 2.4 Checking the Fit\n\nBefore comparing models, we should check that the MCMC actually converged and that the model reproduces the data. The `summary` output reports $\\hat{R}$ (should be very close to 1) and effective sample sizes (want these in the hundreds or thousands). A posterior predictive check overlays simulated outcome counts on the observed counts:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(m2, plotfun = \"bars\", nreps = 50) +\n  ggtitle(\"Posterior predictive check: Model 2\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/ppcheck-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(m2, prob = 0.95) +\n  ggtitle(\"Model 2 coefficients with 95% intervals\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/coefplot-1.png){width=672}\n:::\n:::\n\n\nA coefficient whose interval clears zero is one the data can speak to with confidence; an interval straddling zero means we can't distinguish its effect from nothing.\n\n### 2.5 Comparing Models: AIC, BIC, and LOO\n\nHow do we decide which of the three models to keep? The classical tools are the information criteria. **AIC** and **BIC** both start from the maximized log-likelihood and subtract a penalty for the number of parameters; for both, *lower is better*. We can compute them from ordinary `glm` fits of the same three specifications:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Classical fits of the same three specifications, for AIC/BIC\ng1 <- glm(presvote ~ age + black + income + real_ideo + income:real_ideo,\n          family = binomial, data = nes92)\ng2 <- glm(presvote ~ female + black + age + income + educ3 +\n                     real_ideo + partyid7 + ideo_feel,\n          family = binomial, data = nes92)\ng3 <- glm(presvote ~ female + black + age + income + educ3 +\n                     real_ideo + partyid7 + ideo_feel + income:real_ideo,\n          family = binomial, data = nes92)\n\nic_table <- data.frame(\n  Model = c(\"Model 1\", \"Model 2\", \"Model 3\"),\n  AIC   = c(AIC(g1), AIC(g2), AIC(g3)),\n  BIC   = c(BIC(g1), BIC(g2), BIC(g3))\n)\nkable(ic_table, digits = 1,\n      caption = \"Classical information criteria (lower is better)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Classical information criteria (lower is better)\n\n|Model   |   AIC|   BIC|\n|:-------|-----:|-----:|\n|Model 1 | 843.4| 872.4|\n|Model 2 | 474.3| 517.7|\n|Model 3 | 476.3| 524.6|\n\n\n:::\n:::\n\n\nThe Bayesian counterpart is **leave-one-out cross-validation (LOO)**, which estimates how well each model would predict a held-out observation. The package reports `elpd_loo`, the expected log predictive density. *Higher is better* and `loo_compare` ranks the models and gives each difference together with its standard error.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloo1 <- loo(m1)\nloo2 <- loo(m2)\nloo3 <- loo(m3)\n\nloo_compare(loo1, loo2, loo3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   elpd_diff se_diff\nm2    0.0       0.0 \nm3   -0.8       0.2 \nm1 -184.6      17.0 \n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n## How to read a LOO comparison\n`loo_compare` puts the best model at the top with a difference of 0, and reports every other model as a (negative) `elpd_diff` relative to it, alongside `se_diff`. A difference that is large compared to its standard error (say, several times bigger) is real predictive evidence; a difference smaller than its own standard error is noise. So the rule of thumb is to look at `elpd_diff / se_diff`, not the raw gap.\n:::\n\n::: {.callout-note}\n## What is `elpd`, and why prefer it to AIC/BIC?\n\n$$\n\\text{elpd}_{loo}\n=\n\\sum_{i=1}^{n}\n\\log p(y_i \\mid y_{-i})\n$$\n\n$$\nAIC = -2\\log L + 2k\n$$\n\n$$\nBIC = -2\\log L + k\\log n\n$$\n\nwhere:\n\n- \\(L\\) = maximized likelihood\n- \\(k\\) = number of parameters\n- \\(n\\) = sample size\nAll three numbers are after the same thing --- *how well will this model predict new data?* --- but they get there differently.\n\nAIC and BIC start from the **maximized** log-likelihood (a single best-fit point) and then subtract a complexity penalty: AIC subtracts the number of parameters $k$, BIC subtracts $\\tfrac{1}{2}k\\log n$. That penalty is a stand-in for overfitting, derived under asymptotic assumptions, and it depends on *counting parameters*, which gets awkward the moment a model has priors, hierarchical structure, or partial pooling, where the effective number of parameters isn't even well defined.\n\n`elpd` (expected log predictive density) skips the asymptotics and estimates predictive accuracy more directly. Leave-one-out cross-validation asks, for each observation in turn, \"how probable is this point under the posterior fit to all the *other* points?\", then sums the logs of those probabilities. Three advantages follow:\n\n- It uses the **whole posterior**, not just its maximum, so it naturally accounts for parameter uncertainty and the regularizing pull of the prior, instead of penalizing a point estimate after the fact.\n- It needs **no parameter count**. Effective complexity falls out of the cross-validation itself, exactly what we want for Bayesian and hierarchical models.\n- It comes with an **standard error** (`se_diff`), so we can tell a real difference from noise. A raw AIC or BIC gap gives us no comparable measure of its own uncertainty.\n\nIn practice the three often agree, as they do for these 1992 models. When they disagree, it is usually because the model has priors or structure that break AIC/BIC's parameter-counting assumption --- and that is precisely when `elpd` is the one to trust.\n:::\n\n**Interpretation:**\nIn 1992, tall three model comparison criteria point to Model 2 as the best-performing model. It clearly improves predictive performance over the simpler classical specification, while the additional income*ideology interaction in Model 3 contributes little meaningful improvement.\n\nSubstantively, party identification and ideology emerge as the strongest predictors, with race also playing an important role. By contrast, most demographic variables, including income, add relatively little explanatory power once party ID and the ideology thermometer are included in the model. This finding becomes especially important in the next section, where the classical baseline initially suggested that income was influential. A Bayesian perspective helps reveal how dependent that conclusion is on the modeling assumptions.\n\n## 3. Encoding a Prior Belief: Income's Coefficient\n\nSuppose a colleague argues that, conditional on the other predictors, income shouldn't matter for vote choice at all, and that they're confident enough to pin the income coefficient near zero, give or take about one standard deviation. Now we need to give that one coefficient an informative prior centered at zero, and leave the rest weakly informative.\n\n$$\\beta_{\\text{income}} \\sim \\mathcal{N}(0,\\; \\text{SD}), \\qquad \\text{everything else} \\sim \\mathcal{N}(0,\\; 2.5)$$\n\nWe'll set the prior's scale equal to the data-only posterior SD of income (from Model 2), so the prior and the data carry comparable weight.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Posterior SD of income from the data-only fit (Model 2)\nsd_income <- sd(as.matrix(m2)[, \"income\"])\n\n# Coefficient order in m2: female, black, age, income, educ3, real_ideo, partyid7, ideo_feel\nprior_loc   <- rep(0, 8)\nprior_scale <- c(2.5, 2.5, 2.5, sd_income, 2.5, 2.5, 2.5, 2.5)\n\nm_inf <- stan_glm(presvote ~ female + black + age + income + educ3 +\n                            real_ideo + partyid7 + ideo_feel,\n                  family = binomial(link = \"logit\"),\n                  data = nes92,\n                  prior = normal(location = prior_loc, scale = prior_scale,\n                                 autoscale = FALSE),\n                  seed = 215, refresh = 0)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npost_m2  <- as.matrix(m2)[, \"income\"]\npost_inf <- as.matrix(m_inf)[, \"income\"]\n\ncmp_income <- data.frame(\n  Model   = c(\"Default (m2)\", \"Informative (m_inf)\"),\n  Median  = c(median(post_m2),  median(post_inf)),\n  SD      = c(sd(post_m2),      sd(post_inf)),\n  CI_2.5  = c(quantile(post_m2, 0.025), quantile(post_inf, 0.025)),\n  CI_97.5 = c(quantile(post_m2, 0.975), quantile(post_inf, 0.975))\n)\nkable(cmp_income, digits = 3, row.names = FALSE,\n      caption = \"Income coefficient: weakly-informative vs. informative prior\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Income coefficient: weakly-informative vs. informative prior\n\n|Model               | Median|    SD| CI_2.5| CI_97.5|\n|:-------------------|------:|-----:|------:|-------:|\n|Default (m2)        | -0.163| 0.130| -0.406|   0.102|\n|Informative (m_inf) | -0.083| 0.092| -0.262|   0.095|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninc_df <- data.frame(\n  value = c(post_m2, post_inf),\n  Model = rep(c(\"Default (m2)\", \"Informative (m_inf)\"), each = length(post_m2))\n)\n\nggplot(inc_df, aes(x = value, fill = Model)) +\n  geom_density(alpha = 0.5) +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"red\") +\n  labs(title = \"Posterior of the income coefficient\",\n       subtitle = \"weakly-informative vs. informative prior\",\n       x = \"Income coefficient (log-odds scale)\", y = \"Density\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/income-density-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-note}\n## Intuition: the posterior is a precision-weighted average\nWith a Normal prior and an approximately Normal likelihood, the posterior precision (one over the variance) is just the sum of the two precisions,\n\n$$\\tau_{\\text{post}} = \\tau_{\\text{prior}} + \\tau_{\\text{data}},$$\n\nand the posterior mean is the precision-weighted average of the prior mean and the data estimate,\n\n$$\\mu_{\\text{post}} = \\frac{\\tau_{\\text{prior}}\\cdot 0 + \\tau_{\\text{data}}\\cdot \\hat\\beta_{\\text{data}}}{\\tau_{\\text{prior}} + \\tau_{\\text{data}}}.$$\n\nThis is the same compromise we saw in Part 3 with the Beta-Binomial, just in Gaussian dress. When we set the prior SD equal to the data SD, the two precisions are equal, so the posterior mean lands roughly halfway between the prior's zero and the data estimate, and the posterior SD shrinks by a factor of about $1/\\sqrt{2}$. Adding a prior adds information, so the posterior tightens.\n:::\n\nThe verdict doesn't change. In both fits the credible interval for income comfortably contains zero, and every other coefficient is essentially untouched --- the informative prior acts locally, on the parameter it targets, and leaves the rest of the model alone. Here the prior and the data happen to agree (both say \"income is near zero\"), so the prior simply sharpens a conclusion the data were already pointing to rather than overturning anything. \n\n## 4. When the Likelihood Breaks: Separation in 1964\n\nSwitch to the 1964 election and try to predict the vote from gender, race, and income with an ordinary `glm`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnes64 <- Nes.red %>%\n  filter(year == 1964) %>%\n  select(presvote, female, black, income) %>%\n  na.omit()\n\nfit64_freq <- glm(presvote ~ female + black + income,\n                  family = binomial(link = \"logit\"), data = nes64)\nsummary(fit64_freq)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = presvote ~ female + black + income, family = binomial(link = \"logit\"), \n    data = nes64)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -1.15513    0.21592  -5.350 8.81e-08 ***\nfemale       -0.07918    0.13611  -0.582  0.56072    \nblack       -16.82942  420.51043  -0.040  0.96808    \nincome        0.19010    0.05839   3.256  0.00113 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1337.7  on 1061  degrees of freedom\nResidual deviance: 1254.0  on 1058  degrees of freedom\nAIC: 1262\n\nNumber of Fisher Scoring iterations: 16\n```\n\n\n:::\n:::\n\n\nThe coefficient on `black` comes back enormous and negative, with a standard error so large it's clearly meaningless. This isn't a bug --- it's **separation**. When a predictor perfectly (or nearly perfectly) predicts the outcome, the likelihood has no finite maximum: pushing the coefficient further out always makes the data look a little more probable, so the MLE marches off toward infinity and the standard error explodes with it.\n\nA quick cross-tabulation shows what happened:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_race <- table(black = nes64$black, presvote = nes64$presvote)\ntab_race\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     presvote\nblack   0   1\n    0 631 344\n    1  87   0\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nP(Republican | Black)     =\",\n    round(tab_race[\"1\", \"1\"] / sum(tab_race[\"1\", ]), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nP(Republican | Black)     = 0 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"P(Republican | non-Black) =\",\n    round(tab_race[\"0\", \"1\"] / sum(tab_race[\"0\", ]), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP(Republican | non-Black) = 0.3528 \n```\n\n\n:::\n:::\n\n\nIn this sample, every Black respondent voted Democratic. There's no value of the coefficient that \"best\" fits a probability of zero, the likelihood just keeps rewarding more extreme estimates.\n\nA weakly informative prior fixes this without any special-casing. By placing gentle probability mass near zero, the prior gives the posterior a finite mode even where the likelihood alone has none:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit64_bayes <- stan_glm(presvote ~ female + black + income,\n                        family = binomial(link = \"logit\"),\n                        data = nes64, seed = 215, refresh = 0)\nsummary(fit64_bayes, digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Info:\n function:     stan_glm\n family:       binomial [logit]\n formula:      presvote ~ female + black + income\n algorithm:    sampling\n sample:       4000 (posterior sample size)\n priors:       see help('prior_summary')\n observations: 1062\n predictors:   4\n\nEstimates:\n              mean    sd      10%     50%     90%  \n(Intercept)  -1.163   0.220  -1.442  -1.163  -0.886\nfemale       -0.080   0.138  -0.259  -0.080   0.096\nblack        -9.469   4.442 -15.832  -8.505  -4.705\nincome        0.192   0.060   0.117   0.192   0.270\n\nFit Diagnostics:\n           mean   sd    10%   50%   90%\nmean_PPD 0.324  0.019 0.299 0.324 0.349\n\nThe mean_ppd is the sample average posterior predictive distribution of the outcome variable (for details see help('summary.stanreg')).\n\nMCMC diagnostics\n              mcse  Rhat  n_eff\n(Intercept)   0.005 1.000 2182 \nfemale        0.003 1.000 2191 \nblack         0.152 1.000  855 \nincome        0.001 1.000 2075 \nmean_PPD      0.000 1.000 3771 \nlog-posterior 0.043 1.002 1164 \n\nFor each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclassical <- summary(fit64_freq)$coefficients[, c(\"Estimate\", \"Std. Error\")]\npost_64   <- as.matrix(fit64_bayes)\n\nbayes_summary <- t(apply(post_64[, rownames(classical)], 2, function(x) {\n  c(median = median(x), sd = sd(x),\n    lower = quantile(x, 0.025), upper = quantile(x, 0.975))\n}))\n\ncmp_64 <- data.frame(\n  Variable     = rownames(classical),\n  GLM_Estimate = classical[, \"Estimate\"],\n  GLM_SE       = classical[, \"Std. Error\"],\n  Bayes_Median = bayes_summary[, \"median\"],\n  Bayes_SD     = bayes_summary[, \"sd\"]\n)\nkable(cmp_64, digits = 3, row.names = FALSE,\n      col.names = c(\"Variable\", \"GLM est.\", \"GLM SE\", \"Bayes median\", \"Bayes SD\"),\n      caption = \"1964 NES: classical GLM vs. Bayesian fit\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 1964 NES: classical GLM vs. Bayesian fit\n\n|Variable    | GLM est.|  GLM SE| Bayes median| Bayes SD|\n|:-----------|--------:|-------:|------------:|--------:|\n|(Intercept) |   -1.155|   0.216|       -1.163|    0.220|\n|female      |   -0.079|   0.136|       -0.080|    0.138|\n|black       |  -16.829| 420.510|       -8.505|    4.442|\n|income      |    0.190|   0.058|        0.192|    0.060|\n\n\n:::\n:::\n\n\n::: {.callout-important}\n## The prior acts surgically\nNotice that the prior only does heavy lifting where the data can't. The `black` coefficient moves from -16.829 estimate to -8.505\t, while `female` and `income`, which the data identify well, barely change. This is an illustration of Bayesian regularization: the prior rescues the parameter the likelihood couldn't pin down, and stays out of the way everywhere else.\n:::\n\n\n## 5. Logit vs. Probit\n\nLogistic regression uses the logit link; probit regression uses the inverse Normal CDF instead. \n\nBoth models predict a binary outcome by passing a linear predictor $\\eta_i = \\mathbf{x}_i^\\top \\boldsymbol\\beta$ through a function that squashes it into a probability. They differ only in which squashing function they use. The **logit** link uses the logistic CDF,\n\n$$\\Pr(y_i = 1) = \\operatorname{logit}^{-1}(\\eta_i) = \\frac{e^{\\eta_i}}{1 + e^{\\eta_i}} = \\frac{1}{1 + e^{-\\eta_i}},$$\n\nwhile the **probit** link uses the standard Normal CDF $\\Phi(\\cdot)$,\n\n$$\\Pr(y_i = 1) = \\Phi(\\eta_i) = \\int_{-\\infty}^{\\eta_i} \\frac{1}{\\sqrt{2\\pi}} e^{-t^2/2}\\, dt.$$\n\nEquivalently, on the link scale,\n\n$$\\underbrace{\\log\\!\\frac{p_i}{1 - p_i} = \\eta_i}_{\\text{logit}}, \\qquad \\underbrace{\\Phi^{-1}(p_i) = \\eta_i}_{\\text{probit}}.$$\n\nPractitioners sometimes worry about which to pick. Let's refit our 1992 Model 2 with a probit link and compare.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2_probit <- stan_glm(presvote ~ female + black + age + income + educ3 +\n                                 real_ideo + partyid7 + ideo_feel,\n                      family = binomial(link = \"probit\"),\n                      data = nes92,\n                      QR = TRUE,       # orthogonalize the design matrix for stability\n                      init_r = 0.5,\n                      seed = 215, refresh = 0)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npost_logit  <- as.matrix(m2)\npost_probit <- as.matrix(m2_probit)\ncommon_pars <- intersect(colnames(post_logit), colnames(post_probit))\n\ncmp_links <- data.frame(\n  Variable = common_pars,\n  Logit    = apply(post_logit[,  common_pars], 2, median),\n  Probit   = apply(post_probit[, common_pars], 2, median),\n  Ratio    = apply(post_logit[,  common_pars], 2, median) /\n             apply(post_probit[, common_pars], 2, median)\n)\nkable(cmp_links, digits = 3, row.names = FALSE,\n      col.names = c(\"Variable\", \"Logit median\", \"Probit median\", \"Ratio\"),\n      caption = \"Posterior medians: logit vs. probit\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Posterior medians: logit vs. probit\n\n|Variable    | Logit median| Probit median|  Ratio|\n|:-----------|------------:|-------------:|------:|\n|(Intercept) |       -9.103|        -4.893|  1.860|\n|female      |        0.293|         0.171|  1.710|\n|black       |       -2.285|        -1.196|  1.910|\n|age         |       -0.002|        -0.001|  1.577|\n|income      |       -0.163|        -0.088|  1.847|\n|educ3       |        0.013|        -0.006| -2.279|\n|real_ideo   |        0.454|         0.253|  1.789|\n|partyid7    |        0.938|         0.535|  1.755|\n|ideo_feel   |        0.071|         0.037|  1.938|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_logit  <- colMeans(posterior_epred(m2))\np_probit <- colMeans(posterior_epred(m2_probit))\n\nggplot(data.frame(p_logit, p_probit), aes(p_logit, p_probit)) +\n  geom_abline(slope = 1, intercept = 0, linetype = 2, color = \"gray\") +\n  geom_point(alpha = 0.3, size = 0.8) +\n  labs(x = \"Pr(Republican) -- logit\", y = \"Pr(Republican) -- probit\",\n       title = \"Fitted probabilities: logit vs. probit\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/fitted-compare-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloo_compare(loo(m2), loo(m2_probit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          elpd_diff se_diff\nm2_probit  0.0       0.0   \nm2        -0.2       2.5   \n```\n\n\n:::\n:::\n\n\nThe two fits are the same model in different units. The ratio of logit to probit coefficients clusters around the theoretical constant $\\pi/\\sqrt{3} \\approx 1.81$ (the ratio of the logistic to the Normal scale), the fitted probabilities fall almost exactly on the 45-degree line, and LOO sees no predictive difference worth mentioning. The choice between logit and probit is mostly a matter of convention and interpretability, not fit.\n\n::: {.callout-note}\n## Where the $\\pi/\\sqrt{3}$ factor comes from\nBoth links arise from the same **latent-variable** story. Imagine an unobserved continuous \"propensity to vote Republican,\"\n\n$$y_i^{*} = \\mathbf{x}_i^\\top \\boldsymbol\\beta + \\varepsilon_i, \\qquad y_i = \\mathbf{1}(y_i^{*} > 0),$$\n\nso the vote is 1 whenever the propensity crosses zero. The only difference between the two models is the assumed distribution of the noise $\\varepsilon_i$:\n\n$$\\varepsilon_i \\sim \\text{Logistic}(0, 1) \\;\\Rightarrow\\; \\text{logit}, \\qquad \\varepsilon_i \\sim \\mathcal{N}(0, 1) \\;\\Rightarrow\\; \\text{probit}.$$\n\nThose two error distributions have different spreads. The standard logistic distribution has variance\n\n$$\\operatorname{Var}(\\varepsilon) = \\frac{\\pi^2}{3} \\approx 3.29 \\quad\\Longrightarrow\\quad \\text{SD} = \\frac{\\pi}{\\sqrt{3}} \\approx 1.81,$$\n\nwhereas the standard Normal has variance $1$. Because the coefficients are only identified up to the scale of the error term, the logit coefficients are inflated by exactly that ratio:\n\n$$\\boldsymbol\\beta_{\\text{logit}} \\;\\approx\\; \\frac{\\pi}{\\sqrt{3}}\\, \\boldsymbol\\beta_{\\text{probit}} \\;\\approx\\; 1.81\\,\\boldsymbol\\beta_{\\text{probit}}.$$\n\nSo the two models aren't really competing descriptions of the data --- they're the same fit measured in different units.\n:::\n\n## 6. Beyond Binary: Ordered Logit for Party ID\n\nVote choice was binary, but `partyid7` is an *ordered* seven-point scale from Strong Democrat to Strong Republican. We could lump it into two categories, but that throws away the ordering. The proportional-odds (ordered logit) model keeps it: it posits a latent \"Republican-ness\" score, and a set of increasing cutpoints that slice that score into the seven observed categories. We'll model it from demographics and ideology in the 2000 election.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnes00 <- Nes.red %>%\n  filter(year == 2000) %>%\n  select(partyid7, female, black, age, income, educ3, real_ideo) %>%\n  na.omit() %>%\n  mutate(partyid7 = factor(partyid7, ordered = TRUE, levels = 1:7,\n                           labels = c(\"StrDem\", \"WkDem\", \"LnDem\", \"Ind\",\n                                      \"LnRep\", \"WkRep\", \"StrRep\")))\ntable(nes00$partyid7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nStrDem  WkDem  LnDem    Ind  LnRep  WkRep StrRep \n    78     50     50     18     56     51     62 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_polr <- stan_polr(partyid7 ~ female + black + age + income + educ3 + real_ideo,\n                    data = nes00,\n                    prior = R2(location = 0.3, what = \"mean\"),\n                    seed = 215, refresh = 0)\nsummary(m_polr, digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Info:\n function:     stan_polr\n family:       ordered [logistic]\n formula:      partyid7 ~ female + black + age + income + educ3 + real_ideo\n algorithm:    sampling\n sample:       4000 (posterior sample size)\n priors:       see help('prior_summary')\n observations: 365\n\nEstimates:\n               mean   sd     10%    50%    90% \nfemale       -0.064  0.188 -0.305 -0.064  0.176\nblack        -0.941  0.386 -1.437 -0.941 -0.464\nage          -0.013  0.006 -0.020 -0.013 -0.005\nincome        0.204  0.096  0.080  0.205  0.326\neduc3         0.091  0.066  0.008  0.090  0.175\nreal_ideo     0.821  0.080  0.719  0.820  0.922\nStrDem|WkDem  2.183  0.647  1.358  2.160  3.023\nWkDem|LnDem   3.075  0.653  2.240  3.062  3.918\nLnDem|Ind     3.859  0.664  3.009  3.835  4.727\nInd|LnRep     4.151  0.669  3.297  4.135  5.028\nLnRep|WkRep   5.048  0.683  4.176  5.030  5.935\nWkRep|StrRep  6.036  0.703  5.152  6.025  6.966\n\nFit Diagnostics:\n                  mean   sd    10%   50%   90%\nmean_PPD:StrDem 0.209  0.026 0.175 0.208 0.241\nmean_PPD:WkDem  0.132  0.024 0.101 0.132 0.164\nmean_PPD:LnDem  0.138  0.025 0.107 0.137 0.170\nmean_PPD:Ind    0.054  0.017 0.033 0.052 0.074\nmean_PPD:LnRep  0.159  0.027 0.126 0.159 0.192\nmean_PPD:WkRep  0.141  0.025 0.110 0.140 0.173\nmean_PPD:StrRep 0.167  0.025 0.134 0.167 0.200\n\nThe mean_ppd is the sample average posterior predictive distribution of the outcome variable (for details see help('summary.stanreg')).\n\nMCMC diagnostics\n                mcse  Rhat  n_eff\nfemale          0.002 0.999 6244 \nblack           0.005 1.001 5602 \nage             0.000 1.001 5154 \nincome          0.001 1.000 5533 \neduc3           0.001 1.000 4587 \nreal_ideo       0.001 1.000 3183 \nStrDem|WkDem    0.009 1.000 4697 \nWkDem|LnDem     0.009 1.000 4865 \nLnDem|Ind       0.009 1.000 4985 \nInd|LnRep       0.009 1.000 4964 \nLnRep|WkRep     0.010 1.000 4896 \nWkRep|StrRep    0.010 1.000 4973 \nmean_PPD:StrDem 0.000 1.000 4436 \nmean_PPD:WkDem  0.000 0.999 3451 \nmean_PPD:LnDem  0.000 1.000 3624 \nmean_PPD:Ind    0.000 1.000 3928 \nmean_PPD:LnRep  0.000 1.000 4002 \nmean_PPD:WkRep  0.000 1.000 4136 \nmean_PPD:StrRep 0.000 1.000 3908 \nlog-posterior   0.098 1.004  947 \n\nFor each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npost_polr <- as.matrix(m_polr)\ncoef_pars <- c(\"female\", \"black\", \"age\", \"income\", \"educ3\", \"real_ideo\")\n\npolr_summary <- t(apply(post_polr[, coef_pars], 2, function(x) {\n  c(median = median(x), sd = sd(x),\n    lower = quantile(x, 0.025), upper = quantile(x, 0.975))\n}))\nkable(polr_summary, digits = 3,\n      col.names = c(\"Median\", \"SD\", \"2.5%\", \"97.5%\"),\n      caption = \"Ordered logit coefficients: 2000 NES partyid7\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Ordered logit coefficients: 2000 NES partyid7\n\n|          | Median|    SD|   2.5%|  97.5%|\n|:---------|------:|-----:|------:|------:|\n|female    | -0.064| 0.188| -0.435|  0.300|\n|black     | -0.941| 0.386| -1.721| -0.187|\n|age       | -0.013| 0.006| -0.025| -0.001|\n|income    |  0.205| 0.096|  0.018|  0.392|\n|educ3     |  0.090| 0.066| -0.042|  0.223|\n|real_ideo |  0.820| 0.080|  0.667|  0.979|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(m_polr) + ggtitle(\"Ordered logit coefficients with intervals\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/polr-plot-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-tip}\n## Reading proportional-odds coefficients\nIn an ordered logit, a positive coefficient means that raising the predictor shifts probability mass toward *higher* categories. Here, toward the Republican end. Each coefficient $\\beta$ says that a one-unit increase in the predictor multiplies the *cumulative odds* of being at or above any given category by $\\exp(\\beta)$, and the proportional-odds assumption is that this same multiplier applies at every cutpoint. So a coefficient of $0.8$ means roughly $e^{0.8} \\approx 2.2\\times$ the cumulative odds per one-point step --- and steps compound, so moving across the full range of a 7-point predictor multiplies the odds by $e^{6\\beta}$.\n:::\n\nThe cutpoints themselves are worth a look, since they tell us how the latent scale maps onto the observed categories:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncut_names <- grep(\"\\\\|\", colnames(post_polr), value = TRUE)\ncutpoint_summary <- t(apply(post_polr[, cut_names], 2, function(x) {\n  c(median = median(x), lower = quantile(x, 0.025), upper = quantile(x, 0.975))\n}))\nkable(cutpoint_summary, digits = 3,\n      col.names = c(\"Median\", \"2.5%\", \"97.5%\"),\n      caption = \"Cutpoints between adjacent partyid7 categories\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Cutpoints between adjacent partyid7 categories\n\n|                  | Median|  2.5%| 97.5%|\n|:-----------------|------:|-----:|-----:|\n|StrDem&#124;WkDem |  2.160| 0.947| 3.441|\n|WkDem&#124;LnDem  |  3.062| 1.800| 4.333|\n|LnDem&#124;Ind    |  3.835| 2.571| 5.159|\n|Ind&#124;LnRep    |  4.135| 2.845| 5.459|\n|LnRep&#124;WkRep  |  5.030| 3.745| 6.364|\n|WkRep&#124;StrRep |  6.025| 4.650| 7.414|\n\n\n:::\n:::\n\n\nThe cutpoints are strictly increasing, as a well-posed ordered model requires. Where two adjacent cutpoints sit unusually close together, it signals a thin category, a level the latent score passes through quickly, which is what we'd expect for \"Independent\" in a polarized electorate.\n\nFinally, the same posterior predictive check we used for the binary models works here, now across all seven categories:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(m_polr, plotfun = \"bars\", nreps = 50) +\n  ggtitle(\"Posterior predictive check: ordered logit (2000 partyid7)\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/polr-ppcheck-1.png){width=672}\n:::\n:::\n\n\nSubstantively, ideology and race are the dominant drivers of party identification, income adds a modest positive pull toward the Republican end, and gender and education carry little independent signal once the rest is controlled for.\n\n*This tutorial is based on UCLA [STATS C216: Applied Bayesian Social Statistics](https://handcock.github.io/teaching/c216/) taught by Prof [Mark Handcock](https://handcock.github.io/).*\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}