{
  "hash": "0e82cf9ffbc7c2147a9a3f7565d34ffb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Social Network Analysis R Tutorial Part 5:  Hands-On ERGM Analysis\"\nauthor: Shuhan (Alice) Ai\ndate: \"2025-10-31\"\ncategories: [R, SNA]\ntoc: true\ntoc-depth: 3\ntoc-title: \"Contents\"\nimage: \"plot1.png\"\n---\n\nWelcome to Part 5 of our Social Network Analysis tutorial! In this hands-on session, we'll work through three real-world examples of network modeling using ERGM. \n\n![](plot1.png)\nIn this tutorial, we'll cover:\n\n- Military cooperation networks: Testing random graph assumptions\n- Classroom friendships: Exploring homophily and mixing patterns\n- Individual differences: Using the $p_1$ model for centrality and prestige\n\nBy the end of this tutorial, you'll know how to fit, interpret, and visualize ERGM results. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list = ls())\n\nlibrary(sna)           # Social network analysis\nlibrary(network)       # Network objects\nlibrary(networkdata)   # Example datasets\nlibrary(ergm)          # Exponential random graph models\n```\n:::\n\n\n## Example 1: Testing the Simple Random Graph Model\n\n### 1.1 Background: Cold War Military Cooperation\n\nThe `coldwar` dataset contains information on military cooperation and conflict between countries from 1950 through 1985. We'll focus on cooperative relations (positive ties) in the first time period (1950-1954).\n\n**Research Question**: Does this military cooperation network follow a Simple Random Graph (SRG) model, or is there evidence of structure beyond random chance?\n\n### 1.2 Load and Prepare Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(coldwar)\n\n#examine the data structure\nattributes(coldwar)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$names\n[1] \"cc\"       \"distance\" \"gdp\"      \"polity\"  \n```\n\n\n:::\n\n```{.r .cell-code}\ndimnames(coldwar$cc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n [1] \"AFG\" \"ALB\" \"ARG\" \"AUL\" \"AUS\" \"BEL\" \"BRA\" \"BUL\" \"CAN\" \"CHL\" \"CHN\" \"COL\"\n[13] \"COS\" \"CUB\" \"CZE\" \"DEN\" \"DOM\" \"ECU\" \"EGY\" \"ETH\" \"FRN\" \"GDR\" \"GFR\" \"GRC\"\n[25] \"GUA\" \"HAI\" \"HON\" \"HUN\" \"IND\" \"INS\" \"IRE\" \"IRN\" \"IRQ\" \"ISR\" \"ITA\" \"JOR\"\n[37] \"LBR\" \"LEB\" \"MYA\" \"NEP\" \"NEW\" \"NIC\" \"NOR\" \"NTH\" \"OMA\" \"PAN\" \"PER\" \"PHI\"\n[49] \"POR\" \"PRK\" \"ROK\" \"RUM\" \"SAF\" \"SAL\" \"SAU\" \"SPN\" \"SRI\" \"SWD\" \"TAW\" \"THI\"\n[61] \"TUR\" \"UKG\" \"USA\" \"USR\" \"VEN\" \"YUG\"\n\n[[2]]\n [1] \"AFG\" \"ALB\" \"ARG\" \"AUL\" \"AUS\" \"BEL\" \"BRA\" \"BUL\" \"CAN\" \"CHL\" \"CHN\" \"COL\"\n[13] \"COS\" \"CUB\" \"CZE\" \"DEN\" \"DOM\" \"ECU\" \"EGY\" \"ETH\" \"FRN\" \"GDR\" \"GFR\" \"GRC\"\n[25] \"GUA\" \"HAI\" \"HON\" \"HUN\" \"IND\" \"INS\" \"IRE\" \"IRN\" \"IRQ\" \"ISR\" \"ITA\" \"JOR\"\n[37] \"LBR\" \"LEB\" \"MYA\" \"NEP\" \"NEW\" \"NIC\" \"NOR\" \"NTH\" \"OMA\" \"PAN\" \"PER\" \"PHI\"\n[49] \"POR\" \"PRK\" \"ROK\" \"RUM\" \"SAF\" \"SAL\" \"SAU\" \"SPN\" \"SRI\" \"SWD\" \"TAW\" \"THI\"\n[61] \"TUR\" \"UKG\" \"USA\" \"USR\" \"VEN\" \"YUG\"\n\n[[3]]\n[1] \"1950\" \"1955\" \"1960\" \"1965\" \"1970\" \"1975\" \"1980\" \"1985\"\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(coldwar$cc)  # 66 x 66 matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 66 66  8\n```\n\n\n:::\n:::\n\n\nThe dataset is a 66 × 66 matrix representing 66 countries. Let's focus on cooperative ties (setting negative values to zero):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#create network object with only positive (cooperative) ties\ncc_net <- network(ifelse(coldwar$cc[,,1] > 0, coldwar$cc[,,1], 0), \n                  directed = FALSE)\n\n#check network attributes\nattributes(cc_net)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$names\n[1] \"mel\" \"gal\" \"val\" \"iel\" \"oel\"\n\n$class\n[1] \"network\"\n```\n\n\n:::\n:::\n\n\n### 1.3 Fit the Simple Random Graph Model\n\nUnder the SRG (Erdős-Rényi) model, all ties are equally likely and independent. We fit this model using only the `edges` term:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#fit SRG model\nsrg_modelfit <- ergm(cc_net ~ edges)\nsummary(srg_modelfit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nergm(formula = cc_net ~ edges)\n\nMaximum Likelihood Results:\n\n      Estimate Std. Error MCMC % z value Pr(>|z|)    \nedges  -4.0991     0.1704      0  -24.05   <1e-04 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n     Null Deviance: 2973.6  on 2145  degrees of freedom\n Residual Deviance:  357.5  on 2144  degrees of freedom\n \nAIC: 359.5  BIC: 365.2  (Smaller is better. MC Std. Err. = 0)\n```\n\n\n:::\n:::\n\n\n#### Interpreting the Results\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#extract the edges coefficient\ntheta_edge <- coef(srg_modelfit)[\"edges\"]\ncat(\"Log-odds of a tie:\", round(theta_edge, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLog-odds of a tie: -4.099 \n```\n\n\n:::\n\n```{.r .cell-code}\n#convert to probability\nprob_tie <- plogis(theta_edge)\ncat(\"Probability of a tie:\", round(prob_tie, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProbability of a tie: 0.0163 \n```\n\n\n:::\n\n```{.r .cell-code}\n#compare to observed density\nob_density <- network.density(cc_net)\ncat(\"Observed network density:\", round(ob_density, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved network density: 0.0163 \n```\n\n\n:::\n:::\n\n\n**Key Findings**:\n\n- The coefficient is **-4.02** (log-odds)\n- This translates to a tie probability of **0.0176** (about 1.76%)\n- The network is very sparse - only 1.76% of possible ties exist\n- The MLE probability exactly matches the observed density\n\n### 1.4 Testing Against the SRG Model\n\nNow we'll test if the observed network structure is consistent with an SRG model by examining **degree centralization**.\n\n#### Computing Observed Degree Centralization\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculate observed degree centralization\nob_degree_cc <- sna::centralization(cc_net, sna::degree, mode = \"graph\")\ncat(\"Observed degree centralization:\", round(ob_degree_cc, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved degree centralization: 0.0942 \n```\n\n\n:::\n:::\n\n\n#### Simulating Under the SRG Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#define degree centralization function for undirected networks\ncd_undirected <- function(net) {\n  return(sna::centralization(net, sna::degree, mode = 'graph'))\n}\n\n#simulate 1000 networks under the SRG model\nset.seed(123)\nsimulation <- simulate(srg_modelfit, nsim = 1000)\n\n#calculate degree centralization for each simulated network\ndeg_sim <- sapply(simulation, cd_undirected)\n\n#compare to observed\ncat(\"Mean simulated centralization:\", round(mean(deg_sim), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean simulated centralization: 0.0471 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Proportion >= observed:\", mean(deg_sim >= ob_degree_cc), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProportion >= observed: 0.001 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Proportion < observed:\", mean(deg_sim < ob_degree_cc), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProportion < observed: 0.999 \n```\n\n\n:::\n:::\n\n\n#### Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#create histogram\nhist(deg_sim, breaks = 30, \n     main = \"Distribution of Degree Centralization Under SRG Model\",\n     xlab = \"Degree Centralization\",\n     col = \"lightblue\",\n     border = \"white\")\nabline(v = ob_degree_cc, col = \"red\", lwd = 2, lty = 2)\ntext(ob_degree_cc, max(hist(deg_sim, plot = FALSE)$counts) * 0.9,\n     labels = \"Observed\", pos = 4, col = \"red\", font = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=768}\n:::\n:::\n\n\n#### Formal Test: Conditional Uniform Graph (CUG)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#CUG test\nset.seed(123)\ncug_result <- cug.test(cc_net, \n                       FUN = cd_undirected, \n                       mode = \"graph\", \n                       cmode = \"edges\",  # Condition on number of edges\n                       reps = 1000)\nprint(cug_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nUnivariate Conditional Uniform Graph Test\n\nConditioning Method: edges \nGraph Type: graph \nDiagonal Used: FALSE \nReplications: 1000 \n\nObserved Value: 0.09423077 \nPr(X>=Obs): 0.002 \nPr(X<=Obs): 1 \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(cug_result)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n#### Interpretation\n\n**Results Summary**:\n\n- Only **0.1%** (1 out of 1000) simulated networks had centralization ≥ 0.094\n- p-value ≈ 0.001 (highly significant)\n- The observed centralization (0.094) is far in the tail of the distribution\n- Random networks cluster around 0.04-0.05\n\n**Conclusion**: \n\n- We **reject** the hypothesis that this network follows an SRG model  \n- The network shows significantly more centralization than expected by chance  \n- This suggests underlying structure - perhaps a few countries are much more central than others\n\n\n## Example 2: Exploring Homophily in Classroom Friendships\n\n### 2.1 Background: The Hansell Dataset\n\nThis dataset contains friendship ties among 27 students (13 boys, 14 girls) in a sixth-grade classroom. Students rated if they liked each other \"a lot\", \"some\", or \"not much\" - we consider a strong friendship if someone liked another \"a lot.\"\n\n**Research Question**: Do students show a preference for same-sex friendships (homophily)?\n\n### 2.2 Load and Visualize Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"hansell\")\n\n#extract sex attribute\nsex_attr <- hansell %v% \"sex\"\ntable(sex_attr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsex_attr\nfemale   male \n    14     13 \n```\n\n\n:::\n\n```{.r .cell-code}\n#create colors for visualization\nvertex_colors <- ifelse(sex_attr == \"male\", \"lightblue\", \"lightpink\")\n```\n:::\n\n\nLet's visualize the network:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(627)\nplot(hansell,\n     vertex.col = vertex_colors,\n     main = \"Hansell Classroom Friendship Network\",\n     vertex.cex = 2,\n     label = 1:network.size(hansell),\n     label.cex = 0.8)\n\nlegend(\"topright\",\n       legend = c(\"Male\", \"Female\"),\n       col = c(\"lightblue\", \"lightpink\"),\n       pch = 19,\n       pt.cex = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n**Visual Assessment**: \n\n- Clear clustering by sex\n- Dense connections within each sex group\n- Very few cross-sex ties\n- Suggests strong homophily\n\n\n### 2.3 Model 1: Erdős-Rényi Baseline\n\nLet's start with the simplest model - no homophily, just overall density:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#check basic statistics\nsummary(hansell ~ density + edges + mutual)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    density       edges      mutual \n  0.2236467 157.0000000  24.0000000 \n```\n\n\n:::\n\n```{.r .cell-code}\n#fit Erdős-Rényi model\nfit.er <- ergm(hansell ~ edges)\nsummary(fit.er)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nergm(formula = hansell ~ edges)\n\nMaximum Likelihood Results:\n\n      Estimate Std. Error MCMC % z value Pr(>|z|)    \nedges -1.24454    0.09058      0  -13.74   <1e-04 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n     Null Deviance: 973.2  on 702  degrees of freedom\n Residual Deviance: 746.2  on 701  degrees of freedom\n \nAIC: 748.2  BIC: 752.8  (Smaller is better. MC Std. Err. = 0)\n```\n\n\n:::\n:::\n\n\n#### Interpretation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#log-odds of a tie\ntheta_edge <- coef(fit.er)[\"edges\"]\ncat(\"Log-odds:\", round(theta_edge, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLog-odds: -1.245 \n```\n\n\n:::\n\n```{.r .cell-code}\n#probability\nprob_tie <- plogis(theta_edge)\ncat(\"Probability:\", round(prob_tie, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProbability: 0.224 \n```\n\n\n:::\n\n```{.r .cell-code}\n#compare to observed density\nob_density <- network.density(hansell)\ncat(\"Observed density:\", round(ob_density, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved density: 0.224 \n```\n\n\n:::\n\n```{.r .cell-code}\n#model comparison\ncat(\"\\nDeviance reduction from null model:\", \n    round(fit.er$null.deviance - fit.er$deviance, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nDeviance reduction from null model:  \n```\n\n\n:::\n:::\n\n\n**Key Findings**:\n\n- Log-odds = -1.245\n- Tie probability = 0.224 (22.4%)\n- Matches observed density exactly (as expected for ER model)\n- Reduces deviance by 227 from null model\n\n### 2.4 Model 2: Homophily Model\n\nNow let's test if same-sex ties are more likely:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit.homo <- ergm(hansell ~ edges + nodematch(\"sex\"))\nsummary(fit.homo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nergm(formula = hansell ~ edges + nodematch(\"sex\"))\n\nMaximum Likelihood Results:\n\n              Estimate Std. Error MCMC % z value Pr(>|z|)    \nedges          -1.9841     0.1608      0 -12.341   <1e-04 ***\nnodematch.sex   1.2954     0.1979      0   6.547   <1e-04 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n     Null Deviance: 973.2  on 702  degrees of freedom\n Residual Deviance: 699.1  on 700  degrees of freedom\n \nAIC: 703.1  BIC: 712.2  (Smaller is better. MC Std. Err. = 0)\n```\n\n\n:::\n:::\n\n\n#### Interpretation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#extract coefficients\nbeta_edges <- coef(fit.homo)[\"edges\"]\nbeta_match <- coef(fit.homo)[\"nodematch.sex\"]\n\ncat(\"Edges coefficient:\", round(beta_edges, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEdges coefficient: -1.984 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Nodematch coefficient:\", round(beta_match, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNodematch coefficient: 1.295 \n```\n\n\n:::\n\n```{.r .cell-code}\n#probability for same-sex ties\nlog_odds_same <- beta_edges + beta_match\nprob_same <- plogis(log_odds_same)\ncat(\"\\nP(tie | same sex):\", round(prob_same, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nP(tie | same sex): 0.334 \n```\n\n\n:::\n\n```{.r .cell-code}\n#probability for different-sex ties\nprob_diff <- plogis(beta_edges)\ncat(\"P(tie | different sex):\", round(prob_diff, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP(tie | different sex): 0.121 \n```\n\n\n:::\n\n```{.r .cell-code}\n#odds ratio\nOR <- exp(beta_match)\ncat(\"\\nOdds Ratio:\", round(OR, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nOdds Ratio: 3.65 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Interpretation: Same-sex ties are\", round(OR, 1), \n    \"times more likely than different-sex ties\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInterpretation: Same-sex ties are 3.7 times more likely than different-sex ties\n```\n\n\n:::\n:::\n\n\n**Key Findings**:\n\n- *Significant homophily** (p < 0.001)  \n- Same-sex tie probability: **0.785**  \n- Different-sex tie probability: **0.334**  \n- Odds ratio = **3.65**: Same-sex friendships are 3.65× more likely!  \n- Deviance reduced by 274 from null model\n\n### 2.5 Model 3: Differential Homophily\n\nDo boys and girls show different levels of homophily?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#fit differential homophily model\nfit.diff.homo <- ergm(hansell ~ edges + nodematch(\"sex\", diff = TRUE))\nsummary(fit.diff.homo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nergm(formula = hansell ~ edges + nodematch(\"sex\", diff = TRUE))\n\nMaximum Likelihood Results:\n\n                     Estimate Std. Error MCMC % z value Pr(>|z|)    \nedges                 -1.9841     0.1608      0 -12.341   <1e-04 ***\nnodematch.sex.female   1.4674     0.2221      0   6.607   <1e-04 ***\nnodematch.sex.male     1.0813     0.2389      0   4.526   <1e-04 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n     Null Deviance: 973.2  on 702  degrees of freedom\n Residual Deviance: 696.4  on 699  degrees of freedom\n \nAIC: 702.4  BIC: 716  (Smaller is better. MC Std. Err. = 0)\n```\n\n\n:::\n:::\n\n\n#### Interpretation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#extract coefficients\ncoefs <- coef(fit.diff.homo)\ncat(\"Edges:\", round(coefs[\"edges\"], 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEdges: -1.984 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Male homophily:\", round(coefs[\"nodematch.sex.male\"], 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMale homophily: 1.081 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Female homophily:\", round(coefs[\"nodematch.sex.female\"], 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFemale homophily: 1.467 \n```\n\n\n:::\n\n```{.r .cell-code}\n#calculate probabilities\nprob_mm <- plogis(coefs[\"edges\"] + coefs[\"nodematch.sex.male\"])\nprob_ff <- plogis(coefs[\"edges\"] + coefs[\"nodematch.sex.female\"])\nprob_mf <- plogis(coefs[\"edges\"])\n\ncat(\"\\nProbabilities:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nProbabilities:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Male-Male:\", round(prob_mm, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMale-Male: 0.288 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Female-Female:\", round(prob_ff, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFemale-Female: 0.374 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Cross-sex:\", round(prob_mf, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCross-sex: 0.121 \n```\n\n\n:::\n:::\n\n\n**Key Finding**: \n\n- Both sexes show homophily, but coefficients are similar\n- Not a significant improvement over simple homophily model\n- Suggests homophily effect is approximately equal for both sexes\n\n### 2.6 Model 4: Full Mixing Model\n\nLet's estimate separate probabilities for all four tie types:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#fit mixing model\nfit.mix <- ergm(hansell ~ edges + nodemix(\"sex\"))\nsummary(fit.mix)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nergm(formula = hansell ~ edges + nodemix(\"sex\"))\n\nMaximum Likelihood Results:\n\n                    Estimate Std. Error MCMC % z value Pr(>|z|)    \nedges                -0.5167     0.1532      0  -3.372 0.000746 ***\nmix.sex.male.female  -1.3207     0.2643      0  -4.997  < 1e-04 ***\nmix.sex.female.male  -1.6326     0.2868      0  -5.693  < 1e-04 ***\nmix.sex.male.male    -0.3862     0.2339      0  -1.651 0.098731 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n     Null Deviance: 973.2  on 702  degrees of freedom\n Residual Deviance: 695.5  on 698  degrees of freedom\n \nAIC: 703.5  BIC: 721.7  (Smaller is better. MC Std. Err. = 0)\n```\n\n\n:::\n:::\n\n\n#### Interpretation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#extract all mixing coefficients\ncoefs <- coef(fit.mix)\n\ncoefs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              edges mix.sex.male.female mix.sex.female.male   mix.sex.male.male \n         -0.5166907          -1.3206792          -1.6326205          -0.3861770 \n```\n\n\n:::\n\n```{.r .cell-code}\n#calculate probabilities for all dyad types\nprob_FF <- plogis(coefs[\"edges\"])\nprob_FM <- plogis(coefs[\"edges\"] + coefs[\"mix.sex.female.male\"])\nprob_MF <- plogis(coefs[\"edges\"] + coefs[\"mix.sex.male.female\"])\nprob_MM <- plogis(coefs[\"edges\"] + coefs[\"mix.sex.male.male\"])\n\ncat(\"Tie Probabilities:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTie Probabilities:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"From Female to Female:\", round(prob_FF, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrom Female to Female: 0.374 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"From Female to Male:\", round(prob_FM, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrom Female to Male: 0.104 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"From Male to Female:\", round(prob_MF, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrom Male to Female: 0.137 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"From Male to Male:\", round(prob_MM, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrom Male to Male: 0.288 \n```\n\n\n:::\n\n```{.r .cell-code}\n#calculate log-odds for specific tie types\ncat(\"\\nLog-odds:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLog-odds:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"From Male to Female:\", round(coefs[\"edges\"] + coefs[\"mix.sex.male.female\"], 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrom Male to Female: -1.837 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"From Female to Male:\", round(coefs[\"edges\"] + coefs[\"mix.sex.female.male\"], 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrom Female to Male: -2.149 \n```\n\n\n:::\n:::\n\n\n#### Comparing to Empirical Frequencies\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#step 1: Get empirical mixing matrix\nemp_mix <- mixingmatrix(hansell, \"sex\")\nprint(emp_mix)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        To\nFrom     female male Sum\n  female     68   19  87\n  male       25   45  70\n  Sum        93   64 157\n```\n\n\n:::\n\n```{.r .cell-code}\n#step 2: Calculate empirical probabilities\n#number of nodes by sex\nn_female <- sum(hansell %v% \"sex\" == \"female\")  # 14\nn_male <- sum(hansell %v% \"sex\" == \"male\")      # 13\n\n#observed counts from mixing matrix\nobs_FF <- emp_mix$matrix[\"female\", \"female\"]\nobs_FM <- emp_mix$matrix[\"female\", \"male\"]\nobs_MF <- emp_mix$matrix[\"male\", \"female\"]\nobs_MM <- emp_mix$matrix[\"male\", \"male\"]\n\n#possible ties\npossible_FF <- n_female * (n_female - 1)  # 14 × 13 = 182\npossible_FM <- n_female * n_male          # 14 × 13 = 182\npossible_MF <- n_male * n_female          # 13 × 14 = 182\npossible_MM <- n_male * (n_male - 1)      # 13 × 12 = 156\n\n#empirical probabilities\nemp_prob_FF <- obs_FF / possible_FF\nemp_prob_FM <- obs_FM / possible_FM\nemp_prob_MF <- obs_MF / possible_MF\nemp_prob_MM <- obs_MM / possible_MM\n\n#model-predicted probabilities\ncoefs <- coef(fit.mix)\nmodel_prob_FF <- plogis(coefs[\"edges\"])\nmodel_prob_FM <- plogis(coefs[\"edges\"] + coefs[\"mix.sex.female.male\"])\nmodel_prob_MF <- plogis(coefs[\"edges\"] + coefs[\"mix.sex.male.female\"])\nmodel_prob_MM <- plogis(coefs[\"edges\"] + coefs[\"mix.sex.male.male\"])\n\n#create comparison table\ncomparison <- data.frame(\n  Tie_Type = c(\"From Female to Female\", \"From Female to Male\", \"From Male to Female\", \"From Male to Male\"),\n  Observed = c(obs_FF, obs_FM, obs_MF, obs_MM),\n  Possible = c(possible_FF, possible_FM, possible_MF, possible_MM),\n  Empirical_Prob = round(c(emp_prob_FF, emp_prob_FM, emp_prob_MF, emp_prob_MM), 4),\n  Model_Prob = round(c(model_prob_FF, model_prob_FM, model_prob_MF, model_prob_MM), 4),\n  Difference = round(abs(c(emp_prob_FF - model_prob_FF,\n                           emp_prob_FM - model_prob_FM,\n                           emp_prob_MF - model_prob_MF,\n                           emp_prob_MM - model_prob_MM)), 6)\n)\n\nprint(comparison)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Tie_Type Observed Possible Empirical_Prob Model_Prob Difference\n1 From Female to Female       68      182         0.3736     0.3736          0\n2   From Female to Male       19      182         0.1044     0.1044          0\n3   From Male to Female       25      182         0.1374     0.1374          0\n4     From Male to Male       45      156         0.2885     0.2885          0\n```\n\n\n:::\n:::\n\n\n**Key Finding**: The mixing model perfectly matches the empirical probabilities! This is because it has enough parameters to exactly reproduce the observed mixing matrix.\n\n### 2.7 Model Comparison\n\nLet's formally compare all models:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(fit.er, fit.homo, fit.diff.homo, fit.mix)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: hansell ~ edges\nModel 2: hansell ~ edges + nodematch(\"sex\")\nModel 3: hansell ~ edges + nodematch(\"sex\", diff = TRUE)\nModel 4: hansell ~ edges + nodemix(\"sex\")\n     Df Deviance Resid. Df Resid. Dev Pr(>|Chisq|)    \nNULL                   702     973.18                 \n1     1  226.974       701     746.20    < 2.2e-16 ***\n2     1   47.067       700     699.14    6.861e-12 ***\n3     1    2.752       699     696.39      0.09711 .  \n4     1    0.933       698     695.45      0.33402    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n#### Interpretation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#create summary table\nmodel_summary <- data.frame(\n  Model = c(\"Erdős-Rényi\", \"Homophily\", \"Diff. Homophily\", \"Full Mixing\"),\n  Df = c(1, 2, 3, 4),\n  Deviance = round(c(deviance(fit.er), \n                     deviance(fit.homo),\n                     deviance(fit.diff.homo), \n                     deviance(fit.mix)), 2),\n  AIC = round(c(AIC(fit.er), AIC(fit.homo), AIC(fit.diff.homo), AIC(fit.mix)), 2)\n)\n\nprint(model_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Model Df Deviance    AIC\n1     Erdős-Rényi  1   746.20 748.20\n2       Homophily  2   699.14 703.14\n3 Diff. Homophily  3   696.39 702.39\n4     Full Mixing  4   695.45 703.45\n```\n\n\n:::\n:::\n\n\n**Model Selection**:\n\n- **Homophily model** provides the best balance:\n  - Significantly better than ER baseline (p < 0.001)\n  - More parsimonious than full mixing\n  - Captures the key phenomenon (sex-based homophily)\n  \n- **Differential homophily** doesn't improve significantly (p = 0.098)\n  \n- **Full mixing** fits perfectly but uses 4 parameters vs 2 for homophily\n\n**Recommended**: Use the **homophily model** (`edges + nodematch(\"sex\")`)\n\n\n\n## Example 3: The $p_1$ Model - Individual Differences\n\n### 3.1 Motivation\n\nThe homophily model assumes all students have equal propensity to form ties. But in reality:\n\n- Some students are more **active** in forming friendships (high centrality)\n- Some students are more **popular** (high prestige)\n- Some friendships are **mutual**\n\nThe **p₁ model** accounts for these individual differences!\n\n### 3.2 Fitting the $p_1$  Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#fit p1 model with homophily and reciprocity\nfit.p1 <- ergm(hansell ~ edges + nodematch(\"sex\") + \n               sender + receiver + mutual,\n               estimate = \"MPLE\")  # Use MPLE for faster fitting\nsummary(fit.p1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nergm(formula = hansell ~ edges + nodematch(\"sex\") + sender + \n    receiver + mutual, estimate = \"MPLE\")\n\nMaximum Pseudolikelihood Results:\n\n              Estimate Std. Error MCMC % z value Pr(>|z|)    \nedges         -2.11855    0.78238      0  -2.708  0.00677 ** \nnodematch.sex  1.84281    0.27230      0   6.767  < 1e-04 ***\nsender2       -1.54793    0.93109      0  -1.663  0.09641 .  \nsender3        0.31127    0.70771      0   0.440  0.66006    \nsender4        1.36598    0.68467      0   1.995  0.04603 *  \nsender5        1.49910    0.68305      0   2.195  0.02818 *  \nsender6        0.90061    0.67518      0   1.334  0.18224    \nsender7       -0.51598    0.77064      0  -0.670  0.50314    \nsender8        0.32059    0.70128      0   0.457  0.64757    \nsender9       -1.00340    0.82700      0  -1.213  0.22502    \nsender10          -Inf    0.00000      0    -Inf  < 1e-04 ***\nsender11      -2.05418    1.15421      0  -1.780  0.07512 .  \nsender12      -0.86572    0.82546      0  -1.049  0.29428    \nsender13      -1.47680    0.92002      0  -1.605  0.10845    \nsender14      -0.06642    0.78915      0  -0.084  0.93292    \nsender15      -0.87582    0.82010      0  -1.068  0.28554    \nsender16       3.40801    0.77702      0   4.386  < 1e-04 ***\nsender17      -2.87639    1.19710      0  -2.403  0.01627 *  \nsender18      -2.33790    1.00485      0  -2.327  0.01999 *  \nsender19       1.24062    0.74032      0   1.676  0.09378 .  \nsender20       1.28398    0.73333      0   1.751  0.07997 .  \nsender21      -0.83177    0.82910      0  -1.003  0.31576    \nsender22       0.29150    0.76767      0   0.380  0.70416    \nsender23      -0.01974    0.77048      0  -0.026  0.97957    \nsender24      -1.57924    0.88064      0  -1.793  0.07293 .  \nsender25       0.15595    0.78162      0   0.200  0.84186    \nsender26          -Inf    0.00000      0    -Inf  < 1e-04 ***\nsender27          -Inf    0.00000      0    -Inf  < 1e-04 ***\nreceiver2     -0.28347    0.79423      0  -0.357  0.72116    \nreceiver3     -1.46021    0.88258      0  -1.654  0.09803 .  \nreceiver4     -1.76873    0.91830      0  -1.926  0.05409 .  \nreceiver5     -0.10010    0.75894      0  -0.132  0.89507    \nreceiver6     -0.01126    0.77376      0  -0.015  0.98839    \nreceiver7     -1.59659    0.91266      0  -1.749  0.08023 .  \nreceiver8     -2.22351    1.00494      0  -2.213  0.02693 *  \nreceiver9     -0.33343    0.79901      0  -0.417  0.67646    \nreceiver10     0.07091    0.77588      0   0.091  0.92718    \nreceiver11    -0.91872    0.84415      0  -1.088  0.27644    \nreceiver12    -1.48617    0.89730      0  -1.656  0.09767 .  \nreceiver13    -0.21295    0.79212      0  -0.269  0.78806    \nreceiver14     0.53666    0.77569      0   0.692  0.48903    \nreceiver15     1.45698    0.77945      0   1.869  0.06159 .  \nreceiver16    -0.94514    0.82799      0  -1.141  0.25367    \nreceiver17     1.23003    0.76186      0   1.615  0.10642    \nreceiver18     0.93454    0.77274      0   1.209  0.22651    \nreceiver19    -1.71723    0.95484      0  -1.798  0.07211 .  \nreceiver20        -Inf    0.00000      0    -Inf  < 1e-04 ***\nreceiver21     0.96520    0.78186      0   1.234  0.21702    \nreceiver22    -0.39792    0.82157      0  -0.484  0.62815    \nreceiver23    -0.74203    0.84421      0  -0.879  0.37942    \nreceiver24     0.62428    0.78201      0   0.798  0.42469    \nreceiver25     0.83051    0.77273      0   1.075  0.28248    \nreceiver26    -3.09795    1.33102      0  -2.328  0.01994 *  \nreceiver27    -2.05760    1.06110      0  -1.939  0.05249 .  \nmutual         0.90316    0.35698      0   2.530  0.01141 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nWarning:  The standard errors are based on naive pseudolikelihood and are suspect. Set control.ergm$MPLE.covariance.method='Godambe' for a simulation-based approximation of the standard errors.\n\n     Null Pseudo-deviance: 973.2  on 702  degrees of freedom\n Residual Pseudo-deviance: 451.8  on 647  degrees of freedom\n \nAIC: 553.8  BIC: 778.1  (Smaller is better. MC Std. Err. = 0)\n\n Warning: The following terms have infinite coefficient estimates:\n  sender10 sender26 sender27 receiver20 \n```\n\n\n:::\n:::\n\n\n#### Interpretation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#extract key coefficients\ncoefs <- coef(fit.p1)\n\ncat(\"Baseline (edges):\", round(coefs[\"edges\"], 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBaseline (edges): -2.119 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Homophily effect:\", round(coefs[\"nodematch.sex\"], 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHomophily effect: 1.843 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Reciprocity effect:\", round(coefs[\"mutual\"], 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReciprocity effect: 0.903 \n```\n\n\n:::\n\n```{.r .cell-code}\n#interpret effects\ncat(\"\\n--- Interpretations ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Interpretations ---\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Homophily OR:\", round(exp(coefs[\"nodematch.sex\"]), 2), \n    \"- Same-sex ties are\", round(exp(coefs[\"nodematch.sex\"]), 1), \n    \"times more likely\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHomophily OR: 6.31 - Same-sex ties are 6.3 times more likely\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Reciprocity OR:\", round(exp(coefs[\"mutual\"]), 2),\n    \"- Reciprocated ties are\", round(exp(coefs[\"mutual\"]), 1),\n    \"times more likely\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReciprocity OR: 2.47 - Reciprocated ties are 2.5 times more likely\n```\n\n\n:::\n:::\n\n\n**Key Findings**:\n\n- **Homophily remains significant** even after controlling for individual effects  \n- **Reciprocity is significant** (p = 0.011): Mutual friendships are 2.5× more likely  \n- Individual sender and receiver effects vary substantially across students\n\n### 3.3 Analyzing Individual Effects\n\n#### Extract Sender and Receiver Coefficients\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#extract all coefficients\ncoefs <- coef(fit.p1)\n\n#sender effects (first node is reference = 0)\nsender_coefs <- coefs[grep(\"^sender\", names(coefs))]\nsender_coefs <- c(0, sender_coefs)\n\n#receiver effects (first node is reference = 0)\nreceiver_coefs <- coefs[grep(\"^receiver\", names(coefs))]\nreceiver_coefs <- c(0, receiver_coefs)\n\n#summary statistics\ncat(\"Sender effects:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSender effects:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Range:\", range(sender_coefs[is.finite(sender_coefs)]), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Range: -2.876386 3.408013 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  SD:\", round(sd(sender_coefs[is.finite(sender_coefs)]), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SD: 1.435 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nReceiver effects:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nReceiver effects:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Range:\", range(receiver_coefs[is.finite(receiver_coefs)]), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Range: -3.097952 1.456984 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  SD:\", round(sd(receiver_coefs[is.finite(receiver_coefs)]), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SD: 1.184 \n```\n\n\n:::\n:::\n\n\n#### Visualize Centrality vs Prestige\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#create scatter plot\nplot(receiver_coefs, sender_coefs,\n     xlab = \"Prestige (Receiver Effects)\",\n     ylab = \"Centrality (Sender Effects)\",\n     main = \"Individual Differences in p₁ Model\\nCentrality vs Prestige\",\n     pch = 19, col = \"steelblue\", cex = 1.5)\n\n#add labels\ntext(receiver_coefs, sender_coefs, \n     labels = 1:27, pos = 3, cex = 0.8, col = \"darkred\")\n\n#add reference lines\nabline(h = 0, v = 0, lty = 2, col = \"gray50\")\n\n#identify top students\ntop_prestige <- order(receiver_coefs, decreasing = TRUE)[1:2]\ntop_centrality <- order(sender_coefs, decreasing = TRUE)[1:2]\n\n#highlight top students\npoints(receiver_coefs[top_prestige], sender_coefs[top_prestige], \n       col = \"red\", pch = 19, cex = 3)\npoints(receiver_coefs[top_centrality], sender_coefs[top_centrality], \n       col = \"green\", pch = 19, cex = 3)\n\n#add legend\nlegend(\"topleft\",\n       legend = c(\"Top Prestige\", \"Top Centrality\"),\n       col = c(\"red\", \"green\"),\n       pch = 19,\n       pt.cex = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-26-1.png){width=768}\n:::\n\n```{.r .cell-code}\n#print top students\ncat(\"\\nTop 2 in Prestige (most liked):\", top_prestige, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTop 2 in Prestige (most liked): 15 17 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Top 2 in Centrality (like most others):\", top_centrality, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTop 2 in Centrality (like most others): 16 5 \n```\n\n\n:::\n:::\n\n\n### 3.4 Correlation with Degree Centrality\n\nHow well do p₁ effects capture traditional degree centrality measures?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculate degree centrality\nindeg <- degree(hansell, cmode = \"indegree\")\noutdeg <- degree(hansell, cmode = \"outdegree\")\n\n#filter out infinite/extreme values for correlation\nfinite_indices <- which(is.finite(sender_coefs) & \n                        sender_coefs > -5 & \n                        is.finite(receiver_coefs) & \n                        receiver_coefs > -5)\n\n#calculate correlations\ncor_prestige <- cor(receiver_coefs[finite_indices], indeg[finite_indices])\ncor_centrality <- cor(sender_coefs[finite_indices], outdeg[finite_indices])\n\ncat(\"Correlation between:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCorrelation between:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Receiver effects & In-degree:\", round(cor_prestige, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Receiver effects & In-degree: 0.9896 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Sender effects & Out-degree:\", round(cor_centrality, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sender effects & Out-degree: 0.9694 \n```\n\n\n:::\n:::\n\n\n#### Visualize Correlations\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\n\n# Receiver vs In-Degree\nplot(indeg, receiver_coefs,\n     xlab = \"In-Degree\",\n     ylab = \"Receiver Effect (Prestige)\",\n     main = paste0(\"Prestige Correlation\\nr = \", round(cor_prestige, 3)),\n     pch = 19, col = \"dodgerblue\", cex = 1.5)\ntext(indeg, receiver_coefs, labels = 1:27, pos = 4, cex = 0.7)\nabline(lm(receiver_coefs[finite_indices] ~ indeg[finite_indices]), \n       col = \"red\", lwd = 2, lty = 2)\n\n# Sender vs Out-Degree\nplot(outdeg, sender_coefs,\n     xlab = \"Out-Degree\",\n     ylab = \"Sender Effect (Centrality)\",\n     main = paste0(\"Centrality Correlation\\nr = \", round(cor_centrality, 3)),\n     pch = 19, col = \"coral\", cex = 1.5)\ntext(outdeg, sender_coefs, labels = 1:27, pos = 4, cex = 0.7)\nabline(lm(sender_coefs[finite_indices] ~ outdeg[finite_indices]), \n       col = \"red\", lwd = 2, lty = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-28-1.png){width=1152}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n**Key Finding**: The p₁ model's sender and receiver effects are **highly correlated** with traditional degree centrality measures (r > 0.96)!\n\n### 3.5 Magnitude of Effects\n\nHow do individual differences compare to structural effects?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#filter finite values\nfinite_sender <- sender_coefs[is.finite(sender_coefs)]\nfinite_receiver <- receiver_coefs[is.finite(receiver_coefs)]\n\n#summary\ncat(\"Individual Effects:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIndividual Effects:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Sender effects range:\", range(finite_sender), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sender effects range: -2.876386 3.408013 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Receiver effects range:\", range(finite_receiver), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Receiver effects range: -3.097952 1.456984 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Sender SD:\", round(sd(finite_sender), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sender SD: 1.435 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Receiver SD:\", round(sd(finite_receiver), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Receiver SD: 1.184 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nStructural Effects:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nStructural Effects:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Homophily:\", round(coefs[\"nodematch.sex\"], 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Homophily: 1.843 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Reciprocity:\", round(coefs[\"mutual\"], 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Reciprocity: 0.903 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nInterpretation:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nInterpretation:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Individual effects have substantial variation (SD ≈ 1.1-1.4)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Individual effects have substantial variation (SD ≈ 1.1-1.4)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Homophily effect (1.84) is larger than 1 SD\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Homophily effect (1.84) is larger than 1 SD\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Extreme individuals can override typical homophily patterns\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Extreme individuals can override typical homophily patterns\n```\n\n\n:::\n:::\n\n\n#### Visualization of Effect Magnitudes\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#create density plots\npar(mfrow = c(1, 2))\n\n#sender effects\nplot(density(finite_sender), \n     main = \"Distribution of Individual Effects\",\n     xlab = \"Effect Size\",\n     xlim = c(-3, 4),\n     lwd = 2, col = \"coral\")\nlines(density(finite_receiver), lwd = 2, col = \"dodgerblue\")\n\n#add structural effects\nabline(v = coefs[\"nodematch.sex\"], col = \"darkgreen\", lwd = 2, lty = 2)\nabline(v = coefs[\"mutual\"], col = \"purple\", lwd = 2, lty = 2)\n\nlegend(\"topright\",\n       legend = c(\"Sender\", \"Receiver\", \"Homophily\", \"Reciprocity\"),\n       col = c(\"coral\", \"dodgerblue\", \"darkgreen\", \"purple\"),\n       lwd = 2,\n       lty = c(1, 1, 2, 2))\n\n#boxplot comparison\nboxplot(list(Sender = finite_sender,\n             Receiver = finite_receiver),\n        main = \"Individual Effect Variation\",\n        ylab = \"Effect Size\",\n        col = c(\"coral\", \"dodgerblue\"),\n        horizontal = FALSE)\nabline(h = coefs[\"nodematch.sex\"], col = \"darkgreen\", lwd = 2, lty = 2)\nabline(h = coefs[\"mutual\"], col = \"purple\", lwd = 2, lty = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-30-1.png){width=960}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n### 3.6 Key Insights\n\n**Comparing Individual vs Structural Effects**:\n\n1. **Homophily (1.84)** is the strongest effect\n   - More important than typical individual variation\n   - Structural force that shapes friendships\n\n2. **Individual variation is substantial**\n   - Sender effects: -2.88 to +3.41\n   - Receiver effects: -3.10 to +1.46\n   - Some students deviate strongly from the average\n\n3. **Extreme individuals override structure**\n   - Most sociable/popular students transcend homophily\n   - Isolated students (with -Inf effects) form no ties regardless\n\n4. **Reciprocity (0.90)** is moderate but significant\n   - Mutual friendships are 2.5× more likely\n   - But less important than homophily\n\n**Conclusion**: Both structural forces (homophily, reciprocity) and individual attributes (sender/receiver propensities) jointly shape friendship formation. Neither completely dominates the other.\n\n## Summary and Key Takeaways\n\n### What We've Learned\n\n#### 1. Testing Random Graph Assumptions\n\n- Use **CUG tests** to evaluate if networks follow random graph models  \n- Compare **observed statistics** to **simulated distributions**  \n- Significant deviations indicate underlying structure\n\n#### 2. Modeling Homophily\n\n- Start with **Erdős-Rényi baseline** (edges only)  \n- Add **nodematch** to test for same-group preferences  \n- Use **anova()** to compare models statistically  \n- Consider **differential homophily** if groups differ  \n- **Full mixing models** are flexible but parameter-heavy\n\n#### 3. Individual Heterogeneity (p₁ Models)\n\n- **Sender effects**: Capture node-level activity (centrality)  \n- **Receiver effects**: Capture popularity (prestige)  \n- **Mutual term**: Models reciprocity  \n- Highly correlated with traditional degree measures (r > 0.96)  \n- Accounts for individual variation beyond structural effects\n\n### Practical Workflow\n\n#### Step 1: Visualize\n```r\nplot(network)\n```\n\n#### Step 2: Start Simple\n```r\nfit.er <- ergm(network ~ edges)\n```\n\n#### Step 3: Add Substantive Terms\n```r\nfit.homo <- ergm(network ~ edges + nodematch(\"group\"))\nfit.p1 <- ergm(network ~ edges + nodematch(\"group\") + sender + receiver + mutual)\n```\n\n#### Step 4: Compare Models\n```r\nanova(fit.er, fit.homo, fit.p1)\n```\n\n#### Step 5: Interpret Effects\n```r\n# Coefficients → Probabilities\nplogis(coef(fit))\n\n# Odds Ratios\nexp(coef(fit))\n```\n\n#### Step 6: Check Fit\n```r\ngof(fit.homo)\nmcmc.diagnostics(fit.homo)\n```\n\n### Common Patterns\n\n| Finding | Interpretation |\n|---------|----------------|\n| Positive **nodematch** | Homophily present |\n| Positive **mutual** | Reciprocity tendency |\n| Large **sender** variance | Heterogeneous activity levels |\n| Large **receiver** variance | Popularity differences |\n| High degree correlation | p₁ effects capture centrality well |\n\n### When to Use Each Model\n\n| Model | Use When | Example |\n|-------|----------|---------|\n| **Erdős-Rényi** | Testing baseline/null hypothesis | Is network more structured than random? |\n| **Homophily** | Groups present, testing same-group preference | Do students befriend same-sex peers? |\n| **Differential Homophily** | Homophily may vary by group | Do boys vs girls show different homophily? |\n| **Full Mixing** | Need exact group-pair probabilities | What's the exact M→F friendship rate? |\n| **$p_1$ Model** | Individual differences important | Who are the most central/popular nodes? |\n\n### R Documentation\n\n- [ergm package](https://cran.r-project.org/package=ergm)\n- [statnet tutorials](https://statnet.org/)\n- [ERGM terms](https://zalmquist.github.io/ERGM_Lab/ergm-terms.html)\n\n\n\n---\n\n\n*This tutorial is based on UCLA [STATS 218: Social Network Analysis](https://handcock.github.io/teaching/218/) taught by Prof [Mark Handcock](https://handcock.github.io/).*\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}