{
  "hash": "dc424b584121b6b6c5864f0e9f94e225",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Social Network Analysis R Tutorial Part 7: dvanced ERGM Modeling with Structural Terms, and MCMC Diagnostics\"\nauthor: Shuhan (Alice) Ai\ndate: \"2025-11-17\"\ncategories: [R, SNA]\ntoc: true\ntoc-depth: 3\ncode-fold: show\ncode-tools: true\ntoc-title: \"Contents\"\nimage: \"figure1.png\"\n---\n\nWelcome to Part 7 of our Social Network Analysis R Tutorial series! In our [previous tutorial (Part 6)](https://aliceaii.github.io/posts/snapart6/), we explored the theoretical foundations of ERGMs, understanding the mathematical framework behind these powerful models. We covered the exponential family form, sufficient statistics, and the challenges of model degeneracy.\n\nIn this post, we will advance into **sophisticated ERGM modeling** by incorporating complex structural terms that capture network dependencies beyond simple dyadic relationships. We'll explore geometrically weighted statistics, perform comprehensive MCMC diagnostics, and learn to interpret results in meaningful sociological contexts.\n\n![](figure1.png)\n\nAfter completing this tutorial, you will be able to:\n\n- Implement advanced structural terms in ERGM models (GWESP, GWDSP, triadic structures)\n- Perform and interpret MCMC convergence diagnostics\n- Compare nested models and assess model fit\n- Interpret complex ERGM results in substantive terms\n- Handle model degeneracy using tapered ERGMs\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list = ls())\n\nlibrary(network)        # Network object manipulation\nlibrary(ergm)           # ERGM fitting\nlibrary(networkdata)    # Network datasets\nlibrary(sna)           # Social network analysis tools\nlibrary(ergm.tapered)  # Tapered ERGM for handling degeneracy\n\n# Install ergm.tapered if needed\n# devtools::install_github(\"statnet/ergm\", ref=\"tapered\")\n```\n:::\n\n\n::: callout-note\n**Why ergm.tapered?**\n\nThe `ergm.tapered` package provides an alternative estimation method that better handles models with strong dependence between terms. When you include multiple structural terms (like gwesp and gwdsp), standard ERGM estimation can struggle with convergence. Tapered ERGM adds a \"tapering\" mechanism that helps stabilize estimation.\n\nSoftware available on GitHub as ergm.tapered: https://github.com/statnet/ergm.tapered\n:::\n\n## 1. Introduction for Advanced Structural Terms in ERGMs\n\n### 1.1 Understanding Geometrically Weighted Statistics\n\nBefore diving into applications, let's understand the sophisticated structural terms available in ERGMs. These terms capture complex network dependencies while avoiding the degeneracy issues that plague simpler specifications.\n\n::: {.callout-note}\n**Why Geometrically Weighted Terms?**\nTraditional count statistics (like triangle counts) can lead to model degeneracy because they treat all configurations equally. Geometrically weighted terms apply **diminishing returns** - the first few shared partners matter more than additional ones, making the model more stable and interpretable.\n:::\n\n### 1.2 Comprehensive Function Reference Table\n\nHere's a detailed reference table for advanced ERGM structural terms:\n\n| Function | Syntax | Description | Interpretation | When to Use |\n|----------|---------|-------------|----------------|-------------|\n| **istar(k)** | `istar(2)` | k-in-stars: counts nodes with exactly k incoming edges | Popularity effects in directed networks | Testing for preferential attachment to popular nodes |\n| **ostar(k)** | `ostar(2)` | k-out-stars: counts nodes with exactly k outgoing edges | Activity effects in directed networks | Testing for variation in node activity levels |\n| **gwodegree(decay)** | `gwodegree(0.5, fixed=TRUE)` | Geometrically weighted out-degree distribution | Controls out-degree heterogeneity with diminishing returns | Modeling sender activity patterns without degeneracy |\n| **gwidegree(decay)** | `gwidegree(0.5, fixed=TRUE)` | Geometrically weighted in-degree distribution | Controls in-degree heterogeneity with diminishing returns | Modeling popularity/receiver effects without degeneracy |\n| **gwesp(decay)** | `gwesp(0.5, fixed=TRUE)` | Geometrically weighted edgewise shared partners | Transitivity: \"friend of friend is friend\" with diminishing returns | Capturing clustering while avoiding degeneracy |\n| **gwdsp(decay)** | `gwdsp(0.5, fixed=TRUE)` | Geometrically weighted dyadwise shared partners | Shared partners between any dyad (connected or not) | Modeling local clustering and \"small world\" effects |\n| **ctriple** | `ctriple` or `ctriad` | Cyclic triples: A→B→C→A patterns | Non-hierarchical, cyclic relationships | Testing for cyclic vs hierarchical structures |\n| **ttriple** | `ttriple` or `ttriad` | Transitive triples: A→B→C with A→C | Hierarchical, transitive closure | Testing for transitivity and balance theory |\n\n::: {.callout-tip}\nChoosing Decay Parameters\nThe decay parameter (α) in geometrically weighted terms controls how quickly the weight diminishes:\n\n- **α = 0**: Only the first shared partner matters\n- **α = 0.5**: Moderate decay (common choice)\n- **α = 1.0**: Slower decay, more weight on higher numbers\n- **α → ∞**: Approaches regular count statistics\n\nStart with α = 0.5 as a default and adjust based on model diagnostics.\n:::\n\n\n## 2. Case Study 1 - The French Financial Elite Network\n\n### 2.1 The French Financial Elite Network Basic Information\n\nWe'll work with a network collected by Charles Kadushin (1995) of 28 members of the French financial elite. This network captures friendship ties and includes rich vertex attributes that allow us to explore multiple dimensions of homophily.\n\n**Data Source:**\n\nKadushin, C. 1995. Friendship among the French financial elite. *American Sociological Review* 60:202-221.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(ffef)\nhelp(ffef)\nnetwork.size(ffef)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 28\n```\n\n\n:::\n\n```{.r .cell-code}\nnetwork.edgecount(ffef)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 66\n```\n\n\n:::\n\n```{.r .cell-code}\ngden(ffef)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1746032\n```\n\n\n:::\n\n```{.r .cell-code}\nlist.vertex.attributes(ffef)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"birthdate\"    \"birthplace\"   \"cabinet\"      \"clubs\"        \"eliteprom\"   \n [6] \"elitevote\"    \"ena\"          \"enayear\"      \"fathers-lev\"  \"finance-min\" \n[11] \"igyear\"       \"inspec-gen\"   \"masons\"       \"na\"           \"normal-sch\"  \n[16] \"party\"        \"polytech\"     \"polyyear\"     \"prestige\"     \"religion\"    \n[21] \"sciencepoly\"  \"socialreg\"    \"topboards\"    \"university\"   \"vertex.names\"\n[26] \"zipcode\"     \n```\n\n\n:::\n:::\n\n\nThe network includes several important vertex covariates:\n\n-   **prestige**: 0 (neither particule nor social register), 1 (either), or 2 (both)\n-   **party**: Political party membership (11 parties)\n-   **ena**: Graduated from ENA (École nationale d'administration)? 1=yes, 2=no\n-   **masons**: Mason membership\n-   **religion**: Religious affiliation\n-   **topboards**: Number of top corporate boards\n\n\n::: {.cell}\n\n```{.r .cell-code}\nena_status <- ffef %v% \"ena\"\nvertex_colors <- ifelse(ena_status == 1, \"coral\", \"skyblue\")\n\nplot(ffef, vertex.col = vertex_colors, \n     main = \"French Financial Elite Network Colored by ENA Status\", \n     vertex.cex = 1.5, edge.col = \"gray70\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n**Observations:**\n\n1.  **Visible clustering by ENA attendance**: Individuals who graduated from ENA tend to form connections with other ENA graduates, suggesting strong educational homophily\n2.  **Centrality patterns**: ENA graduates appear more concentrated in the network core, while non-ENA graduates are more dispersed around the periphery\n3.  **Cross-group ties exist**: While there's clear same-status clustering, we also observe connections between ENA and non-ENA graduates\n\n### 2.2 Building a Sophisticated ERGM Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#using ergm.tapered() for better handling of strong dependencies\nfit_elite <- ergm.tapered(\n  ffef ~ \n    edges +                           # Baseline density\n    nodematch(\"ena\") +               # ENA homophily\n    nodematch(\"prestige\") +          # Prestige homophily\n    nodematch(\"party\") +             # Political party homophily\n    gwesp(0.5, fixed = TRUE) +       # Transitive closure (clustering)\n    gwdsp(0.5, fixed = TRUE),        # Shared partners\n  verbose = FALSE\n)\n\nsummary(fit_elite)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Results:\n\n                   Estimate Std. Error MCMC % z value Pr(>|z|)    \nedges              -4.68593    0.51223      0  -9.148  < 1e-04 ***\nnodematch.ena       1.56649    0.36041      0   4.346  < 1e-04 ***\nnodematch.prestige  0.70744    0.28252      0   2.504 0.012279 *  \nnodematch.party     1.22757    0.37359      0   3.286 0.001017 ** \ngwesp.fixed.0.5     0.45725    0.18018      0   2.538 0.011159 *  \ngwdsp.fixed.0.5     0.18363    0.05446      1   3.372 0.000747 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nThe estimated tapering scaling factor is 2.\n\n     Null Deviance: 524  on 378  degrees of freedom\n Residual Deviance: 302  on 372  degrees of freedom\n \nAIC: 314  BIC: 337.6  (Smaller is better. MC Std. Err. = 0)\n```\n\n\n:::\n:::\n\n\n\n### 2.3 Interpreting Model Coefficients\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef_table <- data.frame(\n  Term = names(coef(fit_elite)),\n  Coefficient = round(coef(fit_elite), 3),\n  SE = round(summary(fit_elite)$coefficients[, \"Std. Error\"], 3),\n  OR = round(exp(coef(fit_elite)), 3),\n  p_value = round(summary(fit_elite)$coefficients[, \"Pr(>|z|)\"], 4)\n)\n\nprint(coef_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                 Term Coefficient    SE    OR p_value\nedges                           edges      -4.686 0.512 0.009  0.0000\nnodematch.ena           nodematch.ena       1.566 0.360 4.790  0.0000\nnodematch.prestige nodematch.prestige       0.707 0.283 2.029  0.0123\nnodematch.party       nodematch.party       1.228 0.374 3.413  0.0010\ngwesp.fixed.0.5       gwesp.fixed.0.5       0.457 0.180 1.580  0.0112\ngwdsp.fixed.0.5       gwdsp.fixed.0.5       0.184 0.054 1.202  0.0007\n```\n\n\n:::\n\n```{.r .cell-code}\nbaseline_prob <- plogis(coef(fit_elite)[\"edges\"])\nena_match_prob <- plogis(coef(fit_elite)[\"edges\"] + coef(fit_elite)[\"nodematch.ena\"])\nprestige_match_prob <- plogis(coef(fit_elite)[\"edges\"] + coef(fit_elite)[\"nodematch.prestige\"])\nparty_match_prob <- plogis(coef(fit_elite)[\"edges\"] + coef(fit_elite)[\"nodematch.party\"])\n\ncat(\"Baseline (no matches):\", round(baseline_prob, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBaseline (no matches): 0.0091 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Same ENA status:\", round(ena_match_prob, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSame ENA status: 0.0423 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Same prestige level:\", round(prestige_match_prob, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSame prestige level: 0.0184 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Same party affiliation:\", round(party_match_prob, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSame party affiliation: 0.0305 \n```\n\n\n:::\n:::\n\n\n-   **Edges:** $\\beta = -4.63$ represent the baseline log-odds of a friendship tie existing between any two randomly selected individuals in the networks, while controlling other predictors. The strong negative coefficient indicates this is a very sparse network. The $OR = 0.010$ means the baseline odds of a tie is about 1.0%. The baseline robability of friendship is approximately 0.96%.\n\n-   **nodematch.ena:** $\\beta = 1.57$ measures homophily on ENA attendance. The $OR = 4.79$ means that two individuals who share ENA status (both graduate from ENA or both did not) have 4.79 times higher odds of being friends compared to two individuals with different ENA status. The coefficient is strong and highly significant. And the probability of a friendship tie between two individuals who share the same ENA status is 4.45%.\n\n-   **nodematch.prestige:** $\\beta = 0.68$ measures homophily on prestige level (having particule and/or social register listing).The coefficient is moderate and significant (p = 0.015). The $OR = 1.97$ mean that two individuals with the same prestige level have 1.97 times higher odds of being friends compared to those with different prestige levels. The probability of a friendship tie between two individuals who share the same prestige level is 1.88%.\n\n-   **nodematch.party:** $\\beta = 1.25$ measures homophily on political party affiliation. The coefficient is strong and highly significant (p \\< 0.001).The $OR = 3.49$ means that two individuals from the same political party have 3.49 times higher odds of being friends compared to those from different parties. The probability of a friendship tie between two individuals who share the same party affiliation is 3.28%.\n\n-   **GWESP(0.5):** $\\beta = 0.43$ measures transitivity and clustering through Geometrically Weighted Edgewise Shared Partners. This term captures the \"friend of a friend is a friend\" phenomenon. The coefficient is moderate and significant (p = 0.013). The $OR = 1.53$ indicates that networks with more shared partners (triangles) are more probable. The French financial elite network exhibits strong transitivity. If person A is friends with person B, and person B is friends with person C, then A and C are significantly more likely to also be friends.\n\n-   **GWDSP(0.5):** $\\beta = 0.19$ measures local network structure through Geometrically Weighted Dyadwise Shared Partners. This term captures the tendency for dyads (pairs) to share partners, even if they're not directly connected. The coefficient is modest but significant (p = 0.003). The $OR = 1.21$ indicates preference for configurations where individuals share common friends. Beyond direct transitivity, there's a tendency for individuals to be embedded in overlapping social circles. This creates a \"small world\" structure where even if two people aren't direct friends, they're likely to share mutual acquaintances.\n\n::: callout-note\n```         \nplogis(coef[\"edges\"] + coef[\"gwesp.fixed.0.5\"])\n```\n\n**This does NOT work because:**\n\n-   GWESP is not a 0/1 indicator variable\n-   GWESP is a **count statistic** that depends on the entire network structure\n-   GWESP uses a **geometrically weighted** function: $\\sum_{k=1}^{n-2} \\{1 - (1-e^{-\\alpha})^k\\} \\cdot EP_k$\n\nSummary:\n\n| Term Type | Example Terms | Can use `plogis(edges + term)`? | Why/Why not? |\n|------------------|------------------|------------------|------------------|\n| **Node attributes** | `nodematch()`, `nodecov()`, `absdiff()` | YES | Binary 0/1 or known numeric covariate values |\n| **Dyad attributes** | `edgecov()`, `dyadcov()` | YES (with care) | Known covariate value for specific dyad |\n| **Structural terms** | `gwesp()`, `gwdsp()`, `triangle`, `ttriad`, `ctriad` | NO | Value depends on entire network configuration |\n| **Degree terms** | `gwdegree()`, `degree()`, `idegree()`, `odegree()` | NO | Depends on node's position in network |\n:::\n\n### 2.4 MCMC Diagnostics - Ensuring Model Reliability\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_diag <- mcmc.diagnostics(fit_elite, vars.per.page = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample statistics summary:\n\nIterations = 9984:197120\nThinning interval = 256 \nNumber of chains = 1 \nSample size per chain = 732 \n\n1. Empirical mean and standard deviation for each variable,\n   plus standard error of the mean:\n\n                       Mean     SD Naive SE Time-series SE\nedges              -0.37842  3.722  0.13758         0.1644\nnodematch.ena      -0.25000  3.973  0.14684         0.1748\nnodematch.prestige -0.29235  3.273  0.12098         0.1831\nnodematch.party    -0.02322  2.174  0.08035         0.1291\ngwesp.fixed.0.5    -0.19374  6.637  0.24532         0.2453\ngwdsp.fixed.0.5     2.50133 18.332  0.67756         0.7931\n\n2. Quantiles for each variable:\n\n                      2.5%     25%     50%    75%  97.5%\nedges               -7.725  -3.000  0.0000  2.000  6.725\nnodematch.ena       -8.000  -3.000  0.0000  3.000  8.000\nnodematch.prestige  -6.000  -2.250  0.0000  2.000  6.000\nnodematch.party     -4.000  -2.000  0.0000  1.000  4.000\ngwesp.fixed.0.5    -11.875  -4.982 -0.3306  4.575 12.947\ngwdsp.fixed.0.5    -30.923 -10.000  1.9447 14.795 38.260\n\n\nAre sample statistics significantly different from observed?\n                edges nodematch.ena nodematch.prestige nodematch.party\ndiff.      -0.3784153    -0.2500000         -0.2923497     -0.02322404\ntest stat. -2.3020120    -1.4300338         -1.5964703     -0.17995146\nP-val.      0.0213345     0.1527073          0.1103838      0.85719067\n           gwesp.fixed.0.5 gwdsp.fixed.0.5 Overall (Chi^2)\ndiff.           -0.1937426     2.501327124              NA\ntest stat.      -0.7897416     3.153789509    20.667899611\nP-val.           0.4296787     0.001611653     0.002732234\n\nSample statistics cross-correlations:\n                       edges nodematch.ena nodematch.prestige nodematch.party\nedges              1.0000000    0.70831695         0.38636757      0.17473251\nnodematch.ena      0.7083169    1.00000000         0.20351520      0.08771288\nnodematch.prestige 0.3863676    0.20351520         1.00000000      0.02346102\nnodematch.party    0.1747325    0.08771288         0.02346102      1.00000000\ngwesp.fixed.0.5    0.6485533    0.53125096         0.16732228      0.08451040\ngwdsp.fixed.0.5    0.5912691    0.25880435         0.19755469      0.09857144\n                   gwesp.fixed.0.5 gwdsp.fixed.0.5\nedges                    0.6485533      0.59126909\nnodematch.ena            0.5312510      0.25880435\nnodematch.prestige       0.1673223      0.19755469\nnodematch.party          0.0845104      0.09857144\ngwesp.fixed.0.5          1.0000000      0.54387391\ngwdsp.fixed.0.5          0.5438739      1.00000000\n\nSample statistics auto-correlation:\nChain 1 \n               edges nodematch.ena nodematch.prestige nodematch.party\nLag 0     1.00000000   1.000000000         1.00000000       1.0000000\nLag 256   0.17549198   0.172024313         0.28672574       0.4407665\nLag 512   0.07861936   0.044085462         0.11872718       0.2268692\nLag 768   0.04693548   0.007762898         0.11514094       0.1602980\nLag 1024 -0.02103196  -0.051723764         0.04807089       0.1281802\nLag 1280 -0.02029358  -0.099292509        -0.01649838       0.1258441\n         gwesp.fixed.0.5 gwdsp.fixed.0.5\nLag 0        1.000000000      1.00000000\nLag 256      0.014344672      0.04082106\nLag 512      0.018225222      0.05753242\nLag 768      0.007010241      0.06270653\nLag 1024    -0.038911261     -0.00166690\nLag 1280    -0.058851029      0.02978338\n\nSample statistics burn-in diagnostic (Geweke):\nChain 1 \n\nFraction in 1st window = 0.1\nFraction in 2nd window = 0.5 \n\n             edges      nodematch.ena nodematch.prestige    nodematch.party \n            1.1828             0.2123             1.2710            -0.4160 \n   gwesp.fixed.0.5    gwdsp.fixed.0.5 \n            0.3638            -0.2401 \n\nIndividual P-values (lower = worse):\n             edges      nodematch.ena nodematch.prestige    nodematch.party \n         0.2369010          0.8319044          0.2037202          0.6774413 \n   gwesp.fixed.0.5    gwdsp.fixed.0.5 \n         0.7160131          0.8102226 \nJoint P-value (lower = worse):  0.8553903 .\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/mcmc-diagnostics-1.png){width=1152}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMCMC diagnostics shown here are from the last round of simulation, prior to computation of final parameter estimates. Because the final estimates are refinements of those used for this simulation run, these diagnostics may understate model performance. To directly assess the performance of the final model on in-model statistics, please use the GOF command: gof(ergmFitObject, GOF=~model).\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\nMCMC Diagnostic Components Explained:\n\n- **Sample Statistics vs. Observed**: Compares simulated network statistics to observed values. Good fit shows statistics centered around zero.\n- **Trace Plots**: Show MCMC chain values over iterations. Good mixing looks like \"fuzzy caterpillar\" around zero.\n- **Density Plots**: Distribution of sampled statistics. Should be approximately normal and centered near zero.\n- **Autocorrelation Function (ACF)**: Measures correlation between successive samples. Should decay quickly to near zero.\n- **Geweke Diagnostic**: Tests whether early and late parts of chain come from same distribution (burn-in test).\n:::\n\nLet's extract some key diagnostic statistics:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngof_elite <- gof(fit_elite, GOF = ~degree + esp + dsp + triadcensus, \n                 verbose = FALSE)\nplot(gof_elite)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/diagnostic-summary-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/diagnostic-summary-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/diagnostic-summary-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/diagnostic-summary-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/diagnostic-summary-5.png){width=672}\n:::\n:::\n\n\n\nFrom the sample statistics vs. observed values, the statistics show good agreement between simulated and observed values. All terms have p-value \\> 0.05, The overall chi-squared test p = 0.022, indicating the model successfully reproduces the observed network statistics. The trace plots show relatively good mixing, fluctuating randomly around zero, which means MCMC chains are exploring the parameter space well and not getting trapped in any particular region. All the density plots are approximately centered near zeor, and no extreme skewness and multinodality (multiple peaks), indicating the sampling stable parameter estimation. Moreover, for the Geweke Diagnostic (Burn-in Test), all p-values are well above 0.05, indicating no evidence of non-convergence. The joint p-value of 0.820 indicates good overall convergence. Overall, the model successfully converged and the parameter estimates are reliable for inference.\n\n## 3. Case Study 2 - Balance Theory in Hansell Classroom Friendships\n\nNow let's examine balance theory using directed friendship nominations in a sixth-grade classroom, we've used this dataset in the [previous tutorial (Part 5)](https://aliceaii.github.io/posts/snapart5/):\n\n### 3.1 Is the friendship network balanced in Heider’s definition of balance?\n\n::: {.callout-tip}\n\n**Heider's Balance Theory**\nIn a balanced network:\n\n- **Transitive triads** (A→B→C implies A→C): \"Friend of friend is friend\"\n- **Avoided cyclic triads** (A→B→C→A without A→C): Creates tension\n\nBalanced networks have positive transitive triad coefficients and negative cyclic triad coefficients.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(networkdata)\ndata(hansell)\nhelp(hansell)\n\n#summary(hansell)\ntable(hansell %v% \"sex\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nfemale   male \n    14     13 \n```\n\n\n:::\n\n```{.r .cell-code}\ntriad.census(hansell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     003 012 102 021D 021U 021C 111D 111U 030T 030C 201 120D 120U 120C 210 300\n[1,] 771 982 248  234  115  150   68   97  126    2  13   32   32   20  28   7\n```\n\n\n:::\n\n```{.r .cell-code}\n#transitive triads\ntriads <- triad.census(hansell)\ntriads[9]  # 030T\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 126\n```\n\n\n:::\n\n```{.r .cell-code}\n#cyclic triads\ntriads[10]   # 030C    \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\n\n### 3.2 Fit the model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_balance <- ergm.tapered(\n  hansell ~ \n    edges +                          # Baseline density\n    mutual +                         # Reciprocity\n    nodematch(\"sex\", diff = TRUE) +  # Sex homophily (differentiated)\n    ttriple +                        # Transitive triples\n    ctriple,                         # Cyclic triples\n  verbose = FALSE\n)\n\nsummary(fit_balance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Results:\n\n                     Estimate Std. Error MCMC % z value Pr(>|z|)    \nedges                -3.06147    0.12542      0 -24.410   <1e-04 ***\nmutual                0.25919    0.36783      0   0.705    0.481    \nnodematch.sex.female  0.85847    0.11493      0   7.469   <1e-04 ***\nnodematch.sex.male    1.07967    0.15051      0   7.173   <1e-04 ***\nttriple               0.32888    0.01787      0  18.404   <1e-04 ***\nctriple              -0.40036    0.07597      0  -5.270   <1e-04 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nThe estimated tapering scaling factor is 2.\n\n     Null Deviance: 973.2  on 702  degrees of freedom\n Residual Deviance: 633.2  on 696  degrees of freedom\n \nAIC: 645.2  BIC: 672.5  (Smaller is better. MC Std. Err. = 0)\n```\n\n\n:::\n\n```{.r .cell-code}\nbalance_coef <- data.frame(\n  Term = c(\"Edges\", \"Mutual\", \"Same Sex (Female)\", \"Same Sex (Male)\", \n           \"Transitive Triples\", \"Cyclic Triples\"),\n  Coefficient = round(coef(fit_balance), 3),\n  OR = round(exp(coef(fit_balance)), 3))\n\nprint(balance_coef, row.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Term Coefficient    OR\n              Edges      -3.061 0.047\n             Mutual       0.259 1.296\n  Same Sex (Female)       0.858 2.360\n    Same Sex (Male)       1.080 2.944\n Transitive Triples       0.329 1.389\n     Cyclic Triples      -0.400 0.670\n```\n\n\n:::\n:::\n\n\n::: {.callout-important}\nEvidence for Balance model\n\nThe model provides strong evidence for balance theory:\n\n-  **Positive transitivity** (β = 0.33, p < 0.05): Transitive closure is preferred\n-  **Negative cyclicity** (β = -0.40, p < 0.001): Cyclic patterns are avoided\n-  **Strong sex homophily**: Both boys and girls prefer same-sex friendships\n- **No reciprocity effect**: Friendships aren't necessarily mutual at this age\n\nThis pattern suggests the classroom network organizes into balanced, sex-segregated friendship groups with clear hierarchical structures rather than cyclic patterns.\n:::\n\n-   **Transitive ties (ttriple):** $\\beta = 0.33$, the coefficient measures the tendency for transitive triadic closure in the network, it's significant. The $OR = 1.39$ means that for each additional transitive triple configuration, the odds of the network configuration increased by 39%. When student A nominates student B as a friend, and B nominates C, there is a significantly higher-than-random probability that A will also nominate C. This creates cohesive friendship groups with closed triadic structures.\n\n-   **Cyclic ties (ctriple):** $\\beta = -0.40$, the coefficient measures the tendency for cyclic triadic structures in the network, where: $A→B→C→A$ forms a cycle, but without the full transitive closure. The negative and highly significant coefficient (p \\< 0.001) indicates a strong avoidance of cyclic triadic structures. $OR = 0.67$ means that cyclic triple configurations decrease the odds of the network configuration by 33%. The negative coefficient shows that cyclic patterns are less common than would be expected in a random network.\n\n\n### 3.3 Model Comparison and Selection\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit alternative model for French elite network\nfit_elite_extended <- ergm.tapered(\n  ffef ~ \n    edges + \n    nodematch(\"ena\") + \n    nodematch(\"prestige\") + \n    nodematch(\"party\") +\n    nodematch(\"masons\") +           # Add Masonic membership\n    nodematch(\"religion\") +          # Add religion\n    nodecov(\"topboards\") +           # Board memberships as covariate\n    absdiff(\"topboards\") +           # Difference in board memberships\n    gwesp(0.5, fixed = TRUE) + \n    gwdsp(0.5, fixed = TRUE),\n  verbose = FALSE\n)\n\n# Model comparison\nanova_result <- anova(fit_elite, fit_elite_extended)\nprint(anova_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: ffef ~ Taper(~edges + nodematch(\"ena\") + nodematch(\"prestige\") + \n    nodematch(\"party\") + gwesp(0.5, fixed = TRUE) + gwdsp(0.5, \n    fixed = TRUE), coef = .taper.coef, m = .taper.center)\nModel 2: ffef ~ Taper(~edges + nodematch(\"ena\") + nodematch(\"prestige\") + \n    nodematch(\"party\") + nodematch(\"masons\") + nodematch(\"religion\") + \n    nodecov(\"topboards\") + absdiff(\"topboards\") + gwesp(0.5, \n    fixed = TRUE) + gwdsp(0.5, fixed = TRUE), coef = .taper.coef, \n    m = .taper.center)\n     Df Deviance Resid. Df Resid. Dev Pr(>|Chisq|)    \nNULL                   378     524.02                 \n1     6    222.0       372     302.02       <2e-16 ***\n2     4     -0.1       368     302.11       0.9988    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# AIC comparison\naic_comparison <- data.frame(\n  Model = c(\"Base\", \"Extended\"),\n  AIC = c(AIC(fit_elite), AIC(fit_elite_extended)),\n  BIC = c(BIC(fit_elite), BIC(fit_elite_extended)),\n  Parameters = c(length(coef(fit_elite)), length(coef(fit_elite_extended)))\n)\nprint(aic_comparison)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Model      AIC      BIC Parameters\n1     Base 314.0151 337.6245          6\n2 Extended 322.1149 361.4638         10\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\nModel Selection Guidelines\n\n- **Lower AIC/BIC** indicates better model fit accounting for complexity\n- **ANOVA p-value > 0.05** suggests additional terms don't significantly improve fit\n- **Check MCMC diagnostics** for both models - better convergence often trumps marginal fit improvements\n- **Substantive interpretation** matters - include terms that make theoretical sense\n\nIn our case, the simpler model is preferred: lower AIC, similar fit, better convergence.\n:::\n\n\n## References\n\n- Hansell, S. (1984). \"Cooperative groups, weak ties, and the integration of peer friendships.\" *Social Psychology Quarterly*, 47(4), 316-328.\n\n- Kadushin, C. (1995). \"Friendship among the French financial elite.\" *American Sociological Review*, 60, 202-221.\n\n- Snijders, T.A.B., Pattison, P.E., Robins, G.L., & Handcock, M.S. (2006). \"New specifications for exponential random graph models.\" *Sociological Methodology*, 36(1), 99-153.\n\n- Hunter, D.R., & Handcock, M.S. (2006). \"Inference in curved exponential family models for networks.\" *Journal of Computational and Graphical Statistics*, 15(3), 565-583.\n\n---\n\n*This tutorial is based on UCLA [STATS 218: Social Network Analysis](https://handcock.github.io/teaching/218/) taught by Prof [Mark Handcock](https://handcock.github.io/).*\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}