{
  "hash": "698eb46cdef7ed67f0b9e6765a5179e9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Matching Methods for Causal Inference\"\nauthor: Shuhan (Alice) Ai\ndate: \"2025-05-02\"\ncategories: [R, Causal Inference]\ntoc: true\ntoc-depth: 3\ntoc-title: \"Contents\"\ncode-fold: show\ncode-tools: true\nimage: \"p1.png\"\noutput:\n  html_document:\n    mathjax: default\n    self_contained: true\n---\n\nObservational data rarely cooperate with our causal questions because treatment groups differ systematically from controls, confounding threatens validity, and randomization isn't an option. Matching methods offer a principled solution: reconstruct the experiment you wish you'd run by explicitly pairing treated units with controls that look identical on observed characteristics.\n\nThis tutorial introduces the statistical foundations of matching methods, walks through practical implementation in R using propensity score and Mahalanobis distance approaches, and demonstrates doubly-robust estimation with a real-world example examining COVID-19 instructional modality effects on student achievement.\n\n![](p1.png)\n\n## 1. Introduction\n\nIn observational studies where treatment assignment is not randomized, matching methods provide a powerful approach to estimate causal effects under the assumption of **selection on observables**. The core idea is deceptively simple: for each treated unit, find comparison units that look similar on observed pre-treatment characteristics. By comparing outcomes between these matched groups, we can estimate treatment effects while controlling for observed confounding.\n\n### 1.1 The Fundamental Challenge\n\nRecall from the [Potential Outcomes framework](https://aliceaii.github.io/posts/ci_po/) that causal inference faces the fundamental problem: we can never observe both $Y_i(1)$ and $Y_i(0)$ for the same unit. Matching addresses this by finding units in the comparison group that are \"similar enough\" to treated units that we can plausibly treat their observed outcomes as proxies for the unobserved counterfactuals.\n\n### 1.2 Key Assumptions\n\nMatching methods rely on three core assumptions:\n\n1. **Conditional Independence (Unconfoundedness)**: $(Y_i(1), Y_i(0)) \\perp\\!\\!\\!\\perp D_i \\mid \\mathbf{X}_i$\n\n   Treatment assignment is independent of potential outcomes, conditional on observed covariates $\\mathbf{X}$.\n\n2. **Positivity (Common Support)**: $0 < P(D_i = 1 \\mid \\mathbf{X}_i) < 1$\n\n   All units have a non-zero probability of receiving both treatment and control.\n\n3. **SUTVA**: Treatment assignment of one unit does not affect potential outcomes of other units.\n\nWhen these assumptions hold, we can identify causal effects by conditioning on (or matching on) observed covariates.\n\n### 1.3 Why Match?\n\nMatching offers several advantages:\n\n- **Transparency**: The matched sample is explicit—you can see exactly which units are being compared\n- **Balance diagnostics**: Easy to check whether treatment and control groups are comparable on observed covariates\n- **Nonparametric**: Unlike regression, matching doesn't assume a particular functional form\n- **Estimand flexibility**: Can target ATE, ATT, or ATC depending on the matching approach\n\n\n## 2. Types of Matching Methods\n\nMatching methods vary along several key dimensions. Understanding these trade-offs is crucial for selecting the appropriate method for your analysis.\n\n### 2.1 Subclassification (Stratification)\n\n**What it is:** Partition the sample into $J$ subclasses based on propensity scores or covariate values, then estimate treatment effects within each subclass.\n\n$$\\hat{\\tau}_{ATE} = \\sum_{j=1}^{J} \\frac{n_j}{n} \\hat{\\tau}_j$$\n\nwhere $\\hat{\\tau}_j = \\bar{Y}_j^1 - \\bar{Y}_j^0$ is the effect in subclass $j$.\n\n**When to use:**\n\n- When you want to retain all units in the analysis\n- When you're interested in heterogeneous treatment effects across subclasses\n- As an initial diagnostic before more complex matching\n\n**Trade-offs:**\n\n- Preserves entire sample (maximizes statistical power)\n- Straightforward to implement and interpret\n- May have residual imbalance within subclasses, especially if subclasses are broad\n- Performance depends heavily on number of subclasses chosen\n\n```r\n# Subclassification example\nlibrary(MatchIt)\n\n# Create 5 subclasses based on propensity score\nm_sub <- matchit(treat ~ age + education + income,\n                 data = dat,\n                 method = \"subclass\",\n                 subclass = 5,\n                 estimand = \"ATE\")\n\n# Check balance\nsummary(m_sub)\n```\n\n### 2.2 Exact Matching\n\n**What it is:** Match units that have identical values on all specified covariates.\n\n**When to use:**\n\n- When you have categorical covariates or discretized continuous variables\n- When perfect balance on certain variables is crucial (e.g., matching within the same school)\n- As a component of a stratified matching strategy\n\n**Trade-offs:**\n\n- Achieves perfect balance on matched covariates\n- No modeling assumptions about distance between units\n- **Curse of dimensionality**: Quickly becomes infeasible as number of covariates increases\n- Often results in many unmatched units, reducing sample size dramatically\n\n```r\n# Exact matching\nm_exact <- matchit(treat ~ gender + race + school_id,\n                   data = dat,\n                   method = \"exact\",\n                   estimand = \"ATT\")\n```\n\n### 2.3 Coarsened Exact Matching (CEM)\n\n**What it is:** \"Coarsen\" continuous variables into bins, then perform exact matching on the coarsened variables.\n\n**When to use:**\n\n- When you want the interpretability of exact matching but have continuous covariates\n- When you're willing to sacrifice some precision for transparency\n\n**Trade-offs:**\n\n- More transparent than propensity score matching\n- Reduces model dependence\n- Monotonic imbalance bounding property (imbalance can only improve)\n- Results sensitive to coarsening choices\n- Can still leave many units unmatched\n\n```r\n# CEM example\nlibrary(MatchIt)\n\nm_cem <- matchit(treat ~ age + income + education,\n                 data = dat,\n                 method = \"cem\",\n                 cutpoints = list(age = \"q5\",     # quintiles\n                                  income = \"ss3\")) # 3 equal-size bins\n```\n\n### 2.4 Propensity Score Matching\n\n**What it is:** Match units based on their propensity score $e(\\mathbf{X}) = P(D=1 \\mid \\mathbf{X})$.\n\nBy Rosenbaum & Rubin (1983), conditional independence given $\\mathbf{X}$ implies conditional independence given $e(\\mathbf{X})$:\n\n$$(Y_i(1), Y_i(0)) \\perp\\!\\!\\!\\perp D_i \\mid e(\\mathbf{X}_i)$$\nThis reduces matching from potentially high-dimensional $\\mathbf{X}$ to a single dimension.\n\n#### 2.4.1 Nearest Neighbor Matching\n\n**What it is:** For each treated unit, find the $k$ control units with the closest propensity scores.\n\n**Variants:**\n\n- **Greedy matching**: Match units sequentially, making locally optimal choices\n- **Optimal matching**: Finds the global optimal matching that minimizes total distance\n\n**When to use:**\n\n- **1:1 matching without replacement**: When you want a simple, interpretable matched sample for ATT\n- **1:k matching**: When you need better precision but have abundant controls\n- **With replacement**: When control pool is limited or when you want better balance\n\n**Trade-offs:**\n\n- Easy to understand and implement\n- 1:1 matching without replacement gives balanced sample sizes\n- Greedy algorithm can produce poor matches late in the sequence\n- Can match very dissimilar units if no caliper is used\n\n```r\n# 1-to-1 nearest neighbor (greedy) without replacement\nm_nn <- matchit(treat ~ age + education + income,\n                data = dat,\n                method = \"nearest\",\n                distance = \"glm\",\n                replace = FALSE,\n                ratio = 1,\n                m.order = \"largest\",  # match highest PS first\n                estimand = \"ATT\")\n\n# With a caliper\nm_nn_cal <- matchit(treat ~ age + education + income,\n                    data = dat,\n                    method = \"nearest\",\n                    distance = \"glm\",\n                    caliper = 0.1,        # 0.1 SD of logit(PS)\n                    replace = FALSE,\n                    estimand = \"ATT\")\n\n# Optimal matching\nm_opt <- matchit(treat ~ age + education + income,\n                 data = dat,\n                 method = \"optimal\",\n                 distance = \"glm\",\n                 ratio = 1,\n                 estimand = \"ATT\")\n```\n\n#### 2.4.2 Radius/Caliper Matching\n\n**What it is:** Match treated units only to controls within a specified radius (caliper) on the propensity score.\n\n**When to use:**\n\n- When you want to avoid poor-quality matches\n- When common support violations are a concern\n\n**Trade-offs:**\n\n- Ensures match quality by excluding bad matches\n- Can use all controls within the caliper (not just nearest)\n- May leave treated units unmatched\n- Results sensitive to caliper width choice\n\n```r\n# Basic radius matching: match all controls within caliper\nm_radius <- matchit(treat ~ age + education + income,\n                    data = dat,\n                    method = \"nearest\",\n                    distance = \"glm\",\n                    caliper = 0.1,        # 0.1 SD of logit(PS)\n                    std.caliper = TRUE,   # standardize caliper\n                    replace = TRUE,       # allow control reuse\n                    estimand = \"ATT\")\n\n# Stricter caliper (fewer poor matches)\nm_radius_strict <- matchit(treat ~ age + education + income,\n                          data = dat,\n                          method = \"nearest\",\n                          distance = \"glm\",\n                          caliper = 0.05,     # tighter radius\n                          std.caliper = TRUE,\n                          replace = TRUE,\n                          estimand = \"ATT\")\n\n# Radius matching without replacement (each control used once)\nm_radius_norep <- matchit(treat ~ age + education + income,\n                         data = dat,\n                         method = \"nearest\",\n                         distance = \"glm\",\n                         caliper = 0.1,\n                         std.caliper = TRUE,\n                         replace = FALSE,    # no reuse\n                         estimand = \"ATT\")\n\n# Check how many treated units were matched\nsummary(m_radius)$nn  # Shows matched/unmatched counts\n```\n\n#### 2.4.3 Full Matching\n\n**What it is:** Forms matched sets where each set contains either:\n\n- One treated unit and multiple controls, OR\n- One control unit and multiple treated units\n\n**When to use:**\n\n- When you want to use all units in the sample\n- When estimating ATE (not just ATT)\n- When you have many more controls than treated units (or vice versa)\n\n**Trade-offs:**\n\n- Uses full sample → no loss of statistical power\n- Optimizes overall balance across entire sample\n- Can estimate ATE, ATT, or ATC with appropriate weighting\n- More complex to implement and explain\n- Requires understanding of matching weights\n\n```r\n# Full matching\nm_full <- matchit(treat ~ age + education + income,\n                  data = dat,\n                  method = \"full\",\n                  distance = \"glm\",\n                  estimand = \"ATE\")\n\n# Quick matching (faster than optimal full)\nm_quick <- matchit(treat ~ age + education + income,\n                   data = dat,\n                   method = \"quick\",\n                   distance = \"glm\",\n                   estimand = \"ATT\")\n```\n\n### 2.5 Summary: Choosing a Matching Method\n\n| Method | Sample Size | Balance Quality | Complexity | Best For |\n|--------|-----------|-----------------|----------|-------------|\n| Subclassification | Full sample | Moderate | Low | Initial exploration, transparency |\n| Exact | Often small | Perfect (on matched vars) | Low | Few categorical covariates |\n| CEM | Variable | Good | Low | Categorical + continuous covariates |\n| 1:1 NN | 50% of sample | Variable | Low | Simple ATT estimation |\n| 1:1 NN + caliper | Variable | Good | Low | Quality-controlled ATT |\n| k:1 Matching | Larger | Good (averaging reduces noise) | Moderate | Improving precision |\n| Optimal | 50% of sample | Good (globally optimal) | Moderate | Best 1:1 matches |\n| Full | Full sample | Excellent (minimal distance) | High | ATE with all units |\n\n## 3. Distance Measures\n\nThe choice of distance metric fundamentally shapes which units are considered \"similar.\"\n\n### 3.1 Propensity Score Distance\n\n**Definition:** The propensity score $e(\\mathbf{X}) = P(D=1 \\mid \\mathbf{X})$ is typically estimated via logistic regression:\n\n$$\\text{logit}(e(\\mathbf{X})) = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\ldots$$\n\nDistance between units $i$ and $j$:\n$$d_{ij} = |e(\\mathbf{X}_i) - e(\\mathbf{X}_j)|$$\n\nor in logit space:\n$$d_{ij} = |\\text{logit}(e(\\mathbf{X}_i)) - \\text{logit}(e(\\mathbf{X}_j))|$$\n**Advantages:**\n\n- Dimension reduction: collapse many covariates into one score\n- Balancing property: balancing on $e(\\mathbf{X})$ tends to balance $\\mathbf{X}$\n- Well-studied theoretical properties\n\n**Considerations:**\n\n- **Model misspecification**: If propensity score model is wrong, matches may be poor\n- **Which scale?** Matching on logit scale often works better as it expands regions near 0 and 1\n- **Caliper choice**: Common rule of thumb is 0.2 SD of the logit propensity score\n\n```r\n# Estimate propensity scores\nps_model <- glm(treat ~ age + education + income + race + gender,\n                data = dat,\n                family = binomial(link = \"logit\"))\n\n# Add propensity scores to data\ndat$ps <- predict(ps_model, type = \"response\")\ndat$ps_logit <- qlogis(dat$ps)  # logit scale\n\n# Check overlap\nlibrary(ggplot2)\n\nggplot(dat, aes(x = ps, fill = factor(treat))) +\n  geom_histogram(position = \"identity\", alpha = 0.5, bins = 30) +\n  scale_fill_manual(values = c(\"red\", \"blue\"),\n                    labels = c(\"Control\", \"Treated\")) +\n  labs(x = \"Propensity Score\",\n       y = \"Count\",\n       fill = \"Group\",\n       title = \"Propensity Score Overlap\") +\n  theme_minimal()\n```\n\n### 3.2 Mahalanobis Distance\n\n**Definition:** Accounts for correlations between covariates and different scales:\n\n$$d_{ij} = \\sqrt{(\\mathbf{X}_i - \\mathbf{X}_j)^T \\mathbf{S}^{-1} (\\mathbf{X}_i - \\mathbf{X}_j)}$$\nwhere $\\mathbf{S}$ is the covariance matrix of $\\mathbf{X}$.\n\n**When to use:**\n\n- When covariates are correlated\n- When you don't trust the propensity score model\n- When you want to match directly on covariates\n\n**Advantages:**\n\n- Scale-invariant\n- Accounts for covariate correlations\n- No need to model propensity score\n\n**Disadvantages:**\n\n- Curse of dimensionality (difficult with many covariates)\n- Can be computationally intensive\n\n```r\n# Mahalanobis distance matching\nm_maha <- matchit(treat ~ age + education + income,\n                  data = dat,\n                  method = \"nearest\",\n                  distance = \"mahalanobis\",\n                  estimand = \"ATT\")\n```\n\n### 3.3 Euclidean Distance\n\nSimple distance on standardized covariates:\n\n$$d_{ij} = \\sqrt{\\sum_{k=1}^{K} \\frac{(X_{ik} - X_{jk})^2}{\\sigma_k^2}}$$\nLess commonly used as it doesn't account for correlations.\n\n### 3.4 Distance + Exact Matching\n\nYou can combine distance-based matching with exact matching on key variables:\n\n```r\n# Exact match on gender and race, nearest neighbor on PS\nm_combo <- matchit(treat ~ age + education + income + race + gender,\n                   data = dat,\n                   method = \"nearest\",\n                   distance = \"glm\",\n                   exact = ~ race + gender,  # exact match on these\n                   estimand = \"ATT\")\n```\n\n## 4. Doubly-Robust Estimation\n\nOne of the most powerful features of matching methods is that they can be combined with outcome regression to form **doubly-robust (DR) estimators**. This approach provides a \"second chance\" at consistent estimation.\n\n### 4.1 The Doubly-Robust Property\n\nA doubly-robust estimator requires specifying two models:\n\n1. **Treatment model**: $P(D_i = 1 \\mid \\mathbf{X}_i) = e(\\mathbf{X}_i)$ (propensity score)\n2. **Outcome model**: $E[Y_i \\mid D_i, \\mathbf{X}_i] = \\mu(D_i, \\mathbf{X}_i)$\n\nThe key insight: **If either model is correctly specified, the treatment effect estimate remains consistent**, even if the other model is misspecified. This offers protection against model misspecification—a major concern in observational studies.\n\n### 4.2 Mathematical Framework\n\nFor the **ATT**, a doubly-robust estimator takes the form:\n\n$$\n\\hat{\\tau}_{ATT}^{DR} = \\frac{1}{n_1} \\sum_{i=1}^{n} \\left[ D_i \\left(Y_i - \\hat{\\mu}_0(\\mathbf{X}_i)\\right) + \\frac{D_i - \\hat{e}(\\mathbf{X}_i)}{1 - \\hat{e}(\\mathbf{X}_i)} \\left(Y_i - \\hat{\\mu}_0(\\mathbf{X}_i)\\right) \\right]\n$$\nwhere:\n\n- $\\hat{\\mu}_0(\\mathbf{X}_i)$ = predicted outcome under control\n- $\\hat{e}(\\mathbf{X}_i)$ = estimated propensity score\n- $n_1$ = number of treated units\n\n| Component | Active for | Purpose | Protects against |\n|-----------|-----------|---------|------------------|\n| $D_i(Y_i - \\hat{\\mu}_0)$ | Treated units | Impute counterfactual using outcome model | PS model misspecification |\n| $-\\frac{(1-D_i)\\hat{e}}{1-\\hat{e}}(Y_i - \\hat{\\mu}_0)$ | Control units | Correct imputation errors using weighted residuals | Outcome model misspecification |\n\n**Intuition:**\n\n- **Treated units**: Calculate individual treatment effects as observed outcome minus model-predicted control outcome\n-  **Control units**: Use their prediction errors to correct bias in the outcome model, weighted by how \"treated-like\" they are (via propensity score odds)\n- **Double protection**: Consistency requires only ONE model to be correct—either PS model or outcome model\n\n\nFor the **ATE**, the estimator is:\n\n$$\n\\hat{\\tau}_{ATE}^{DR} = \\frac{1}{n} \\sum_{i=1}^{n} \\left[ \\frac{D_i Y_i}{\\hat{e}(\\mathbf{X}_i)} - \\frac{(D_i - \\hat{e}(\\mathbf{X}_i)) \\hat{\\mu}_1(\\mathbf{X}_i)}{\\hat{e}(\\mathbf{X}_i)} \\right] - \\left[ \\frac{(1-D_i) Y_i}{1-\\hat{e}(\\mathbf{X}_i)} + \\frac{(D_i - \\hat{e}(\\mathbf{X}_i)) \\hat{\\mu}_0(\\mathbf{X}_i)}{1-\\hat{e}(\\mathbf{X}_i)} \\right]\n$$\n\n### 4.3 Why Doubly-Robust?\n\nConsider three scenarios:\n\n| Propensity Model | Outcome Model | DR Estimator |\n|-----------------|---------------|--------------|\n| Correct | Wrong | Consistent |\n| Wrong | Correct | Consistent |\n| Correct | Correct | Consistent (most efficient) |\n| Wrong | Wrong | Inconsistent |\n\nThe estimator is \"doubly protected\": it only fails if **both** models are wrong.\n\n### 4.4 Implementation Strategy\n\nIn practice, doubly-robust estimation after matching follows this workflow:\n\n**Step 1: Matching/Weighting**\n- Estimate propensity scores: $\\hat{e}(\\mathbf{X})$\n- Create matched sample or weights\n- This addresses confounding via the **treatment model**\n\n**Step 2: Outcome Regression on Matched Sample**\n- Fit: $Y_i = \\alpha + \\tau D_i + \\boldsymbol{\\beta}'\\mathbf{X}_i + \\varepsilon_i$\n- Include the same covariates used in matching\n- This addresses residual confounding via the **outcome model**\n\n**Step 3: G-Computation for Correct SE**\n- Use `marginaleffects::avg_comparisons()` with appropriate `vcov` option\n- Cluster-robust SE if using matching with replacement\n- This accounts for matching structure\n\n```r\nlibrary(MatchIt)\nlibrary(marginaleffects)\n\n# Step 1: Propensity score matching\nmatch_obj <- matchit(\n  treat ~ x1 + x2 + x3 + x4,\n  data = dat,\n  method = \"nearest\",\n  distance = \"glm\",\n  caliper = 0.1,\n  estimand = \"ATT\"\n)\n\n# Step 2: Get matched data\nmd <- match.data(match_obj)\n\n# Step 3: Fit outcome model WITH covariates (doubly-robust)\nmod_dr <- lm(\n  outcome ~ treat + x1 + x2 + x3 + x4,\n  data = md,\n  weights = weights  # Use matching weights\n)\n\n# Step 4: Estimate ATT with g-computation and robust SE\natt_dr <- avg_comparisons(\n  mod_dr,\n  variables = \"treat\",\n  vcov = \"HC3\",  # Robust SE\n  newdata = subset(treat == 1)  # For ATT\n)\n\nprint(att_dr)\n```\n\n### 4.5 Targeted Maximum Likelihood Estimation (TMLE)\n\n**Targeted Maximum Likelihood Estimation (TMLE)** represents the state-of-the-art in doubly-robust estimation. While standard AIPW combines two models additively, TMLE iteratively **updates** the outcome model to optimize bias reduction for the specific causal parameter you're estimating.\n\n#### 4.5.1 Why \"Targeted\"?\n\nStandard maximum likelihood estimation optimizes the **entire likelihood** of the outcome model. But we don't care about predicting $Y$ perfectly—we only care about getting the **causal effect** right. TMLE \"targets\" the estimation procedure specifically toward the parameter of interest (ATE, ATT, etc.), achieving:\n\n1. **Asymptotic efficiency**: Achieves the semiparametric efficiency bound (lowest possible variance)\n2. **Double robustness**: Consistent if either model is correct\n3. **Finite sample bias reduction**: Updates reduce bias even in small samples\n4. **Respect for bounds**: Predictions stay within valid ranges (e.g., probabilities in [0,1])\n\n#### 4.5.2 The TMLE Algorithm\n\n**Step 1: Initial estimation**\n\n- Fit outcome model: $\\hat{Q}_0(A, W) = E[Y \\mid A, W]$\n- Fit propensity score: $\\hat{g}(W) = P(A=1 \\mid W)$\n\n**Step 2: Clever covariate**\nConstruct the \"clever covariate\" $H(A, W)$ based on the estimand:\n\n- For ATE: $H(A,W) = \\frac{A}{\\hat{g}(W)} - \\frac{1-A}{1-\\hat{g}(W)}$\n- For ATT: $H(A,W) = A - \\frac{(1-A)\\hat{g}(W)}{1-\\hat{g}(W)}$\n\n**Step 3: Targeting step**\nUpdate the initial outcome model by fitting:\n$$\\text{logit}(\\hat{Q}_1(A,W)) = \\text{logit}(\\hat{Q}_0(A,W)) + \\epsilon \\cdot H(A,W)$$\n\nThis fluctuation parameter $\\epsilon$ is chosen to eliminate residual confounding bias.\n\n**Step 4: Iterate**\nRepeat Step 3 until $\\epsilon \\approx 0$ (typically 1-3 iterations).\n\n**Step 5: Estimate causal effect**\nThe final targeted estimate:\n$$\\hat{\\psi}_{TMLE} = \\frac{1}{n}\\sum_{i=1}^n [\\hat{Q}_1(1, W_i) - \\hat{Q}_1(0, W_i)]$$\n\n**TMLE vs. Standard AIPW**\n\n| Feature | Standard AIPW | TMLE |\n|---------|---------------|------|\n| **Estimation** | Fit models independently | Iteratively update outcome model |\n| **Efficiency** | Efficient only asymptotically | Efficient in finite samples |\n| **Bounded predictions** | Can produce invalid predictions | Respects outcome bounds |\n| **Bias** | First-order bias removed | Higher-order bias reduction |\n| **Machine learning** | Compatible but suboptimal | Designed for ensemble methods |\n\n#### 4.5.3 Implementation with Super Learner\n\nTMLE shines when combined with **Super Learner** (ensemble machine learning), which automatically selects the best-weighted combination of algorithms:\n\n```r\nlibrary(tmle)\nlibrary(SuperLearner)\n\n# Define candidate algorithms for ensemble\nSL.library <- c(\n  \"SL.glm\",           # Logistic/linear regression\n  \"SL.glmnet\",        # Elastic net (LASSO/Ridge)\n  \"SL.gam\",           # Generalized additive models\n  \"SL.earth\",         # Multivariate adaptive regression splines\n  \"SL.ranger\",        # Random forest\n  \"SL.xgboost\"        # Gradient boosting\n)\n\n# Estimate ATE using TMLE\ntmle_ate <- tmle(\n  Y = dat$outcome,\n  A = dat$treat,\n  W = dat[, c(\"x1\", \"x2\", \"x3\", \"x4\")],\n  Q.SL.library = SL.library,  # Ensemble for outcome model\n  g.SL.library = SL.library,  # Ensemble for PS model\n  family = \"gaussian\"          # Continuous outcome\n)\n\n# Results\nsummary(tmle_ate)\n\n# Extract key quantities\ntmle_ate$estimates$ATE$psi        # Point estimate\ntmle_ate$estimates$ATE$var.psi    # Variance\ntmle_ate$estimates$ATE$CI         # 95% CI\ntmle_ate$estimates$ATE$pvalue     # P-value\n```\n\n```r\n#For ATT Estimation\n# Create indicator for treated units\ndat$target_pop <- as.numeric(dat$treat == 1)\n\n# TMLE for ATT\ntmle_att <- tmle(\n  Y = dat$outcome,\n  A = dat$treat,\n  W = dat[, c(\"x1\", \"x2\", \"x3\", \"x4\")],\n  Q.SL.library = SL.library,\n  g.SL.library = SL.library,\n  gbound = c(0.01, 0.99),       # Trim extreme PS (avoid positivity violations)\n  family = \"gaussian\"\n)\n\n# For true ATT, manually calculate on treated units\nate_est <- tmle_att$estimates$ATE$psi\ntreated_outcome <- mean(dat$outcome[dat$treat == 1])\natt_est <- ate_est  # Under correct specification\n```\n\n```r\n# Diagnostics and Interpretation\n# Check Super Learner weights (which algorithms were chosen?)\ntmle_ate$g$coef   # Weights for PS model\ntmle_ate$Qinit$coef  # Weights for outcome model\n\n# Check convergence\ntmle_ate$epsilon  # Should be close to 0\n\n# Check influence curve-based inference\nhist(tmle_ate$estimates$IC$IC.ATE)  # Should be roughly symmetric\n\n# Compare with standard AIPW\nlibrary(marginaleffects)\n\n# Standard regression approach\nmod_aipw <- lm(outcome ~ treat + x1 + x2 + x3 + x4, data = dat)\nate_aipw <- avg_comparisons(mod_aipw, variables = \"treat\")\n\n# Compare estimates\ntibble(\n  Method = c(\"TMLE\", \"Standard AIPW\"),\n  Estimate = c(tmle_ate$estimates$ATE$psi, ate_aipw$estimate),\n  SE = c(sqrt(tmle_ate$estimates$ATE$var.psi), ate_aipw$std.error)\n)\n```\n\n#### 4.5.4 When to Use TMLE\n\n**Choose TMLE when:**\n\n- You have **moderate to large samples** (n > 500)\n- You want to use **machine learning** for outcome and PS models\n- **Efficiency matters** (e.g., underpowered studies, costly data collection)\n- You're estimating effects in contexts where **small biases matter** (e.g., policy decisions)\n- You need **valid inference** even with model misspecification\n\n**Use simpler DR methods when:**\n\n- Sample is small (n < 200) and you're using parametric models anyway\n- Computational resources are limited\n- Transparency and interpretability are paramount\n- You're doing exploratory/preliminary analysis\n\n## 5. Practical Example\n\n### 5.1 Research Question\n\nThe Education Policy Director from the National Governors Association wants to understand: **Did school districts that used primarily in-person instruction during the 2020-21 school year experience smaller learning losses than districts that used remote or hybrid instruction?**\n\nSpecifically, we want to estimate the **Average Treatment Effect on the Treated (ATT)**:\n\n$$\\text{ATT} = E[Y_i(1) - Y_i(0) \\mid D_i = 1]$$\n\nwhere:\n\n- $Y_i(1)$ = 2022 math achievement for district $i$ if they used in-person instruction\n- $Y_i(0)$ = 2022 math achievement for district $i$ if they used remote/hybrid instruction\n- $D_i = 1$ indicates the district used in-person instruction\n\n### 5.2 Data Description\n\nWe'll use data from the Stanford Education Data Archive (SEDA) containing **5,358 U.S. school districts** with:\n\n**Treatment Variable:**\n- `inperson` = Binary indicator for whether the district was primarily in-person during 2020-21 (1 = in-person, 0 = remote/hybrid)\n\n**Outcome Variable:**\n- `yscore22` = District's average math test score in 2022, scaled so that 0 = average U.S. achievement for a 5th grader in 2019, and 1 unit = 1 student-level standard deviation\n\n**Pre-Treatment Covariates (measured in 2019):**\n\n*Geographic characteristics:*\n\n- `urban` = City location indicator\n- `suburb` = Suburban location indicator  \n- `town` = Town location indicator\n- `rural` = Rural location indicator\n\n*District size:*\n\n- `totenrl` = Total district enrollment\n- `enravg38` = Average enrollment per grade (grades 3-8)\n\n*Student demographics:*\n\n- `perblk` = Proportion Black students\n- `perhsp` = Proportion Latinx/Hispanic students\n- `perasn` = Proportion Asian students\n- `pernam` = Proportion Native American students\n- `perwht` = Proportion White students\n- `perfrl` = Proportion eligible for free lunch (poverty proxy)\n\n*Socioeconomic context:*\n\n- `sesavgall` = Average SES in district boundary\n- `lninc50avgall` = Log median income in district boundary\n- `baplusavgall` = Proportion adults with bachelor's degree\n- `povertyavgall` = Proportion families below poverty line\n\n*Baseline achievement:*\n\n- `yscore19` = District's average math score in 2019 (pre-pandemic)\n\n### 5.3 Load and Explore Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(MatchIt)\nlibrary(cobalt)\nlibrary(marginaleffects)\nlibrary(patchwork)\n\n# Load the actual homework data\nhw <- readRDS(\"ed255data_hw3_sedamath22.rds\")\n\n# Quick overview\ncat(\"Sample size:\", nrow(hw), \"districts\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample size: 5358 districts\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Treatment group:\", sum(hw$inperson), \"in-person districts\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTreatment group: 2183 in-person districts\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Control group:\", sum(1 - hw$inperson), \"remote/hybrid districts\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nControl group: 3175 remote/hybrid districts\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Treatment prevalence:\", round(mean(hw$inperson) * 100, 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTreatment prevalence: 40.7 %\n```\n\n\n:::\n:::\n\n\n### 5.4 Step 1: Check Pre-Treatment Covariate Balance\n\nBefore matching, let's examine how in-person and remote districts differ:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(table1)\nlibrary(flextable)\n\ndesc_table <- table1(\n  ~ yscore19 + urban + suburb + town + rural + totenrl + \n    sesavgall + lninc50avgall + baplusavgall | as.factor(inperson), \n  data = hw\n)\n\ndesc_table\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"Rtable1\"><table class=\"Rtable1\">\n<thead>\n<tr>\n<th class='rowlabel firstrow lastrow'></th>\n<th class='firstrow lastrow'><span class='stratlabel'>0<br><span class='stratn'>(N=3175)</span></span></th>\n<th class='firstrow lastrow'><span class='stratlabel'>1<br><span class='stratn'>(N=2183)</span></span></th>\n<th class='firstrow lastrow'><span class='stratlabel'>Overall<br><span class='stratn'>(N=5358)</span></span></th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td class='rowlabel firstrow'>yscore19</td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n</tr>\n<tr>\n<td class='rowlabel'>Mean (SD)</td>\n<td>0.0274 (0.413)</td>\n<td>0.0827 (0.343)</td>\n<td>0.0500 (0.387)</td>\n</tr>\n<tr>\n<td class='rowlabel lastrow'>Median [Min, Max]</td>\n<td class='lastrow'>0.0126 [-1.11, 1.35]</td>\n<td class='lastrow'>0.0849 [-1.31, 1.31]</td>\n<td class='lastrow'>0.0514 [-1.31, 1.35]</td>\n</tr>\n<tr>\n<td class='rowlabel firstrow'>urban</td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n</tr>\n<tr>\n<td class='rowlabel'>Mean (SD)</td>\n<td>0.101 (0.301)</td>\n<td>0.0454 (0.208)</td>\n<td>0.0782 (0.269)</td>\n</tr>\n<tr>\n<td class='rowlabel lastrow'>Median [Min, Max]</td>\n<td class='lastrow'>0 [0, 1.00]</td>\n<td class='lastrow'>0 [0, 1.00]</td>\n<td class='lastrow'>0 [0, 1.00]</td>\n</tr>\n<tr>\n<td class='rowlabel firstrow'>suburb</td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n</tr>\n<tr>\n<td class='rowlabel'>Mean (SD)</td>\n<td>0.458 (0.498)</td>\n<td>0.197 (0.398)</td>\n<td>0.352 (0.478)</td>\n</tr>\n<tr>\n<td class='rowlabel lastrow'>Median [Min, Max]</td>\n<td class='lastrow'>0 [0, 1.00]</td>\n<td class='lastrow'>0 [0, 1.00]</td>\n<td class='lastrow'>0 [0, 1.00]</td>\n</tr>\n<tr>\n<td class='rowlabel firstrow'>town</td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n</tr>\n<tr>\n<td class='rowlabel'>Mean (SD)</td>\n<td>0.166 (0.372)</td>\n<td>0.260 (0.439)</td>\n<td>0.204 (0.403)</td>\n</tr>\n<tr>\n<td class='rowlabel lastrow'>Median [Min, Max]</td>\n<td class='lastrow'>0 [0, 1.00]</td>\n<td class='lastrow'>0 [0, 1.00]</td>\n<td class='lastrow'>0 [0, 1.00]</td>\n</tr>\n<tr>\n<td class='rowlabel firstrow'>rural</td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n</tr>\n<tr>\n<td class='rowlabel'>Mean (SD)</td>\n<td>0.275 (0.447)</td>\n<td>0.497 (0.500)</td>\n<td>0.366 (0.482)</td>\n</tr>\n<tr>\n<td class='rowlabel lastrow'>Median [Min, Max]</td>\n<td class='lastrow'>0 [0, 1.00]</td>\n<td class='lastrow'>0 [0, 1.00]</td>\n<td class='lastrow'>0 [0, 1.00]</td>\n</tr>\n<tr>\n<td class='rowlabel firstrow'>totenrl</td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n</tr>\n<tr>\n<td class='rowlabel'>Mean (SD)</td>\n<td>6110 (16500)</td>\n<td>3010 (4640)</td>\n<td>4850 (13200)</td>\n</tr>\n<tr>\n<td class='rowlabel lastrow'>Median [Min, Max]</td>\n<td class='lastrow'>2700 [260, 493000]</td>\n<td class='lastrow'>1600 [186, 54000]</td>\n<td class='lastrow'>2170 [186, 493000]</td>\n</tr>\n<tr>\n<td class='rowlabel firstrow'>sesavgall</td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n</tr>\n<tr>\n<td class='rowlabel'>Mean (SD)</td>\n<td>0.255 (1.03)</td>\n<td>0.256 (0.781)</td>\n<td>0.256 (0.939)</td>\n</tr>\n<tr>\n<td class='rowlabel lastrow'>Median [Min, Max]</td>\n<td class='lastrow'>0.287 [-3.91, 2.93]</td>\n<td class='lastrow'>0.292 [-4.30, 2.92]</td>\n<td class='lastrow'>0.290 [-4.30, 2.93]</td>\n</tr>\n<tr>\n<td class='rowlabel firstrow'>lninc50avgall</td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n</tr>\n<tr>\n<td class='rowlabel'>Mean (SD)</td>\n<td>10.9 (0.387)</td>\n<td>10.8 (0.284)</td>\n<td>10.9 (0.353)</td>\n</tr>\n<tr>\n<td class='rowlabel lastrow'>Median [Min, Max]</td>\n<td class='lastrow'>10.9 [9.94, 12.3]</td>\n<td class='lastrow'>10.8 [10.1, 12.2]</td>\n<td class='lastrow'>10.9 [9.94, 12.3]</td>\n</tr>\n<tr>\n<td class='rowlabel firstrow'>baplusavgall</td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n<td class='firstrow'></td>\n</tr>\n<tr>\n<td class='rowlabel'>Mean (SD)</td>\n<td>0.273 (0.162)</td>\n<td>0.216 (0.115)</td>\n<td>0.250 (0.148)</td>\n</tr>\n<tr>\n<td class='rowlabel lastrow'>Median [Min, Max]</td>\n<td class='lastrow'>0.225 [0.0194, 0.890]</td>\n<td class='lastrow'>0.181 [0.0291, 0.894]</td>\n<td class='lastrow'>0.202 [0.0194, 0.894]</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nThese differences suggest **confounding** that could bias naive comparisons.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Naive ATE (before matching)\nnaive_model <- lm(yscore22 ~ inperson, data = hw)\nnaive_est <- avg_comparisons(naive_model, variables = \"inperson\")\n\ncat(\"Naive estimate (no adjustment):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNaive estimate (no adjustment):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(naive_est)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error    z Pr(>|z|)    S  2.5 % 97.5 %\n   0.0981     0.0112 8.79   <0.001 59.2 0.0763   0.12\n\nTerm: inperson\nType: response\nComparison: 1 - 0\n```\n\n\n:::\n:::\n\n\n\n### 5.5 Step 2: Estimate Propensity Scores and Check Common Support\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Estimate propensity score using logistic regression\nps_model <- glm(\n  inperson ~ yscore19 + urban + suburb + town + rural + \n             totenrl + sesavgall + lninc50avgall + baplusavgall,\n  data = hw,\n  family = binomial(link = \"logit\")\n)\n\n# Add propensity scores to dataset\nhw$ps <- fitted(ps_model)\nhw$ps_logit <- qlogis(hw$ps)\n\n# Examine propensity score model\nsummary(ps_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = inperson ~ yscore19 + urban + suburb + town + rural + \n    totenrl + sesavgall + lninc50avgall + baplusavgall, family = binomial(link = \"logit\"), \n    data = hw)\n\nCoefficients: (1 not defined because of singularities)\n                Estimate Std. Error z value Pr(>|z|)    \n(Intercept)    4.717e+01  3.121e+00  15.111  < 2e-16 ***\nyscore19       9.164e-01  1.339e-01   6.845 7.66e-12 ***\nurban         -1.296e-01  1.519e-01  -0.853  0.39350    \nsuburb        -7.091e-01  8.834e-02  -8.027 1.00e-15 ***\ntown           1.021e-01  8.206e-02   1.244  0.21354    \nrural                 NA         NA      NA       NA    \ntotenrl       -1.856e-05  6.026e-06  -3.081  0.00207 ** \nsesavgall      1.851e+00  1.163e-01  15.924  < 2e-16 ***\nlninc50avgall -4.297e+00  2.916e-01 -14.735  < 2e-16 ***\nbaplusavgall  -4.098e+00  4.257e-01  -9.626  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 7243.0  on 5357  degrees of freedom\nResidual deviance: 6099.8  on 5349  degrees of freedom\nAIC: 6117.8\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize propensity score overlap\nhw <- hw %>%\n  mutate(group = factor(inperson, \n                        levels = c(0, 1), \n                        labels = c(\"Remote\", \"In-Person\")))\n\n# Linear scale\np_linear <- ggplot(hw, aes(x = ps, fill = group)) +\n  geom_histogram(position = \"identity\", alpha = 0.5, bins = 50) +\n  scale_fill_manual(values = c(\"#ee84a8\", \"#71bced\")) +\n  labs(x = \"Propensity Score\", y = \"Count\", \n       title = \"A) Propensity Score Distribution (Linear Scale)\",\n       fill = NULL) +\n  theme_minimal() +\n  theme(legend.position = \"top\")\n\n# Logit scale\np_logit <- ggplot(hw, aes(x = ps_logit, fill = group)) +\n  geom_histogram(position = \"identity\", alpha = 0.5, bins = 50) +\n  scale_fill_manual(values = c(\"#ee84a8\", \"#71bced\")) +\n  labs(x = \"Logit Propensity Score\", y = \"Count\",\n       title = \"B) Propensity Score Distribution (Logit Scale)\",\n       fill = NULL) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n\n# Jitter plot\np_jitter <- ggplot(hw, aes(x = ps_logit, y = group, color = group)) +\n  geom_jitter(height = 0.15, alpha = 0.3, size = 0.8) +\n  scale_color_manual(values = c(\"#ee84a8\", \"#71bced\")) +\n  labs(x = \"Logit Propensity Score\", y = NULL,\n       title = \"C) Common Support Assessment\",\n       color = NULL) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n\np_linear / p_logit / p_jitter\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/ps-overlap-1.png){width=672}\n:::\n:::\n\n\n\n### 5.6 Step 3: Trim Sample for Common Support\n\nBased on the propensity score distributions, we'll exclude:\n- In-person districts with logit PS > 2 (very high propensity)\n- Remote districts with logit PS < -4 (very low propensity)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Apply trimming rules\nhw <- hw %>%\n  mutate(keep = case_when(\n    group == \"In-Person\" & ps_logit > 2 ~ 0,\n    group == \"Remote\" & ps_logit < -4 ~ 0,\n    TRUE ~ 1\n  ))\n\n# Create trimmed dataset\nhw_trimmed <- hw %>% filter(keep == 1)\n\n# Summarize exclusions\nexcluded_summary <- hw %>%\n  group_by(group) %>%\n  summarise(\n    excluded = sum(keep == 0),\n    remaining = sum(keep == 1),\n    pct_excluded = round(excluded / n() * 100, 1)\n  )\n\nexcluded_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  group     excluded remaining pct_excluded\n  <fct>        <int>     <int>        <dbl>\n1 Remote          18      3157          0.6\n2 In-Person        4      2179          0.2\n```\n\n\n:::\n:::\n\n\nThis trimming excluded **22 districts** (4 in-person, 18 remote), leaving **5,336 districts** for analysis.\n\n### 5.7 Step 4: Implement Multiple Matching Methods\n\nWe'll compare three matching approaches to assess robustness:\n\n1. **1:1 Nearest Neighbor without replacement** (greedy)\n2. **1:1 Nearest Neighbor with caliper and replacement** (quality-controlled)  \n3. **1:1 Optimal matching without replacement** (globally optimal)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define covariate formula\nmatch_formula <- as.formula(\n  \"inperson ~ yscore19 + urban + suburb + town + rural + \n              totenrl + sesavgall + lninc50avgall + baplusavgall\"\n)\n\n# Method 1: Greedy 1:1 matching (no replacement)\nmatch_nn <- matchit(\n  match_formula,\n  data = hw_trimmed,\n  method = \"nearest\",\n  distance = \"glm\",\n  replace = FALSE,\n  ratio = 1,\n  m.order = \"largest\",  # match highest PS first\n  estimand = \"ATT\"\n)\n\n# Method 2: Caliper matching with replacement\nmatch_caliper <- matchit(\n  match_formula,\n  data = hw_trimmed,\n  method = \"nearest\",\n  distance = \"glm\",\n  replace = TRUE,\n  ratio = 1,\n  caliper = 0.1,  # 0.1 SD of logit PS\n  m.order = \"largest\",\n  estimand = \"ATT\"\n)\n\n# Method 3: Optimal 1:1 matching\nmatch_optimal <- matchit(\n  match_formula,\n  data = hw_trimmed,\n  method = \"optimal\",\n  distance = \"glm\",\n  ratio = 1,\n  estimand = \"ATT\"\n)\n\n# Compare sample sizes\ntibble(\n  Method = c(\"Greedy NN\", \"Caliper + Replacement\", \"Optimal\"),\n  N_Treated_Matched = c(\n    match_nn$nn[\"Matched\", \"Treated\"],\n    match_caliper$nn[\"Matched\", \"Treated\"],\n    match_optimal$nn[\"Matched\", \"Treated\"]\n  ),\n  N_Control_Matched = c(\n    match_nn$nn[\"Matched\", \"Control\"],\n    match_caliper$nn[\"Matched\", \"Control\"],\n    match_optimal$nn[\"Matched\", \"Control\"]\n  ),\n  N_Control_ESS = c(\n    match_nn$nn[\"Matched (ESS)\", \"Control\"],\n    match_caliper$nn[\"Matched (ESS)\", \"Control\"],\n    match_optimal$nn[\"Matched (ESS)\", \"Control\"]\n  )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 1\n  Method               \n  <chr>                \n1 Greedy NN            \n2 Caliper + Replacement\n3 Optimal              \n```\n\n\n:::\n:::\n\n\n### 5.8 Step 5: Compare Covariate Balance\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create love plots for each method\np1 <- love.plot(match_nn, \n                stats = \"mean.diffs\",\n                threshold = 0.1, abs = FALSE,\n                colors = c(\"gray50\", \"dodgerblue\"),\n                title = \"1:1 Greedy NN (No Replacement)\") +\n  theme(legend.position = \"none\", axis.title.x = element_blank())\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Standardized mean differences and raw mean differences are present in\nthe same plot. Use the `stars` argument to distinguish between them and\nappropriately label the x-axis. See `?love.plot` for details.\n```\n\n\n:::\n\n```{.r .cell-code}\np2 <- love.plot(match_caliper,\n                stats = \"mean.diffs\", \n                threshold = 0.1, abs = FALSE,\n                colors = c(\"gray50\", \"dodgerblue\"),\n                title = \"1:1 Caliper + Replacement\") +\n  theme(legend.position = \"none\", axis.title.x = element_blank())\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Standardized mean differences and raw mean differences are present in\nthe same plot. Use the `stars` argument to distinguish between them and\nappropriately label the x-axis. See `?love.plot` for details.\n```\n\n\n:::\n\n```{.r .cell-code}\np3 <- love.plot(match_optimal,\n                stats = \"mean.diffs\",\n                threshold = 0.1, abs = FALSE,\n                colors = c(\"gray50\", \"dodgerblue\"),\n                title = \"1:1 Optimal Matching\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Standardized mean differences and raw mean differences are present in\nthe same plot. Use the `stars` argument to distinguish between them and\nappropriately label the x-axis. See `?love.plot` for details.\n```\n\n\n:::\n\n```{.r .cell-code}\n(p1 + p2) / (p3 + plot_spacer()) + plot_layout(heights = c(1, 1))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/balance-comparison-1.png){width=960}\n:::\n:::\n\n\n**Balance Assessment:**\n\nAll three methods substantially improve balance, but differ in quality:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Numerical balance comparison\nbal_nn <- bal.tab(match_nn, un = FALSE)\nbal_cal <- bal.tab(match_caliper, un = FALSE)\nbal_opt <- bal.tab(match_optimal, un = FALSE)\n\n# Extract max absolute SMD\ntibble(\n  Method = c(\"Greedy NN\", \"Caliper + Replacement\", \"Optimal\"),\n  Max_Abs_SMD = c(\n    max(abs(bal_nn$Balance$Diff.Adj), na.rm = TRUE),\n    max(abs(bal_cal$Balance$Diff.Adj), na.rm = TRUE),\n    max(abs(bal_opt$Balance$Diff.Adj), na.rm = TRUE)\n  ),\n  N_Unbalanced = c(\n    sum(abs(bal_nn$Balance$Diff.Adj) > 0.1, na.rm = TRUE),\n    sum(abs(bal_cal$Balance$Diff.Adj) > 0.1, na.rm = TRUE),\n    sum(abs(bal_opt$Balance$Diff.Adj) > 0.1, na.rm = TRUE)\n  )\n) %>%\n  arrange(Max_Abs_SMD)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  Method                Max_Abs_SMD N_Unbalanced\n  <chr>                       <dbl>        <int>\n1 Caliper + Replacement      0.0634            0\n2 Optimal                    0.555             7\n3 Greedy NN                  0.555             7\n```\n\n\n:::\n:::\n\n\n- **Caliper + replacement** achieves the best balance (all |SMD| < 0.1)\n- **Greedy NN** leaves moderate imbalance on several covariates (max |SMD| ≈ 0.56)\n- **Optimal matching** performs similarly to greedy NN\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize PS distributions after matching\nplot_ps_matched <- function(match_obj, title) {\n  md <- match.data(match_obj)\n  ggplot(md, aes(x = distance, fill = group)) +\n    geom_histogram(position = \"identity\", alpha = 0.5, bins = 40) +\n    scale_fill_manual(values = c(\"#ee84a8\", \"#71bced\")) +\n    labs(x = \"Propensity Score\", y = \"Count\", \n         title = title, fill = NULL) +\n    theme_minimal() +\n    theme(legend.position = \"top\")\n}\n\np_nn <- plot_ps_matched(match_nn, \"A) Greedy NN\")\np_cal <- plot_ps_matched(match_caliper, \"B) Caliper + Replacement\")  \np_opt <- plot_ps_matched(match_optimal, \"C) Optimal\")\n\np_nn / p_cal / p_opt\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/ps-overlap-matched-1.png){width=672}\n:::\n:::\n\n\n### 5.9 Step 6: Estimate Treatment Effects\n\nWe'll use doubly-robust estimation: matching + regression adjustment with g-computation for proper standard errors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function for doubly-robust ATT estimation\nestimate_att_dr <- function(match_obj, data_trimmed) {\n  md <- match.data(match_obj)\n  \n  # Remove 'group' variable to avoid conflict with marginaleffects\n  md$group <- NULL\n  \n  # Outcome model with covariates (doubly-robust)\n  mod_dr <- lm(\n    yscore22 ~ inperson + yscore19 + urban + suburb + town + rural +\n               totenrl + sesavgall + lninc50avgall + baplusavgall,\n    data = md,\n    weights = weights\n  )\n  \n  # G-computation for ATT with robust SE\n  avg_comparisons(mod_dr,\n                  variables = \"inperson\",\n                  vcov = \"HC3\",\n                  newdata = subset(md, inperson == 1))\n}\n\n# Estimate ATT for each method\natt_nn <- estimate_att_dr(match_nn, hw_trimmed)\natt_caliper <- estimate_att_dr(match_caliper, hw_trimmed)\natt_optimal <- estimate_att_dr(match_optimal, hw_trimmed)\n\n# Compile results\nresults <- tibble(\n  Method = c(\"Greedy NN\", \"Caliper + Replacement\", \"Optimal\"),\n  Estimate = c(att_nn$estimate, att_caliper$estimate, att_optimal$estimate),\n  SE = c(att_nn$std.error, att_caliper$std.error, att_optimal$std.error),\n  CI_Lower = Estimate - 1.96 * SE,\n  CI_Upper = Estimate + 1.96 * SE,\n  P_Value = c(att_nn$p.value, att_caliper$p.value, att_optimal$p.value)\n) %>%\n  mutate(across(where(is.numeric), ~round(.x, 4)))\n\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 6\n  Method                Estimate     SE CI_Lower CI_Upper P_Value\n  <chr>                    <dbl>  <dbl>    <dbl>    <dbl>   <dbl>\n1 Greedy NN               0.0393 0.0036   0.0323   0.0463       0\n2 Caliper + Replacement   0.0326 0.0052   0.0225   0.0427       0\n3 Optimal                 0.0391 0.0036   0.0321   0.0461       0\n```\n\n\n:::\n:::\n\n\n**Treatment Effect Estimates:**\n\n- **Caliper + replacement** (preferred): ATT = 0.033 SD (95% CI: [0.023, 0.043])\n- **Greedy NN**: ATT = 0.039 SD (95% CI: [0.032, 0.046])\n- **Optimal**: ATT = 0.039 SD (95% CI: [0.032, 0.046])\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(results, aes(x = reorder(Method, Estimate), y = Estimate)) +\n  geom_point(size = 4, color = \"dodgerblue\") +\n  geom_errorbar(aes(ymin = CI_Lower, ymax = CI_Upper),\n                width = 0.2, linewidth = 0.8, color = \"dodgerblue\") +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"gray40\") +\n  coord_flip() +\n  labs(\n    y = \"Estimated ATT (SD units)\",\n    x = NULL,\n    title = \"Treatment Effect of In-Person Instruction on 2022 Math Achievement\",\n    subtitle = \"Error bars show 95% confidence intervals\",\n    caption = \"All estimates significant at α = 0.05\"\n  ) +\n  theme_minimal() +\n  theme(plot.title = element_text(size = 11))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/results-plot-1.png){width=672}\n:::\n:::\n\n\n### 5.10 Step 7: Robustness Check with IPTW\n\nLet's compare with inverse probability of treatment weighting as an alternative approach:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(WeightIt)\n\n# Estimate ATT weights\nw_att <- weightit(\n  inperson ~ yscore19 + urban + suburb + town + rural +\n             totenrl + sesavgall + lninc50avgall + baplusavgall,\n  data = hw_trimmed,\n  estimand = \"ATT\",\n  method = \"glm\"\n)\n\n# Check weight distribution\nsummary(w_att)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Summary of weights\n\n- Weight ranges:\n\n           Min                                  Max\ntreated 1.0000       ||                      1.0000\ncontrol 0.0199 |---------------------------| 5.0301\n\n- Units with the 5 most extreme weights by group:\n                                           \n              6      5      4      2      1\n treated      1      1      1      1      1\n           4023   5208   4329   4210   5289\n control 4.3544 4.4113 4.8355 4.9055 5.0301\n\n- Weight statistics:\n\n        Coef of Var   MAD Entropy # Zeros\ntreated        0.00 0.000   0.000       0\ncontrol        1.04 0.771   0.435       0\n\n- Effective Sample Sizes:\n\n           Control Treated\nUnweighted 3157.      2179\nWeighted   1516.63    2179\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check balance after weighting\nbal.tab(w_att, stats = \"m\", thresholds = c(m = 0.10))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalance Measures\n                  Type Diff.Adj    M.Threshold\nprop.score    Distance   0.0395 Balanced, <0.1\nyscore19       Contin.   0.0148 Balanced, <0.1\nurban           Binary  -0.0007 Balanced, <0.1\nsuburb          Binary  -0.0012 Balanced, <0.1\ntown            Binary  -0.0005 Balanced, <0.1\nrural           Binary   0.0024 Balanced, <0.1\ntotenrl        Contin.  -0.0267 Balanced, <0.1\nsesavgall      Contin.   0.0722 Balanced, <0.1\nlninc50avgall  Contin.   0.0608 Balanced, <0.1\nbaplusavgall   Contin.   0.0090 Balanced, <0.1\n\nBalance tally for mean differences\n                   count\nBalanced, <0.1        10\nNot Balanced, >0.1     0\n\nVariable with the greatest mean difference\n  Variable Diff.Adj    M.Threshold\n sesavgall   0.0722 Balanced, <0.1\n\nEffective sample sizes\n           Control Treated\nUnadjusted 3157.      2179\nAdjusted   1516.63    2179\n```\n\n\n:::\n\n```{.r .cell-code}\n# Doubly-robust outcome model with weights\n# Remove 'group' variable if it exists to avoid conflict with marginaleffects\nhw_iptw <- hw_trimmed\nhw_iptw$group <- NULL\n\nmod_iptw <- lm(\n  yscore22 ~ inperson + yscore19 + urban + suburb + town + rural +\n             totenrl + sesavgall + lninc50avgall + baplusavgall,\n  data = hw_iptw,\n  weights = w_att$weights\n)\n\n# Estimate ATT\natt_iptw <- avg_comparisons(mod_iptw, \n                            variables = \"inperson\",\n                            vcov = \"HC3\",\n                            newdata = subset(hw_iptw, inperson == 1))\n\n# Add to results\nresults_all <- bind_rows(\n  results,\n  tibble(\n    Method = \"IPTW\",\n    Estimate = att_iptw$estimate,\n    SE = att_iptw$std.error,\n    CI_Lower = Estimate - 1.96 * SE,\n    CI_Upper = Estimate + 1.96 * SE,\n    P_Value = att_iptw$p.value\n  )\n) %>%\n  mutate(across(where(is.numeric), ~round(.x, 4)))\n\nresults_all\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 6\n  Method                Estimate     SE CI_Lower CI_Upper P_Value\n  <chr>                    <dbl>  <dbl>    <dbl>    <dbl>   <dbl>\n1 Greedy NN               0.0393 0.0036   0.0323   0.0463       0\n2 Caliper + Replacement   0.0326 0.0052   0.0225   0.0427       0\n3 Optimal                 0.0391 0.0036   0.0321   0.0461       0\n4 IPTW                    0.0368 0.0038   0.0294   0.0442       0\n```\n\n\n:::\n:::\n\n\nIPTW yields a consistent estimate (ATT = 0.036).\n\n### 5.11 Step 8: Sensitivity Analysis\n\nHow robust are these findings to potential unobserved confounding?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sensemakr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSee details in:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCarlos Cinelli and Chad Hazlett (2020). Making Sense of Sensitivity: Extending Omitted Variable Bias. Journal of the Royal Statistical Society, Series B (Statistical Methodology).\n```\n\n\n:::\n\n```{.r .cell-code}\n# Use the caliper + replacement model (best balance)\nmd_caliper <- match.data(match_caliper)\nmod_sens <- lm(\n  yscore22 ~ inperson + yscore19 + urban + suburb + town + rural +\n             totenrl + sesavgall + lninc50avgall + baplusavgall,\n  data = md_caliper,\n  weights = weights\n)\n\n# Sensitivity analysis\nsens <- sensemakr(\n  model = mod_sens,\n  treatment = \"inperson\",\n  benchmark_covariates = \"yscore19\",  # Use baseline achievement as benchmark\n  kd = 1:2, ky = 1:2,\n  q = 1,  # Effect goes to zero\n  alpha = 0.05,\n  reduce = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in ovb_partial_r2_bound.numeric(r2dxj.x = r2dxj.x[i], r2yxj.dx =\nr2yxj.dx[i], : Implied bound on r2yz.dx greater than 1, try lower kd and/or ky.\nSetting r2yz.dx to 1.\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(sens)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSensitivity Analysis to Unobserved Confounding\n\nModel Formula: yscore22 ~ inperson + yscore19 + urban + suburb + town + rural + \n    totenrl + sesavgall + lninc50avgall + baplusavgall\n\nNull hypothesis: q = 1 and reduce = TRUE \n-- This means we are considering biases that reduce the absolute value of the current estimate.\n-- The null hypothesis deemed problematic is H0:tau = 0 \n\nUnadjusted Estimates of 'inperson': \n  Coef. estimate: 0.0326 \n  Standard Error: 0.0043 \n  t-value (H0:tau = 0): 7.6317 \n\nSensitivity Statistics:\n  Partial R2 of treatment with outcome: 0.0174 \n  Robustness Value, q = 1: 0.1245 \n  Robustness Value, q = 1, alpha = 0.05: 0.0941 \n\nVerbal interpretation of sensitivity statistics:\n\n-- Partial R2 of the treatment with the outcome: an extreme confounder (orthogonal to the covariates) that explains 100% of the residual variance of the outcome, would need to explain at least 1.74% of the residual variance of the treatment to fully account for the observed estimated effect.\n\n-- Robustness Value, q = 1: unobserved confounders (orthogonal to the covariates) that explain more than 12.45% of the residual variance of both the treatment and the outcome are strong enough to bring the point estimate to 0 (a bias of 100% of the original estimate). Conversely, unobserved confounders that do not explain more than 12.45% of the residual variance of both the treatment and the outcome are not strong enough to bring the point estimate to 0.\n\n-- Robustness Value, q = 1, alpha = 0.05: unobserved confounders (orthogonal to the covariates) that explain more than 9.41% of the residual variance of both the treatment and the outcome are strong enough to bring the estimate to a range where it is no longer 'statistically different' from 0 (a bias of 100% of the original estimate), at the significance level of alpha = 0.05. Conversely, unobserved confounders that do not explain more than 9.41% of the residual variance of both the treatment and the outcome are not strong enough to bring the estimate to a range where it is no longer 'statistically different' from 0, at the significance level of alpha = 0.05.\n\nBounds on omitted variable bias:\n\n--The table below shows the maximum strength of unobserved confounders with association with the treatment and the outcome bounded by a multiple of the observed explanatory power of the chosen benchmark covariate(s).\n\n Bound Label R2dz.x R2yz.dx Treatment Adjusted Estimate Adjusted Se Adjusted T\n 1x yscore19 0.0015       1  inperson            0.0231           0        Inf\n 2x yscore19 0.0030       1  inperson            0.0192           0        Inf\n Adjusted Lower CI Adjusted Upper CI\n            0.0231            0.0231\n            0.0192            0.0192\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(sens)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/sensitivity-1.png){width=672}\n:::\n:::\n\n\n**Sensitivity Analysis Findings:**\n\n- **Robustness Value (RV)** for nullifying effect: 12.45%\n  - An unobserved confounder would need to explain **>12% of residual variance** in both treatment and outcome to eliminate the effect entirely\n  \n- **RV for losing significance** (α = 0.05): 9.41%\n  - Relatively robust threshold\n  \n- **Benchmark comparison:** The unobserved confounder would need to be **stronger than baseline achievement** (`yscore19`), which is already a powerful predictor\n\n**Interpretation:** While unmeasured confounding remains a concern, the effect appears reasonably robust. Potential unobserved confounders would need relative large explanatory power to overturn the findings.\n\n---\n\n*This tutorial is based on lecture materials from Stat 256: Causality (UCLA) and EDUC 255C: Introduction to Causal Inference in Education Research (UCLA), Spring 2025.*\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/table1-1.0/table1_defaults.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}