{
  "hash": "a5c5f56626db300eec3f4b53b67a1c39",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"How to code Race?\"\nauthor: Shuhan (Alice) Ai\ndate: \"2025-06-25\"\ncategories: [R, Critical Quant]\ntoc: true\ntoc-depth: 3\ntoc-title: \"Contents\"\nimage: \"racecode.jpg\"\n---\n\n\n\nThis post will show several ways of race coding in quantitative social science research. \n\n![](racecode.jpg)\n\n## Introduction\n\nWhen conducting social science research, especially in critical quantitative studies, race is a sensitive variable that requires careful consideration. Traditional approaches to coding race often fall short when attempting to capture the complex realities of students who identify with multiple racial categories. This tutorial will explore three different methods for handling race variables in your analyses, each method has advantages and limitations.\n\n## The Traditional Way: Categorical Coding\n\nThe traditional approach treats race as a single categorical variable with mutually exclusive categories such as White, Black, Asian, Hispanic, Multiracial, and Other. This method forces each participant into one category, even if they identify with multiple racial groups.\n\nFollowing is a simulated dataset to demonstrate this approach:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(car)\n\nset.seed(123)\n\n#Simulate traditional categorical race data\nn <- 500\ntraditional_data <- data.frame(\n  student_id = 1:n,\n  race_traditional = sample(c(\"White\", \"Black\", \"Asian\", \"Hispanic\", \"Multiracial\", \"Other\"), \n                           n, replace = TRUE, \n                           prob = c(0.45, 0.15, 0.20, 0.12, 0.06, 0.02)),\n  college_gpa = rnorm(n, mean = 3.2, sd = 0.5),\n  science_identity = rnorm(n, mean = 4.0, sd = 1.2)\n)\n\ntraditional_data$science_identity[traditional_data$race_traditional == \"Asian\"] <- \n  traditional_data$science_identity[traditional_data$race_traditional == \"Asian\"] + 0.3\n\nhead(traditional_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  student_id race_traditional college_gpa science_identity\n1          1            White    3.012199         5.846116\n2          2            Black    2.919062         3.868348\n3          3            White    3.028041         4.613765\n4          4         Hispanic    3.245248         4.256750\n5          5      Multiracial    3.999254         3.776655\n6          6            White    3.155717         3.855527\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(traditional_data$race_traditional)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      Asian       Black    Hispanic Multiracial       Other       White \n         92          77          55          27          12         237 \n```\n\n\n:::\n\n```{.r .cell-code}\n#Check the factor levels - this determines the reference group\nlevels(factor(traditional_data$race_traditional))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Asian\"       \"Black\"       \"Hispanic\"    \"Multiracial\" \"Other\"      \n[6] \"White\"      \n```\n\n\n:::\n\n```{.r .cell-code}\n# By default, R uses alphabetical order, so \"Asian\" would be the reference group\n\n#Explicitly set White as reference group for clearer interpretation\ntraditional_data$race_traditional <- factor(traditional_data$race_traditional, \n          levels = c(\"White\", \"Asian\", \"Black\", \"Hispanic\", \"Multiracial\", \"Other\"))\n\n# Confirm White is now the reference group (first level)\nlevels(traditional_data$race_traditional)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"White\"       \"Asian\"       \"Black\"       \"Hispanic\"    \"Multiracial\"\n[6] \"Other\"      \n```\n\n\n:::\n:::\n\n\n\n\n### Potential Analysis with Traditional Race Coding\n\n- Regression analysis\n- ANOVA\n- Post-hoc tests\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Linear regression with traditional categorical race variable\ntraditional_model <- lm(science_identity ~ race_traditional + college_gpa, data = traditional_data)\nsummary(traditional_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = science_identity ~ race_traditional + college_gpa, \n    data = traditional_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.1993 -0.8330  0.0016  0.7314  3.7727 \n\nCoefficients:\n                            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                  4.13485    0.35884  11.523  < 2e-16 ***\nrace_traditionalAsian        0.40274    0.15044   2.677  0.00767 ** \nrace_traditionalBlack        0.01130    0.16081   0.070  0.94399    \nrace_traditionalHispanic     0.04394    0.18348   0.240  0.81082    \nrace_traditionalMultiracial  0.05976    0.24887   0.240  0.81032    \nrace_traditionalOther       -0.35093    0.36377  -0.965  0.33516    \ncollege_gpa                 -0.03989    0.10991  -0.363  0.71683    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.224 on 493 degrees of freedom\nMultiple R-squared:  0.01832,\tAdjusted R-squared:  0.006373 \nF-statistic: 1.533 on 6 and 493 DF,  p-value: 0.1652\n```\n\n\n:::\n\n```{.r .cell-code}\n#Additional analyses\n# ANOVA for science identity by race\nanova_result <- aov(science_identity ~ race_traditional, data = traditional_data)\nsummary(anova_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Df Sum Sq Mean Sq F value Pr(>F)\nrace_traditional   5   13.6   2.718   1.817  0.108\nResiduals        494  739.0   1.496               \n```\n\n\n:::\n\n```{.r .cell-code}\n#Post-hoc tests\nTukeyHSD(anova_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = science_identity ~ race_traditional, data = traditional_data)\n\n$race_traditional\n                             diff         lwr       upr     p adj\nAsian-White           0.401102578 -0.02873138 0.8309365 0.0832504\nBlack-White           0.008146734 -0.45085693 0.4671504 1.0000000\nHispanic-White        0.040401167 -0.48332801 0.5641303 0.9999281\nMultiracial-White     0.056002743 -0.65474710 0.7667526 0.9999202\nOther-White          -0.338777734 -1.37417196 0.6966165 0.9370082\nBlack-Asian          -0.392955844 -0.93343001 0.1475183 0.2994279\nHispanic-Asian       -0.360701411 -0.95712426 0.2357214 0.5123743\nMultiracial-Asian    -0.345099835 -1.11099362 0.4207940 0.7910142\nOther-Asian          -0.739880312 -1.81387713 0.3341165 0.3606136\nHispanic-Black        0.032254433 -0.58552169 0.6500306 0.9999896\nMultiracial-Black     0.047856009 -0.73478083 0.8304928 0.9999773\nOther-Black          -0.346924468 -1.43292460 0.7390757 0.9428997\nMultiracial-Hispanic  0.015601576 -0.80666864 0.8378718 0.9999999\nOther-Hispanic       -0.379178901 -1.49407987 0.7357221 0.9263404\nOther-Multiracial    -0.394780477 -1.60881395 0.8192530 0.9385782\n```\n\n\n:::\n:::\n\n\n### Advantages \n\n- **Simplicity:** Easy to understand and implement.\n- **Support Standard analyses:** Compatible with ANOVA, chi-square tests, and most statistical procedures.\n- **Clear group comparisons:** Straightforward interpretation of group differences.\n\n\n### Disadvantages\n\n- **Reference group dependency:** Results are interpreted relative to a chosen reference category (typically White), which can reinforce hierarchical thinking about race.\n- **Lmited representation:** Students identifying as both White and Hispanic, or Black and Asian, are lumped into a generic \"Multiracial\" category. This \"Multiracial\" category obscures the specific combination of racial identities.\n\n## Alternative Way 1: Binary Coding\n\nDummy coding creates separate binary variables for each racial category, allowing students to be coded as belonging to multiple groups simultaneously.\n\nLet's see a simulated case.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Create dummy-coded race variables\ndummy_data <- data.frame(\n  student_id = 1:n,\n  college_gpa = rnorm(n, mean = 3.2, sd = 0.5),\n  science_identity = rnorm(n, mean = 4.0, sd = 1.2)\n)\n\n#Create binary race variables (allowing multiple identities)\ndummy_data$white <- sample(c(0, 1), n, replace = TRUE, prob = c(0.6, 0.4))\ndummy_data$black <- sample(c(0, 1), n, replace = TRUE, prob = c(0.85, 0.15))\ndummy_data$asian <- sample(c(0, 1), n, replace = TRUE, prob = c(0.75, 0.25))\ndummy_data$hispanic <- sample(c(0, 1), n, replace = TRUE, prob = c(0.85, 0.15))\n\n#Add a multiracial category for students identifying with multiple groups\ndummy_data$multiracial <- 0\n\n#Ensure some students have multiple identities\nmultiracial_ids <- sample(1:n, size = 30)\ndummy_data$asian[multiracial_ids[1:15]] <- 1\ndummy_data$white[multiracial_ids[1:15]] <- 1\ndummy_data$multiracial[multiracial_ids[1:15]] <- 1  #mark as multiracial\n\ndummy_data$black[multiracial_ids[16:30]] <- 1\ndummy_data$hispanic[multiracial_ids[16:30]] <- 1\ndummy_data$multiracial[multiracial_ids[16:30]] <- 1  #mark as multiracial\n\ndummy_data$science_identity[dummy_data$asian == 1] <- \n  dummy_data$science_identity[dummy_data$asian == 1] + 0.3\n\ndummy_data$total_races <- dummy_data$white + dummy_data$black + \n                         dummy_data$asian + dummy_data$hispanic + dummy_data$multiracial\n```\n:::\n\n\n\n### Potential Analysis with Binary Race Coding\n\n- Regression analysis\n- t.test\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Linear regression with dummy-coded race variables\ndummy_model <- lm(science_identity ~ white + black + asian + hispanic + multiracial + college_gpa, \n                  data = dummy_data)\nsummary(dummy_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = science_identity ~ white + black + asian + hispanic + \n    multiracial + college_gpa, data = dummy_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.1157 -0.7986 -0.0094  0.7565  3.4763 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  4.50824    0.34959  12.896   <2e-16 ***\nwhite        0.16506    0.10748   1.536   0.1252    \nblack       -0.04779    0.14274  -0.335   0.7379    \nasian        0.22991    0.11929   1.927   0.0545 .  \nhispanic    -0.07766    0.14697  -0.528   0.5975    \nmultiracial  0.18770    0.24330   0.771   0.4408    \ncollege_gpa -0.17517    0.10467  -1.673   0.0949 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.162 on 493 degrees of freedom\nMultiple R-squared:  0.02285,\tAdjusted R-squared:  0.01096 \nF-statistic: 1.921 on 6 and 493 DF,  p-value: 0.07568\n```\n\n\n:::\n\n```{.r .cell-code}\n#Analysis of White-Asian students specifically\nwhite_asian <- dummy_data[dummy_data$white == 1 & dummy_data$asian == 1, ]\nmean(white_asian$science_identity, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.220716\n```\n\n\n:::\n\n```{.r .cell-code}\n#Compare with single-race students science identity vs multi-race identity\nsingle_race <- dummy_data[dummy_data$total_races == 1, ]\nmulti_race <- dummy_data[dummy_data$total_races > 1, ]\n\nt.test(single_race$science_identity, multi_race$science_identity)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  single_race$science_identity and multi_race$science_identity\nt = -0.2536, df = 302.83, p-value = 0.8\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -0.2799823  0.2160553\nsample estimates:\nmean of x mean of y \n 4.137296  4.169259 \n```\n\n\n:::\n:::\n\n\n\n### Advantages\n\n- **Captures multiple identities:** Students can be coded as belonging to multiple racial groups.\n- **Specific comparisons:** Researchers can examine the unique characteristics of specific multiracial combinations.\n- **Flexible analysis:** No forced categorization, better represents how students actually identify.\n\n### Disadvantages\n\n- **Inflated sample size:** The sum of all racial categories exceeds the actual number of participants.\n- **Statistical complications:** Traditional categorical tests (chi-square) are no longer appropriate.\n- **Interpretation complexity:** More difficult to interpret main effects when students belong to multiple categories.\n- **Multicollinearity concerns:** Racial variables may be correlated with each other.\n\n\n## Alternative Way 2: Effect Coding\n\n[Mayhew & Simonoff (2015)](https://link.springer.com/article/10.1007/s11162-015-9364-0) propose **effect coding** as alternative approach that doesn't rely on a reference group and better handles students who check multiple racial boxes.\n\n> **Reference**: Mayhew, M. J., & Simonoff, J. S. (2015). Effect Coding as a Mechanism for Improving the Accuracy of Measuring Students Who Self‑Identify with More than One Race. *Research in Higher Education*, 56(6), 571–600.\n\n### Statistical Idea\n\nEffect coding (also known for **sum-to-zero coding**) forces the set of race‑indicator columns for **each student** to sum to 0.  When a respondent can select more than one race, Mayhew & Simonoff (2015) recommend *fractional weights* so the rule still holds.\n\n> **Rule of thumb**  If a student selects *m* race boxes, give each selected category a weight of **1 / m**.  The omitted reference column automatically gets the negative of the row‑sum, keeping totals at 0.\n\n#### Mini example: three race categories (A, B, C)\n\nWith three categories we need only **two** coded columns (EA and EB).  The table below reproduces the logic in Mayhew & Simonoff’s Table 1 and shows how multi‑race selections receive fractional weights.\n\n| Selected Races   | $E_A$   | $E_B$   | Expected Mean of *y*         |\n|------------------|---------|---------|-------------------------------|\n| A                | $1$     | $0$     | $b_0 + b_A$                   |\n| B                | $0$     | $1$     | $b_0 + b_B$                   |\n| C                | $-1$    | $-1$    | $b_0 - b_A - b_B$             |\n| A & B            | $1/2$   | $1/2$   | $b_0 + \\frac{b_A}{2} + \\frac{b_B}{2}$ |\n| A & C            | $0$     | $-1/2$  | $b_0 - \\frac{b_B}{2}$         |\n| B & C            | $-1/2$  | $0$    | $b_0 - \\frac{b_A}{2}$         |\n| A, B & C         | $0$     | $0$     | $b_0$                         |\n\n\n- Intercept (b0) is the grand mean across all racial groups.\n- Each coefficient (bA, bB) is that group’s deviation from the grand mean.\n- Because rows always add to 0, no single group is the \"reference group\".\n\n#### Generalising to *k* categories\n\n`contr.sum(k)` makes the k – 1 columns automatically. It sets up the k − 1 contrast vectors for single-race categories. The last category (by default) is omitted and represented as the negative sum of the other categories' contrasts.\n\n### Apply Effect Coding and Run the Regression\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Use the same traditional categorical race data\neffect_data <- traditional_data\n\n#Convert race_traditional to factor for effect coding\neffect_data$race_traditional <- factor(effect_data$race_traditional)\ntable(effect_data$race_traditional)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      White       Asian       Black    Hispanic Multiracial       Other \n        237          92          77          55          27          12 \n```\n\n\n:::\n\n```{.r .cell-code}\n#Create effect-coded contrasts\n#This will use \"Other\" as the omitted category (coded as -1 for all contrasts, like C in the above example)\ncontrasts(effect_data$race_traditional) <- contr.sum(6)\n#contrasts(effect_data$race_traditional) <- contr.sum(length(levels(effect_data$race_traditional))) - same above\n\n#Check the contrast matrix\ncontrasts(effect_data$race_traditional)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            [,1] [,2] [,3] [,4] [,5]\nWhite          1    0    0    0    0\nAsian          0    1    0    0    0\nBlack          0    0    1    0    0\nHispanic       0    0    0    1    0\nMultiracial    0    0    0    0    1\nOther         -1   -1   -1   -1   -1\n```\n\n\n:::\n\n```{.r .cell-code}\n#Run the linear regression model\neffect_model_1 <- lm(science_identity ~ race_traditional + college_gpa, data = effect_data)\nsummary(effect_model_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = science_identity ~ race_traditional + college_gpa, \n    data = effect_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.1993 -0.8330  0.0016  0.7314  3.7727 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        4.16265    0.35967  11.574  < 2e-16 ***\nrace_traditional1 -0.02780    0.10560  -0.263  0.79244    \nrace_traditional2  0.37494    0.13348   2.809  0.00517 ** \nrace_traditional3 -0.01650    0.14138  -0.117  0.90714    \nrace_traditional4  0.01614    0.15874   0.102  0.91905    \nrace_traditional5  0.03196    0.20987   0.152  0.87903    \ncollege_gpa       -0.03989    0.10991  -0.363  0.71683    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.224 on 493 degrees of freedom\nMultiple R-squared:  0.01832,\tAdjusted R-squared:  0.006373 \nF-statistic: 1.533 on 6 and 493 DF,  p-value: 0.1652\n```\n\n\n:::\n:::\n\n\n\n- The intercept 4.16 is the **grand mean** of science identity across all races.\n- Each race coefficient represents the difference from the grand mean:\n  - Asian (-0.028): Students identifying as Asian have a science_identity ~0.028 points below the grand mean (not statistically significant).\n  - Black (+0.375): Students identifying as Black have science_identity ~0.375 points above the grand mean (significant at p < .01).\n  - Hispanic (-0.017): Slightly below the grand mean, not significant.\n  - Multiracial (+0.016): Slightly above the grand mean, not significant.\n  - White (+0.032): Slightly above the grand mean, not significant.\n- “Other” is the omitted category:\n  - Its value is the negative sum of all the other categories' contrasts.\n  - So its deviation from the grand mean is:\n    - $-(sum) = -(-0.0278 + 0.3749 - 0.0165 + 0.0161 + 0.03196) ≈ -0.379$\n    - So “Other” is $-0.379$ points below the grand mean, which is also the lowest science identity group.\n\n### Advantages\n- **No reference group:** Coefficients represent deviations from the grand mean, avoiding hierarchical comparisons.\n- **Clearer interpretation:** Effects are interpreted relative to the overall sample mean.\n- **Reduced bias:** Eliminates the arbitrary choice of reference group that can influence interpretation.\n\n### Disadvantages\n- **Interpretation challenges:** In multiracial applications, may still obscure differences between specific combinations (e.g., White-Black vs. Black-Asian students)\n\n\n## Summary\n\n### Which Method Should I Use?\n\nThe choice of coding method should ultimately depend on your research questions:\n\n- If your research question focuses on comparing specific racial groups to a meaningful reference category (e.g., comparing minority groups to White students), traditional dummy coding may be appropriate.\n- If you want to understand the unique experiences of students with multiple racial identities, dummy coding with binary race variables allows the most flexibility.\n- If you want to avoid the hierarchical implications of reference groups and focus on how each group differs from the overall population, effect coding is preferable.\n- If your research question requires understanding specific multiracial combinations (e.g., White-Asian vs. Black-Hispanic experiences), consider creating specific categorical variables for the combinations of interest.\n\n### Final Considerations\nRegardless of the coding method chosen, researchers should:\n\n- Be transparent about your coding decisions and rationale.\n- Consider the theoretical implications of your chosen approach.\n- Validate your approach with sensitivity analyses when possible.\n- Acknowledge the limitations of your chosen method in the discussion.\n\nRemember that no single approach perfectly captures the complexity of racial identity. The goal is to choose the method that best serves your research questions while remaining sensitive to the lived experiences of the students you're studying.\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}